"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Building2, CheckCircle2, Circle, ClipboardCheck, ExternalLink, FileText, Gauge, History, ListChecks, LoaderCircle, NotebookPen, Save, Sparkles, Target, TriangleAlert, X } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { apiGet, apiPatch, apiPost } from "@/lib/api";
import { OpportunityBriefing } from "@/components/opportunity-briefing";
import { CaptureAssessment } from "@/components/capture-assessment";
import { WinStrategy } from "@/components/win-strategy";
import { CaptureCommandCenter } from "@/components/capture-command-center";
import { ProposalWorkspace } from "@/components/proposal-workspace";
import { ProposalExecution } from "@/components/proposal-execution";
import { SubmissionControl } from "@/components/submission-control";

type DocumentRow={name:string;url:string;preview_available?:boolean};
type IncumbentSignal={recipient_name:string;recipient_uei?:string;award_count:number;obligated:number;latest_end?:string|null};
type Detail={opportunity:Record<string,unknown>;description:string;documents:DocumentRow[];source_url:string;incumbent_signals?:IncumbentSignal[];incumbent_signal_note?:string};
type ComplianceItem={id:string;label:string;complete:boolean;source?:string};
type AiSource={label:string;type:string;title:string;url?:string};
type Workspace={id:number;notes:string;capture_summary:string;risks:string[];compliance_items:ComplianceItem[];decision:string;updated_at:string};
type EvidenceRow={source:string;source_kind:"official"|"platform"|"user"|"ai_derived";title:string;url?:string;observed_at:string;confidence:"high"|"medium"|"low"|"unknown";detail?:string};
type OpportunityIntelligence={subject_id:string;subject_type:string;generated_at:string;warnings:string[];evidence:EvidenceRow[];data:{opportunity:{source_id:string;title:string;agency:string;naics:string;psc:string;source_url:string};incumbent:Record<string,unknown>;past_winners:Array<Record<string,unknown>>;likely_competitors:Array<Record<string,unknown>>;teaming_recommendations:Array<Record<string,unknown>>;labels:Record<string,string>}};
function value(row:Record<string,unknown>,key:string){const item=row[key];return item===null||item===undefined||item===""?"—":String(item)}
function previewable(document:DocumentRow){return document.preview_available||/\.(pdf|txt|html?)(\?|$)/i.test(document.url)}
function defaultChecklist(data:Detail):ComplianceItem[]{
 const o=data.opportunity; const rows:ComplianceItem[]=[
  {id:"deadline",label:`Confirm response deadline: ${value(o,"responseDeadLine")}`,complete:false,source:"SAM.gov"},
  {id:"naics",label:`Validate NAICS and size standard: ${value(o,"naicsCode")}`,complete:false,source:"SAM.gov"},
  {id:"setaside",label:`Confirm set-aside eligibility: ${value(o,"typeOfSetAsideDescription")}`,complete:false,source:"SAM.gov"},
  {id:"scope",label:"Review scope, deliverables, and performance locations",complete:false,source:"Description"},
  {id:"submission",label:"Identify all submission instructions and required volumes",complete:false,source:"Solicitation files"},
  {id:"evaluation",label:"Extract evaluation factors and scoring priorities",complete:false,source:"Solicitation files"},
 ];
 return rows;
}
function StructuredOpportunityAnswer({content}:{content:string}){const blocks=content.split(/\n{2,}/).map(v=>v.trim()).filter(Boolean);return <div className="structured-ai-answer">{blocks.map((block,index)=>{const lines=block.split("\n").map(v=>v.trim()).filter(Boolean);const heading=/^#{1,6}\s/.test(lines[0]??"")||/^\*\*.+\*\*:?$/.test(lines[0]??"");const title=lines[0]?.replace(/^#{1,6}\s*/,"").replace(/^\*\*(.+)\*\*:?$/,"$1").replace(/:$/,"");const body=heading?lines.slice(1):lines;return <section className="ai-insight-card" key={index}>{heading&&<h3>{title}</h3>}{body.map((line,i)=>/^[-•*]\s+/.test(line)?<div className="ai-bullet" key={i}><span/><p>{line.replace(/^[-•*]\s+/,"")}</p></div>:<p key={i}>{line}</p>)}</section>})}</div>}

export default function FederalOpportunityDetailPage(){
 const params=useParams<{noticeId:string}>();const noticeId=decodeURIComponent(params.noticeId);
 const[data,setData]=useState<Detail|null>(null);const[loadState,setLoadState]=useState<"loading"|"loaded"|"error">("loading");const[message,setMessage]=useState("Loading SAM.gov opportunity details and documents…");const[adding,setAdding]=useState(false);const[viewer,setViewer]=useState<DocumentRow|null>(null);
 const[question,setQuestion]=useState("");const[answer,setAnswer]=useState("");const[aiSources,setAiSources]=useState<AiSource[]>([]);const[asking,setAsking]=useState(false);const[intelligence,setIntelligence]=useState<OpportunityIntelligence|null>(null);const[intelligenceMessage,setIntelligenceMessage]=useState("");const[activeTab,setActiveTab]=useState<"command_center"|"proposal"|"proposal_execution"|"submission_control"|"capture"|"win_strategy"|"overview"|"intelligence"|"briefing"|"compliance"|"notes"|"timeline">("command_center");
 const[workspace,setWorkspace]=useState<Workspace|null>(null);const[workspaceMessage,setWorkspaceMessage]=useState("");const[saving,setSaving]=useState(false);
 const loadWorkspace=useCallback(async()=>{try{const result=await apiGet<Workspace>(`/workflow/opportunity-workspaces/${encodeURIComponent(noticeId)}/`);setWorkspace(result)}catch(error){setWorkspaceMessage(error instanceof Error?error.message:"Workspace could not be loaded")}},[noticeId]);
 const loadIntelligence=useCallback(async()=>{try{const result=await apiGet<OpportunityIntelligence>(`/intelligence/opportunities/${encodeURIComponent(noticeId)}/`);setIntelligence(result);setIntelligenceMessage(result.warnings?.[0]??"")}catch(error){setIntelligence(null);setIntelligenceMessage(error instanceof Error?error.message:"Opportunity intelligence could not be loaded")}},[noticeId]);
 const load=useCallback(async()=>{setLoadState("loading");try{const result=await apiGet<Detail>(`/live/sam/opportunities/${encodeURIComponent(noticeId)}/`);setData(result);setLoadState("loaded");setMessage(`${result.documents?.length??0} public documents loaded.`);void loadWorkspace();void loadIntelligence()}catch(error){setData(null);setLoadState("error");setMessage(error instanceof Error?error.message:"Opportunity detail could not be loaded")}},[noticeId,loadWorkspace,loadIntelligence]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function addToPipeline(){setAdding(true);try{await apiPost("/workflow/opportunity-to-pipeline/",{source_id:noticeId,stage:"reviewing"});setMessage("Opportunity added to the capture pipeline.");await loadWorkspace()}catch(error){setMessage(error instanceof Error?error.message:"Opportunity could not be added")}finally{setAdding(false)}}
 async function ask(event?:FormEvent,preset?:string){event?.preventDefault();const prompt=preset??question;if(!prompt.trim()||!data)return;setQuestion(prompt);setAsking(true);setAnswer("");setAiSources([]);try{const result=await apiPost<{answer:string;sources?:AiSource[]}>(`/ai/opportunities/${encodeURIComponent(noticeId)}/ask/`,{message:prompt});setAnswer(result.answer);setAiSources(result.sources??[])}catch(error){setAnswer(error instanceof Error?error.message:"ForgeGov AI could not analyze this opportunity")}finally{setAsking(false)}} async function saveWorkspace(next:Partial<Workspace>={}){if(!workspace)return;setSaving(true);setWorkspaceMessage("");try{const result=await apiPatch<Workspace>(`/workflow/opportunity-workspaces/${encodeURIComponent(noticeId)}/`,{notes:next.notes??workspace.notes,capture_summary:next.capture_summary??workspace.capture_summary,risks:next.risks??workspace.risks,compliance_items:next.compliance_items??workspace.compliance_items,decision:next.decision??workspace.decision});setWorkspace(result);setWorkspaceMessage("Workspace saved.")}catch(error){setWorkspaceMessage(error instanceof Error?error.message:"Workspace could not be saved")}finally{setSaving(false)}}
 function initializeChecklist(){if(!data||!workspace)return;const next={...workspace,compliance_items:defaultChecklist(data)};setWorkspace(next);void saveWorkspace(next)}
 const opportunity=useMemo(()=>data?.opportunity??{},[data]);
 const timeline=useMemo(()=>data?[{label:"Posted",date:value(opportunity,"postedDate")},{label:"Updated",date:value(opportunity,"modifiedDate")},{label:"Response deadline",date:value(opportunity,"responseDeadLine")},{label:"Archive date",date:value(opportunity,"archiveDate")}].filter(row=>row.date!=="—"):[],[data,opportunity]);
 const completed=workspace?.compliance_items?.filter(item=>item.complete).length??0;const total=workspace?.compliance_items?.length??0;
 return <><header className="feature-hero opportunity-detail-hero"><div><Link className="detail-back" href="/opportunities/federal-contracts"><ArrowLeft size={16}/> Back to search</Link><span className="eyebrow">SAM.gov opportunity workspace</span><h1>{value(opportunity,"title")}</h1><p><Link className="entity-link hero-entity-link" href={`/intelligence/agency/${encodeURIComponent(value(opportunity,"fullParentPathName"))}`}>{value(opportunity,"fullParentPathName")} ↗</Link></p></div><div className="detail-actions">{data?.source_url?<a className="secondary-button" href={data.source_url} target="_blank" rel="noreferrer">Original source <ExternalLink size={16}/></a>:null}<button className="primary-button" onClick={()=>void addToPipeline()} disabled={adding||!data}><Target size={16}/>{adding?"Adding…":"Add to pipeline"}</button></div></header><p className="inline-message">{message}</p>
 {!data?<div className="table-state">{loadState==="loading"?<><LoaderCircle className="spin"/><strong>Loading opportunity</strong><p>Retrieving the canonical SAM.gov record and public documents.</p></>:<><TriangleAlert/><strong>Opportunity workspace unavailable</strong><p>{message}</p><div className="row-actions"><button className="primary-button" onClick={()=>void load()}>Retry</button><Link className="secondary-button" href="/opportunities/federal-contracts">Return to search</Link></div></>}</div>:<><section className="insight-strip detail-facts"><div><span>Solicitation</span><strong>{value(opportunity,"solicitationNumber")}</strong></div><div><span>Notice type</span><strong>{value(opportunity,"type")}</strong></div><div><span>NAICS</span><strong>{value(opportunity,"naicsCode")}</strong></div><div><span>Deadline</span><strong>{value(opportunity,"responseDeadLine")}</strong></div></section>
 <nav className="workspace-tabs"><button className={activeTab==="command_center"?"active":""} onClick={()=>setActiveTab("command_center")}><Target size={16}/> Command Center</button><button className={activeTab==="proposal"?"active":""} onClick={()=>setActiveTab("proposal")}><ListChecks size={16}/> Proposal Workspace <span className="tab-new-badge">NEW</span></button><button className={activeTab==="proposal_execution"?"active":""} onClick={()=>setActiveTab("proposal_execution")}><ClipboardCheck size={16}/> Proposal Execution <span className="tab-new-badge">NEW</span></button><button className={activeTab==="submission_control"?"active":""} onClick={()=>setActiveTab("submission_control")}><FileText size={16}/> Submission Control <span className="tab-new-badge">NEW</span></button><button className={activeTab==="capture"?"active":""} onClick={()=>setActiveTab("capture")}><Gauge size={16}/> Executive Capture</button><button className={activeTab==="win_strategy"?"active":""} onClick={()=>setActiveTab("win_strategy")}><Target size={16}/> Win Strategy <span className="tab-new-badge">NEW</span></button><button className={activeTab==="overview"?"active":""} onClick={()=>setActiveTab("overview")}><FileText size={16}/> Overview</button><button className={activeTab==="intelligence"?"active":""} onClick={()=>setActiveTab("intelligence")}><Building2 size={16}/> Intelligence <span className="tab-new-badge">NEW</span></button><button className={activeTab==="briefing"?"active":""} onClick={()=>setActiveTab("briefing")}><Sparkles size={16}/> ForgeAI Briefing</button><button className={activeTab==="compliance"?"active":""} onClick={()=>setActiveTab("compliance")}><ListChecks size={16}/> Compliance {total?`${completed}/${total}`:""}</button><button className={activeTab==="notes"?"active":""} onClick={()=>setActiveTab("notes")}><NotebookPen size={16}/> Capture notes</button><button className={activeTab==="timeline"?"active":""} onClick={()=>setActiveTab("timeline")}><History size={16}/> Timeline</button></nav>
 {workspaceMessage&&<p className="inline-message">{workspaceMessage}</p>}
 {activeTab==="command_center"&&<CaptureCommandCenter noticeId={noticeId}/>}
 {activeTab==="proposal"&&<ProposalWorkspace noticeId={noticeId}/>} 
 {activeTab==="proposal_execution"&&<ProposalExecution noticeId={noticeId}/>} 
 {activeTab==="submission_control"&&<SubmissionControl noticeId={noticeId}/>} 
 {activeTab==="capture"&&<CaptureAssessment noticeId={noticeId}/>}
 {activeTab==="overview"&&<><div className="split-intelligence"><section className="data-panel opportunity-description"><div className="panel-title-row"><div><span className="eyebrow">REQUIREMENT</span><h2>Description</h2></div></div><div className="rich-description">{data.description||"SAM.gov did not return a public description through the API."}</div></section><section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">FILES</span><h2>Government documents</h2></div><small>{data.documents.length} files</small></div><div className="document-list">{data.documents.length?data.documents.map((document,index)=><button key={`${document.url}-${index}`} onClick={()=>setViewer(document)}><FileText/><span><strong>{document.name}</strong><small>{previewable(document)?"Open inside ForgeGov":"View file options"}</small></span><ExternalLink size={16}/></button>):<div className="table-state"><FileText/><strong>No public attachments returned</strong></div>}</div></section></div>
 <section className="data-panel context-ai"><div className="panel-title-row"><div><span className="eyebrow">CONTEXTUAL AI</span><h2>Analyze this opportunity</h2></div><Sparkles/></div><div className="ai-preset-row"><button onClick={()=>void ask(undefined,"Create a concise executive summary with scope, buyer, deadlines, set-aside, and major unknowns.")}>Executive summary</button><button onClick={()=>void ask(undefined,"Extract every explicit requirement and organize them into a compliance checklist. Cite the source section or document name when known.")}>Extract requirements</button><button onClick={()=>void ask(undefined,"Identify capture, technical, schedule, compliance, staffing, and pricing risks. Separate confirmed risks from assumptions.")}>Find risks</button><button onClick={()=>void ask(undefined,"Prepare a bid/no-bid brief with strengths, gaps, questions, and a recommendation based only on available information.")}>Bid/no-bid brief</button></div><form onSubmit={ask}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about requirements, risks, evaluation criteria, or a capture plan…"/><button className="primary-button" disabled={asking||!question.trim()}>{asking?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>} {asking?"Analyzing…":"Ask AI"}</button></form>{answer&&<div className="context-ai-answer"><div className="ai-answer-header"><Sparkles size={18}/><div><strong>ForgeGov findings</strong><small>Verified facts, risks, and next actions</small></div></div><StructuredOpportunityAnswer content={answer}/>{aiSources.length?<details className="ai-source-list contextual-source-list compact-source-disclosure"><summary>Sources ({aiSources.length})</summary><div className="compact-source-items">{aiSources.slice(0,12).map(source=>source.url?<a key={`${source.label}-${source.url}`} href={source.url} target="_blank" rel="noreferrer"><b>{source.label}</b>{source.title}<ExternalLink size={12}/></a>:<div key={`${source.label}-${source.title}`}><b>{source.label}</b>{source.title}</div>)}</div></details>:null}</div>}</section></>}
 {activeTab==="intelligence"&&<section className="opportunity-intelligence-workspace">
  <div className="intelligence-hero-row"><div><span className="eyebrow">MARKET INTELLIGENCE</span><h2>Evidence-backed competitive picture</h2><p>Official award history, ForgeGov inferences, and partner recommendations are separated so you can see what is known versus estimated.</p></div><button className="secondary-button" onClick={()=>void loadIntelligence()}>Refresh research</button></div>
  {intelligenceMessage&&<div className="system-banner warning">{intelligenceMessage}</div>}
  {!intelligence?<div className="table-state"><Building2/><strong>Intelligence is still loading or unavailable.</strong><p>Run USAspending ingestion and retry research to strengthen incumbent and competitor evidence.</p></div>:<>
   <div className="intelligence-summary-grid">
    <article className="intelligence-card official"><span>Likely incumbent</span><strong>{String(intelligence.data.incumbent?.name??"No reliable evidence")}</strong><p>{String(intelligence.data.incumbent?.match_reason??intelligence.data.incumbent?.reason??"No confirmed predecessor match is available yet.")}</p><small>Classification: official historical evidence · {String(intelligence.data.incumbent?.status??"not found")}</small></article>
    <article className="intelligence-card"><span>Past winners</span><strong>{intelligence.data.past_winners.length}</strong><p>{intelligence.data.past_winners.slice(0,3).map(row=>String(row.name??"Unknown")).join(" · ")||"No matching award history yet"}</p><small>USAspending / stored public awards</small></article>
    <article className="intelligence-card derived"><span>Likely competitors</span><strong>{intelligence.data.likely_competitors.length}</strong><p>Historical overlap only — not an official bidder list.</p><small>ForgeGov-derived intelligence</small></article>
    <article className="intelligence-card platform"><span>Teaming matches</span><strong>{intelligence.data.teaming_recommendations.length}</strong><p>Public ForgeGov companies matched by NAICS, PSC, certifications, and partner availability.</p><small>ForgeGov Network</small></article>
   </div>
   <div className="intelligence-detail-grid">
    <section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">COMPETITION</span><h3>Likely competitors</h3></div></div><div className="intelligence-list">{intelligence.data.likely_competitors.length?intelligence.data.likely_competitors.map((row,index)=><article key={`${String(row.name)}-${index}`}><Target/><div><strong>{String(row.name??"Unknown")}</strong><p>{String(row.reason??"")}</p><small>{Number(row.historical_awards??0)} matching awards · confidence {Number(row.confidence??0)}%</small></div></article>):<div className="table-state compact-state"><Target/><strong>No competitor signal yet</strong></div>}</div></section>
    <section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">TEAMING</span><h3>Recommended partners</h3></div></div><div className="intelligence-list">{intelligence.data.teaming_recommendations.length?intelligence.data.teaming_recommendations.map((row,index)=><article key={`${String(row.name)}-${index}`}><Building2/><div><Link className="entity-link" href={String(row.href??"/network")}><strong>{String(row.name??"Unknown")}</strong></Link><p>{Array.isArray(row.reasons)?row.reasons.map(String).join(" · "):"ForgeGov Network match"}</p><small>Fit score {Number(row.score??0)}%</small></div></article>):<div className="table-state compact-state"><Building2/><strong>No network match yet</strong><p>Complete company profiles and capabilities to improve teaming recommendations.</p></div>}</div></section>
   </div>
   <section className="data-panel evidence-panel"><div className="panel-title-row"><div><span className="eyebrow">EVIDENCE</span><h3>Why ForgeGov is showing this</h3></div><small>Generated {new Date(intelligence.generated_at).toLocaleString()}</small></div><div className="evidence-grid">{intelligence.evidence.map((row,index)=><article key={`${row.source}-${index}`}><span className={`evidence-kind ${row.source_kind}`}>{row.source_kind.replaceAll("_"," ")}</span><strong>{row.source}</strong><p>{row.title}</p><small>{row.confidence} confidence · observed {new Date(row.observed_at).toLocaleDateString()}</small>{row.detail&&<em>{row.detail}</em>}{row.url&&<a href={row.url} target="_blank" rel="noreferrer">Open source <ExternalLink size={12}/></a>}</article>)}</div></section>
  </>}
 </section>}
 {activeTab==="briefing"&&<OpportunityBriefing noticeId={noticeId} sourceDocuments={data.documents} opportunity={data.opportunity}/>}
 {activeTab==="compliance"&&<section className="data-panel workspace-section-card"><div className="workspace-section-header"><div><span className="workspace-step">02</span><div><span className="eyebrow">RESPONSE READINESS</span><h2>Compliance checklist</h2><p>Track every requirement, source, and completion status in one guided view.</p></div></div><div className="workspace-progress"><strong>{completed}/{total}</strong><span>complete</span><div><i style={{width:`${total?Math.round(completed/total*100):0}%`}}/></div></div></div>{!workspace?<div className="table-state"><TriangleAlert/><strong>Add this opportunity to activate the workspace.</strong><p>Use Add to pipeline, then reload this page.</p></div>:<><div className="workspace-toolbar">{!total?<button className="secondary-button" onClick={initializeChecklist}>Build starter checklist</button>:<span>{total-completed} requirements remaining</span>}<button className="primary-button" disabled={saving} onClick={()=>void saveWorkspace()}><Save size={16}/>{saving?"Saving…":"Save checklist"}</button></div><div className="compliance-list modern-compliance-list">{workspace.compliance_items.map((item,index)=><article className={item.complete?"complete":""} key={item.id||index}><button className="check-toggle" onClick={()=>{const items=workspace.compliance_items.map((row,i)=>i===index?{...row,complete:!row.complete}:row);setWorkspace({...workspace,compliance_items:items})}}>{item.complete?<CheckCircle2/>:<Circle/>}</button><div><strong>{item.label}</strong><small>{item.source||"Workspace item"}</small></div><button className="icon-button danger-button" onClick={()=>setWorkspace({...workspace,compliance_items:workspace.compliance_items.filter((_,i)=>i!==index)})}><X size={16}/></button></article>)}<button className="add-workspace-item" onClick={()=>{const label=window.prompt("Checklist item");if(label)setWorkspace({...workspace,compliance_items:[...workspace.compliance_items,{id:crypto.randomUUID(),label,complete:false}]})}}>+ Add checklist item</button></div></>}</section>}
 {activeTab==="notes"&&<section className="workspace-capture-shell">{workspace?<><div className="capture-command-bar"><div><span className="workspace-step">03</span><div><span className="eyebrow">CAPTURE STRATEGY</span><h2>Build the win plan</h2><p>Keep the decision, strategy, working assumptions, and risks organized.</p></div></div><label className="decision-control"><span>Bid decision</span><select value={workspace.decision} onChange={e=>setWorkspace({...workspace,decision:e.target.value})}><option value="undecided">Undecided</option><option value="bid">Bid</option><option value="no_bid">No-bid</option><option value="hold">Hold</option></select></label></div><div className="capture-card-grid"><label className="capture-editor primary-editor"><span><b>Capture summary</b><small>Customer need, win strategy, differentiators, and pursuit posture</small></span><textarea value={workspace.capture_summary} onChange={e=>setWorkspace({...workspace,capture_summary:e.target.value})} placeholder="Describe why the customer will choose your team and how you will win…"/></label><label className="capture-editor"><span><b>Working notes</b><small>Questions, assumptions, partner needs, and pricing thoughts</small></span><textarea value={workspace.notes} onChange={e=>setWorkspace({...workspace,notes:e.target.value})} placeholder="Record open questions and capture intelligence…"/></label><label className="capture-editor risk-editor"><span><b>Risk register</b><small>Enter one technical, schedule, compliance, or pricing risk per line</small></span><textarea value={workspace.risks.join("\n")} onChange={e=>setWorkspace({...workspace,risks:e.target.value.split("\n").map(v=>v.trim()).filter(Boolean)})} placeholder={"Missing clearance\nAggressive response schedule"}/></label></div><div className="workspace-save-bar"><span>Last saved {new Date(workspace.updated_at).toLocaleString()}</span><button className="primary-button" disabled={saving} onClick={()=>void saveWorkspace()}><Save size={16}/>{saving?"Saving…":"Save capture workspace"}</button></div></>:<div className="table-state"><NotebookPen/><strong>Workspace is not active yet.</strong><p>Add this opportunity to the pipeline to persist capture notes.</p></div>}</section>}
 {activeTab==="timeline"&&<section className="data-panel workspace-section-card"><div className="workspace-section-header"><div><span className="workspace-step">04</span><div><span className="eyebrow">PURSUIT HISTORY</span><h2>Opportunity timeline</h2><p>Key acquisition dates and ForgeGov workspace activity.</p></div></div></div><div className="timeline-list modern-timeline">{timeline.map((row,index)=><article key={`${row.label}-${index}`}><span><i/></span><div><small>{index===0?"START":index===timeline.length-1?"MILESTONE":"UPDATE"}</small><strong>{row.label}</strong><p>{row.date}</p></div></article>)}{workspace?<article><span><i/></span><div><small>FORGEGOV</small><strong>Workspace last updated</strong><p>{new Date(workspace.updated_at).toLocaleString()}</p></div></article>:null}</div></section>}
 <section className="data-panel incumbent-panel"><div className="panel-title-row"><div><span className="eyebrow">MARKET EVIDENCE</span><h2>Incumbent signals</h2></div><small>{data.incumbent_signals?.length??0} candidates</small></div><p className="panel-note">{data.incumbent_signal_note}</p><div className="intelligence-list">{data.incumbent_signals?.length?data.incumbent_signals.map((signal,index)=><article key={`${signal.recipient_name}-${index}`}><Building2/><div><span>Potential incumbent / competitor signal</span><Link className="entity-link" href={`/participants/vendors/profile?name=${encodeURIComponent(signal.recipient_name)}`}><h3>{signal.recipient_name}</h3></Link><p>{signal.award_count.toLocaleString()} matching stored awards · {new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(signal.obligated??0))} obligated</p><small>{signal.recipient_uei?`UEI ${signal.recipient_uei}`:"UEI unavailable"}{signal.latest_end?` · Latest end ${signal.latest_end}`:""}</small></div></article>):<div className="table-state"><Building2/><strong>Load USAspending award data to generate incumbent signals</strong></div>}</div></section></>}
 {viewer&&<div className="document-viewer-backdrop" role="dialog" aria-modal="true"><div className="document-viewer"><header><strong>{viewer.name}</strong><div><a className="secondary-button" href={viewer.url} target="_blank" rel="noreferrer">Open original <ExternalLink size={15}/></a><button className="icon-button" onClick={()=>setViewer(null)}><X/></button></div></header>{previewable(viewer)?<iframe title={viewer.name} src={viewer.url}/>:<div className="document-viewer-empty"><div><FileText size={42}/><h2>Browser preview is unavailable for this file type.</h2><p>The original filename is preserved. Open the source only when required.</p><a className="primary-button" href={viewer.url} target="_blank" rel="noreferrer">Open original file</a></div></div>}</div></div>}
 </>;
}
