from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .auth_views import (
    audit_logs,
    csrf_token,
    invitation_action,
    invitation_preview,
    invitations,
    pending_invitation_response,
    pending_invitations,
    login,
    logout,
    me,
    refresh,
    register,
    team_member_detail,
    team_members,
    workspaces,
)
from .views import (
    AgencyViewSet,
    AwardViewSet,
    CategoryViewSet,
    ContactGroupViewSet,
    ContactViewSet,
    DataSyncRunViewSet,
    FileRecordViewSet,
    IntelligenceAlertViewSet,
    OpportunityViewSet,
    OrganizationViewSet,
    ParticipantViewSet,
    PipelineItemViewSet,
    PursuitViewSet,
    SavedSearchViewSet,
    TaskViewSet,
    TeamingRequestViewSet,
    VendorViewSet,
    ProjectRoomViewSet,
    AIConversationViewSet,
    CollaborationNotificationViewSet,
    dashboard_summary,
    command_center,
    health,
    integration_status,
    intelligence_connectors,
    opportunity_intelligence_view,
    live_sam_search,
    sam_opportunity_detail,
    live_sam_contract_awards,
    live_sam_subaward_search,
    live_sba_subnet_search,
    sam_opportunity_documents,
    live_grants_search,
    live_grants_detail,
    live_usaspending_awards,
    live_usaspending_contract_vehicles,
    federal_forecast_sources,
    global_search,
    state_local_source_directory,
    agency_intelligence,
    vendor_intelligence,
    category_market_intelligence,
    partner_discovery,
    run_saved_search_alerts,
    add_opportunity_to_pipeline,
    ai_chat,
    pipeline_to_pursuit,
    create_saved_search,
    create_workspace_task,
    opportunity_workspace,
    teaming_activity_collection,
    teaming_activity_detail,
    project_room_partner,
    opportunity_documents,
    opportunity_briefing,
    opportunity_document_question,
    opportunity_document_intelligence,
    opportunity_capture_assessment,
    opportunity_win_strategy,
    opportunity_capture_command_center,
    opportunity_proposal_workspace,
    opportunity_proposal_execution,
    proposal_requirement_detail,
    proposal_review_detail,
    proposal_finding_detail,
    opportunity_submission_control,
    opportunity_submission_export,
    project_room_tasks,
    project_room_access_management,
    project_room_task_detail,
    project_room_comments,
    project_room_notes,
    project_room_files,
    project_room_activity,
    network_directory,
    network_profile,
    network_connections,
    network_connection_response, network_connection_manage, naics_catalog,
    project_room_invitations,
    project_room_invitation_manage,
    project_room_invitation_response,
    pipeline_project_room,
    project_room_lifecycle,
    organization_join_requests,
    organization_join_request_response,
    award_ingestion,
    connector_registry_view,
    award_intelligence_view,
)

router = DefaultRouter()
router.register("organizations", OrganizationViewSet, basename="organization")
router.register("opportunities", OpportunityViewSet, basename="opportunity")
router.register("pipeline", PipelineItemViewSet, basename="pipeline-item")
router.register("pursuits", PursuitViewSet, basename="pursuit")
router.register("tasks", TaskViewSet, basename="task")
router.register("saved-searches", SavedSearchViewSet, basename="saved-search")
router.register("sync-runs", DataSyncRunViewSet, basename="sync-run")
router.register("agencies", AgencyViewSet, basename="agency")
router.register("vendors", VendorViewSet, basename="vendor")
router.register("awards", AwardViewSet, basename="award")
router.register("contacts", ContactViewSet, basename="contact")
router.register("contact-groups", ContactGroupViewSet, basename="contact-group")
router.register("teaming-requests", TeamingRequestViewSet, basename="teaming-request")
router.register("files", FileRecordViewSet, basename="file")
router.register("participants", ParticipantViewSet, basename="participant")
router.register("categories", CategoryViewSet, basename="category")
router.register("alerts", IntelligenceAlertViewSet, basename="intelligence-alert")
router.register("project-rooms", ProjectRoomViewSet, basename="project-room")
router.register("ai/conversations", AIConversationViewSet, basename="ai-conversation")
router.register("collaboration/notifications", CollaborationNotificationViewSet, basename="collaboration-notification")

urlpatterns = [
    path("auth/csrf/", csrf_token),
    path("auth/register/", register),
    path("auth/login/", login),
    path("auth/refresh/", refresh),
    path("auth/logout/", logout),
    path("auth/me/", me),
    path("auth/workspaces/", workspaces),
    path("team/members/", team_members),
    path("team/members/<int:membership_id>/", team_member_detail),
    path("team/invitations/", invitations),
    path("team/invitations/<int:invitation_id>/action/", invitation_action),
    path("auth/invitations/preview/", invitation_preview),
    path("auth/invitations/pending/", pending_invitations),
    path("auth/invitations/<int:invitation_id>/respond/", pending_invitation_response),
    path("audit-logs/", audit_logs),
    path("health/", health),
    path("dashboard/summary/", dashboard_summary),
    path("dashboard/command-center/", command_center),
    path("integrations/status/", integration_status),
    path("intelligence/connectors/", intelligence_connectors),
    path("intelligence/connector-registry/", connector_registry_view),
    path("intelligence/awards/ingestion/", award_ingestion),
    path("intelligence/awards/summary/", award_intelligence_view),
    path("intelligence/opportunities/<str:source_id>/", opportunity_intelligence_view),
    path("ai/chat/", ai_chat),
    path("live/sam/opportunities/", live_sam_search),
    path("live/sam/opportunities/<str:notice_id>/", sam_opportunity_detail),
    path("live/sam/contract-awards/", live_sam_contract_awards),
    path("live/sam/subawards/", live_sam_subaward_search),
    path("live/sba/subnet/", live_sba_subnet_search),
    path("live/sam/opportunities/<str:notice_id>/documents/", sam_opportunity_documents),
    path("live/grants/opportunities/", live_grants_search),
    path("live/grants/opportunities/<str:opportunity_id>/", live_grants_detail),
    path("live/usaspending/awards/", live_usaspending_awards),
    path("live/usaspending/vehicles/", live_usaspending_contract_vehicles),
    path("intelligence/search/", global_search),
    path("intelligence/forecasts/sources/", federal_forecast_sources),
    path("intelligence/state-local/sources/", state_local_source_directory),
    path("intelligence/agencies/", agency_intelligence),
    path("intelligence/vendors/", vendor_intelligence),
    path("intelligence/categories/", category_market_intelligence),
    path("intelligence/partners/", partner_discovery),
    path("workflow/opportunity-to-pipeline/", add_opportunity_to_pipeline),
    path("workflow/pipeline/<int:pipeline_id>/create-pursuit/", pipeline_to_pursuit),
    path("workflow/pipeline/<int:pipeline_id>/project-room/", pipeline_project_room),
    path("project-rooms/<int:room_id>/access/", project_room_access_management),
    path("project-rooms/<int:room_id>/tasks/", project_room_tasks),
    path("project-rooms/<int:room_id>/tasks/<int:task_id>/", project_room_task_detail),
    path("project-rooms/<int:room_id>/comments/", project_room_comments),
    path("project-rooms/<int:room_id>/notes/", project_room_notes),
    path("project-rooms/<int:room_id>/files/", project_room_files),
    path("project-rooms/<int:room_id>/activity/", project_room_activity),
    path("project-rooms/<int:room_id>/lifecycle/", project_room_lifecycle),
    path("workflow/saved-searches/", create_saved_search),
    path("workflow/saved-searches/evaluate/", run_saved_search_alerts),
    path("workflow/tasks/", create_workspace_task),
    path("workflow/opportunity-workspaces/<str:source_id>/", opportunity_workspace),
    path("workflow/teaming/<int:teaming_id>/activities/", teaming_activity_collection),
    path("workflow/teaming-activities/<int:activity_id>/", teaming_activity_detail),
    path("workflow/project-rooms/<int:room_id>/partners/", project_room_partner),
    path("network/directory/", network_directory),
    path("network/profile/", network_profile),
    path("network/connections/", network_connections),
    path("network/connections/<int:connection_id>/respond/", network_connection_response),
    path("network/connections/<int:connection_id>/manage/", network_connection_manage),
    path("reference/naics/", naics_catalog),
    path("network/project-room-invitations/", project_room_invitations),
    path("network/project-room-invitations/<int:invitation_id>/manage/", project_room_invitation_manage),
    path("network/project-room-invitations/<int:invitation_id>/respond/", project_room_invitation_response),
    path("company/join-requests/", organization_join_requests),
    path("company/join-requests/<int:request_id>/respond/", organization_join_request_response),
    path("ai/opportunities/<str:source_id>/documents/", opportunity_documents),
    path("ai/opportunities/<str:source_id>/briefing/", opportunity_briefing),
    path("ai/opportunities/<str:source_id>/ask/", opportunity_document_question),
    path("ai/opportunities/<str:source_id>/document-intelligence/", opportunity_document_intelligence),
    path("ai/opportunities/<str:source_id>/capture-assessment/", opportunity_capture_assessment),
    path("ai/opportunities/<str:source_id>/win-strategy/", opportunity_win_strategy),
    path("ai/opportunities/<str:source_id>/command-center/", opportunity_capture_command_center),
    path("ai/opportunities/<str:source_id>/proposal-workspace/", opportunity_proposal_workspace),
    path("ai/opportunities/<str:source_id>/proposal-execution/", opportunity_proposal_execution),
    path("ai/opportunities/<str:source_id>/proposal-requirements/<int:requirement_id>/", proposal_requirement_detail),
    path("ai/opportunities/<str:source_id>/proposal-reviews/<int:review_id>/", proposal_review_detail),
    path("ai/opportunities/<str:source_id>/proposal-findings/<int:finding_id>/", proposal_finding_detail),
    path("ai/opportunities/<str:source_id>/submission-control/", opportunity_submission_control),
    path("ai/opportunities/<str:source_id>/submission-exports/<str:export_format>/", opportunity_submission_export),
    path("", include(router.urls)),
]
