from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .auth_views import (
    audit_logs,
    csrf_token,
    registration_config,
    resend_verification,
    verify_email,
    password_reset_request,
    password_reset_confirm,
    security_overview,
    step_up_authentication,
    totp_setup,
    totp_confirm,
    totp_disable,
    recovery_codes_regenerate,
    passkey_register_options,
    passkey_register_verify,
    passkey_delete,
    mfa_verify,
    mfa_enrollment_totp_setup,
    mfa_enrollment_totp_confirm,
    mfa_passkey_options,
    mfa_passkey_verify,
    session_revoke,
    sessions_revoke_others,
    organization_security_policy,
    invitation_action,
    invitation_preview,
    invitations,
    pending_invitation_response,
    pending_invitations,
    login,
    logout,
    me,
    refresh,
    register,
    team_member_detail,
    team_members,
    workspaces,
)
from .views import (
    AgencyViewSet,
    AwardViewSet,
    CategoryViewSet,
    ContactGroupViewSet,
    ContactViewSet,
    DataSyncRunViewSet,
    FileRecordViewSet,
    IntelligenceAlertViewSet,
    OpportunityViewSet,
    OrganizationViewSet,
    ParticipantViewSet,
    PipelineItemViewSet,
    PursuitViewSet,
    SavedSearchViewSet,
    TaskViewSet,
    TeamingRequestViewSet,
    VendorViewSet,
    ProjectRoomViewSet,
    AIConversationViewSet,
    CollaborationNotificationViewSet,
    dashboard_summary,
    portfolio_intelligence_view,
    command_center,
    health,
    ready,
    governance_role_matrix,
    integration_status,
    intelligence_connectors,
    opportunity_intelligence_view,
    live_sam_search,
    sam_opportunity_detail,
    opportunity_command_summary,
    live_sam_contract_awards,
    live_sam_subaward_search,
    live_sba_subnet_search,
    sam_opportunity_documents,
    live_grants_search,
    live_grants_detail,
    live_usaspending_awards,
    live_usaspending_contract_vehicles,
    federal_forecast_sources,
    global_search,
    state_local_source_directory,
    agency_intelligence,
    vendor_intelligence,
    category_market_intelligence,
    partner_discovery,
    run_saved_search_alerts,
    notification_preferences,
    notification_delivery_history,
    add_opportunity_to_pipeline,
    ai_chat,
    pipeline_to_pursuit,
    create_saved_search,
    create_workspace_task,
    opportunity_workspace,
    teaming_activity_collection,
    teaming_activity_detail,
    project_room_partner,
    opportunity_documents,
    opportunity_briefing,
    opportunity_document_question,
    opportunity_document_intelligence,
    opportunity_capture_assessment,
    opportunity_win_strategy,
    opportunity_capture_command_center,
    opportunity_pursuit_decision,
    opportunity_pricing_workspace,
    pricing_profile,
    opportunity_price_to_win,
    opportunity_prime_sub_cashflow,
    opportunity_proposal_workspace,
    opportunity_proposal_execution,
    proposal_requirement_detail,
    proposal_review_detail,
    proposal_finding_detail,
    opportunity_submission_control,
    opportunity_submission_export,
    project_room_tasks,
    beta_feedback,
    project_room_access_management,
    project_room_task_detail,
    project_room_comments,
    project_room_notes,
    project_room_files,
    project_room_activity,
    project_room_export,
    network_directory,
    network_profile,
    network_connections,
    network_connection_response, network_connection_manage, naics_catalog,
    project_room_invitations,
    project_room_invitation_manage,
    project_room_invitation_response,
    pipeline_project_room,
    project_room_lifecycle,
    organization_join_requests,
    organization_join_request_response,
    award_ingestion,
    connector_registry_view,
    award_intelligence_view,
)

router = DefaultRouter()
router.register("organizations", OrganizationViewSet, basename="organization")
router.register("opportunities", OpportunityViewSet, basename="opportunity")
router.register("pipeline", PipelineItemViewSet, basename="pipeline-item")
router.register("pursuits", PursuitViewSet, basename="pursuit")
router.register("tasks", TaskViewSet, basename="task")
router.register("saved-searches", SavedSearchViewSet, basename="saved-search")
router.register("sync-runs", DataSyncRunViewSet, basename="sync-run")
router.register("agencies", AgencyViewSet, basename="agency")
router.register("vendors", VendorViewSet, basename="vendor")
router.register("awards", AwardViewSet, basename="award")
router.register("contacts", ContactViewSet, basename="contact")
router.register("contact-groups", ContactGroupViewSet, basename="contact-group")
router.register("teaming-requests", TeamingRequestViewSet, basename="teaming-request")
router.register("files", FileRecordViewSet, basename="file")
router.register("participants", ParticipantViewSet, basename="participant")
router.register("categories", CategoryViewSet, basename="category")
router.register("alerts", IntelligenceAlertViewSet, basename="intelligence-alert")
router.register("project-rooms", ProjectRoomViewSet, basename="project-room")
router.register("ai/conversations", AIConversationViewSet, basename="ai-conversation")
router.register("collaboration/notifications", CollaborationNotificationViewSet, basename="collaboration-notification")

urlpatterns = [
    path("platform-admin/", include("platform_admin.urls")),
    path("beta-feedback/", beta_feedback),
    path("notifications/preferences/", notification_preferences),
    path("notifications/deliveries/", notification_delivery_history),
    path("auth/csrf/", csrf_token),
    path("auth/registration-config/", registration_config),
    path("auth/register/", register),
    path("auth/verify-email/", verify_email),
    path("auth/resend-verification/", resend_verification),
    path("auth/password-reset/request/", password_reset_request),
    path("auth/password-reset/confirm/", password_reset_confirm),
    path("auth/login/", login),
    path("auth/mfa/verify/", mfa_verify),
    path("auth/mfa/enroll/totp/setup/", mfa_enrollment_totp_setup),
    path("auth/mfa/enroll/totp/confirm/", mfa_enrollment_totp_confirm),
    path("auth/mfa/passkey/options/", mfa_passkey_options),
    path("auth/mfa/passkey/verify/", mfa_passkey_verify),
    path("auth/refresh/", refresh),
    path("auth/logout/", logout),
    path("auth/me/", me),
    path("auth/security/", security_overview),
    path("auth/security/step-up/", step_up_authentication),
    path("auth/security/totp/setup/", totp_setup),
    path("auth/security/totp/confirm/", totp_confirm),
    path("auth/security/totp/disable/", totp_disable),
    path("auth/security/recovery-codes/regenerate/", recovery_codes_regenerate),
    path("auth/security/passkeys/register/options/", passkey_register_options),
    path("auth/security/passkeys/register/verify/", passkey_register_verify),
    path("auth/security/passkeys/<int:passkey_id>/", passkey_delete),
    path("auth/security/sessions/<uuid:session_id>/revoke/", session_revoke),
    path("auth/security/sessions/revoke-others/", sessions_revoke_others),
    path("auth/security/organization-policy/", organization_security_policy),
    path("auth/workspaces/", workspaces),
    path("team/members/", team_members),
    path("team/members/<int:membership_id>/", team_member_detail),
    path("team/invitations/", invitations),
    path("team/invitations/<int:invitation_id>/action/", invitation_action),
    path("auth/invitations/preview/", invitation_preview),
    path("auth/invitations/pending/", pending_invitations),
    path("auth/invitations/<int:invitation_id>/respond/", pending_invitation_response),
    path("audit-logs/", audit_logs),
    path("health/", health),
    path("ready/", ready),
    path("governance/role-matrix/", governance_role_matrix),
    path("dashboard/summary/", dashboard_summary),
    path("reports/portfolio-intelligence/", portfolio_intelligence_view),
    path("dashboard/command-center/", command_center),
    path("integrations/status/", integration_status),
    path("intelligence/connectors/", intelligence_connectors),
    path("intelligence/connector-registry/", connector_registry_view),
    path("intelligence/awards/ingestion/", award_ingestion),
    path("intelligence/awards/summary/", award_intelligence_view),
    path("intelligence/opportunities/<str:source_id>/", opportunity_intelligence_view),
    path("ai/chat/", ai_chat),
    path("live/sam/opportunities/", live_sam_search),
    path("live/sam/opportunities/<str:notice_id>/", sam_opportunity_detail),
    path("workflow/opportunities/<str:notice_id>/command-summary/", opportunity_command_summary),
    path("live/sam/contract-awards/", live_sam_contract_awards),
    path("live/sam/subawards/", live_sam_subaward_search),
    path("live/sba/subnet/", live_sba_subnet_search),
    path("live/sam/opportunities/<str:notice_id>/documents/", sam_opportunity_documents),
    path("live/grants/opportunities/", live_grants_search),
    path("live/grants/opportunities/<str:opportunity_id>/", live_grants_detail),
    path("live/usaspending/awards/", live_usaspending_awards),
    path("live/usaspending/vehicles/", live_usaspending_contract_vehicles),
    path("intelligence/search/", global_search),
    path("intelligence/forecasts/sources/", federal_forecast_sources),
    path("intelligence/state-local/sources/", state_local_source_directory),
    path("intelligence/agencies/", agency_intelligence),
    path("intelligence/vendors/", vendor_intelligence),
    path("intelligence/categories/", category_market_intelligence),
    path("intelligence/partners/", partner_discovery),
    path("workflow/opportunity-to-pipeline/", add_opportunity_to_pipeline),
    path("workflow/pipeline/<int:pipeline_id>/create-pursuit/", pipeline_to_pursuit),
    path("workflow/pipeline/<int:pipeline_id>/project-room/", pipeline_project_room),
    path("project-rooms/<int:room_id>/access/", project_room_access_management),
    path("project-rooms/<int:room_id>/tasks/", project_room_tasks),
    path("project-rooms/<int:room_id>/tasks/<int:task_id>/", project_room_task_detail),
    path("project-rooms/<int:room_id>/comments/", project_room_comments),
    path("project-rooms/<int:room_id>/notes/", project_room_notes),
    path("project-rooms/<int:room_id>/files/", project_room_files),
    path("project-rooms/<int:room_id>/activity/", project_room_activity),
    path("project-rooms/<int:room_id>/export/", project_room_export),
    path("project-rooms/<int:room_id>/lifecycle/", project_room_lifecycle),
    path("workflow/saved-searches/", create_saved_search),
    path("workflow/saved-searches/evaluate/", run_saved_search_alerts),
    path("workflow/tasks/", create_workspace_task),
    path("workflow/opportunity-workspaces/<str:source_id>/", opportunity_workspace),
    path("workflow/teaming/<int:teaming_id>/activities/", teaming_activity_collection),
    path("workflow/teaming-activities/<int:activity_id>/", teaming_activity_detail),
    path("workflow/project-rooms/<int:room_id>/partners/", project_room_partner),
    path("network/directory/", network_directory),
    path("network/profile/", network_profile),
    path("network/connections/", network_connections),
    path("network/connections/<int:connection_id>/respond/", network_connection_response),
    path("network/connections/<int:connection_id>/manage/", network_connection_manage),
    path("reference/naics/", naics_catalog),
    path("network/project-room-invitations/", project_room_invitations),
    path("network/project-room-invitations/<int:invitation_id>/manage/", project_room_invitation_manage),
    path("network/project-room-invitations/<int:invitation_id>/respond/", project_room_invitation_response),
    path("company/join-requests/", organization_join_requests),
    path("company/join-requests/<int:request_id>/respond/", organization_join_request_response),
    path("ai/opportunities/<str:source_id>/documents/", opportunity_documents),
    path("ai/opportunities/<str:source_id>/briefing/", opportunity_briefing),
    path("ai/opportunities/<str:source_id>/ask/", opportunity_document_question),
    path("ai/opportunities/<str:source_id>/document-intelligence/", opportunity_document_intelligence),
    path("ai/opportunities/<str:source_id>/capture-assessment/", opportunity_capture_assessment),
    path("ai/opportunities/<str:source_id>/win-strategy/", opportunity_win_strategy),
    path("ai/opportunities/<str:source_id>/command-center/", opportunity_capture_command_center),
    path("ai/opportunities/<str:source_id>/pursuit-decision/", opportunity_pursuit_decision),
    path("pricing/opportunities/<str:source_id>/", opportunity_pricing_workspace),
    path("pricing/opportunities/<str:source_id>/price-to-win/", opportunity_price_to_win),
    path("pricing/opportunities/<str:source_id>/prime-sub-cashflow/", opportunity_prime_sub_cashflow),
    path("pricing/profile/", pricing_profile),
    path("ai/opportunities/<str:source_id>/proposal-workspace/", opportunity_proposal_workspace),
    path("ai/opportunities/<str:source_id>/proposal-execution/", opportunity_proposal_execution),
    path("ai/opportunities/<str:source_id>/proposal-requirements/<int:requirement_id>/", proposal_requirement_detail),
    path("ai/opportunities/<str:source_id>/proposal-reviews/<int:review_id>/", proposal_review_detail),
    path("ai/opportunities/<str:source_id>/proposal-findings/<int:finding_id>/", proposal_finding_detail),
    path("ai/opportunities/<str:source_id>/submission-control/", opportunity_submission_control),
    path("ai/opportunities/<str:source_id>/submission-exports/<str:export_format>/", opportunity_submission_export),
    path("", include(router.urls)),
]
