"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Check, Handshake, Search, UserPlus, X } from "lucide-react";
import { apiGet, apiPost } from "@/lib/api";
import { CompanyBrandingPanel, CompanyIdentity } from "@/components/company-identity";

type Company={id:number;organization_id:number;organization_name:string;slug:string;uei:string;cage_code:string;tagline:string;description:string;website:string;city:string;state:string;country:string;naics_codes:string[];capabilities:string[];certifications:string[];accepting_partners:boolean;verified:boolean;connection_status:string;connection_id:number|null};
type Connection={id:number;requester:number;requester_name:string;recipient:number;recipient_name:string;status:string;message:string;created_at:string};
type RoomInvite={id:number;project_room:number;project_room_name:string;owner_organization_name:string;invited_organization_name:string;status:string;access_level:string;message:string;created_at:string};
export default function NetworkPage(){
 const params=useSearchParams(); const router=useRouter(); const requestedTab=params.get("tab")||"directory";
 const tab=["directory","invitations","partners"].includes(requestedTab)?requestedTab:"directory";
 function selectNetworkTab(next:string){if(next!=="directory"&&next!=="invitations"&&next!=="partners")return;router.replace(next==="directory"?"/network":"/network?tab="+encodeURIComponent(next),{scroll:false})} const [q,setQ]=useState(""); const [companies,setCompanies]=useState<Company[]>([]); const [connections,setConnections]=useState<Connection[]>([]); const [invites,setInvites]=useState<RoomInvite[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState("");
 async function loadDirectory(){const data=await apiGet<{results:Company[]}>(`/network/directory/?q=${encodeURIComponent(q)}`);setCompanies(data.results)}
 async function loadAll(){try{const [c,i]=await Promise.all([apiGet<Connection[]>("/network/connections/"),apiGet<RoomInvite[]>("/network/project-room-invitations/")]);setConnections(c);setInvites(i);await loadDirectory()}catch(e){setMessage(e instanceof Error?e.message:"Network could not be loaded")}}
 useEffect(()=>{
  let cancelled=false;
  Promise.all([apiGet<Connection[]>("/network/connections/"),apiGet<RoomInvite[]>("/network/project-room-invitations/"),apiGet<{results:Company[]}>("/network/directory/?q=")])
   .then(([c,i,d])=>{if(cancelled)return;setConnections(c);setInvites(i);setCompanies(d.results)})
   .catch((e:unknown)=>{if(!cancelled)setMessage(e instanceof Error?e.message:"Network could not be loaded")});
  return()=>{cancelled=true};
 },[]);
 const pending=connections.filter(c=>c.status==="pending"); const active=connections.filter(c=>c.status==="accepted"); const roomPending=invites.filter(i=>i.status==="pending");
 async function connect(company:Company){setBusy(`c-${company.organization_id}`);try{await apiPost("/network/connections/",{recipient:company.organization_id,message:"We would like to connect and explore government contracting opportunities together."});setMessage(`Connection request sent to ${company.organization_name}.`);await loadAll()}catch(e){setMessage(e instanceof Error?e.message:"Request failed")}finally{setBusy("")}}
 async function manageConnection(id:number,action:"cancel"|"disconnect"|"block"|"unblock"){setBusy(`manage-${id}`);try{await apiPost(`/network/connections/${id}/manage/`,{action});await loadAll()}catch(e){setMessage(e instanceof Error?e.message:"Relationship update failed")}finally{setBusy("")}}
 async function respond(id:number,action:"accept"|"decline",kind:"connection"|"room"){setBusy(`${kind}-${id}`);try{await apiPost(kind==="connection"?`/network/connections/${id}/respond/`:`/network/project-room-invitations/${id}/respond/`,{action});await loadAll()}catch(e){setMessage(e instanceof Error?e.message:"Response failed")}finally{setBusy("")}}
 return <div className="page-stack network-page"><section className="page-hero"><div><span className="eyebrow">FORGEGOV NETWORK</span><h1>Find companies. Build teams. Win together.</h1><p>Search verified company profiles, create trusted connections, and accept secure Project Room invitations without exposing your internal workspace.</p></div></section>
 <div className="network-tabs">{[["directory","Company Directory"],["invitations",`Invitations (${pending.length+roomPending.length})`],["partners",`Active Partners (${active.length})`]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>selectNetworkTab(k)}>{l}</button>)}</div>
 {message&&<div className="network-message">{message}</div>}
 {tab==="directory"&&<><CompanyBrandingPanel/><div className="network-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void loadDirectory()}} placeholder="Search company name, capability, CAGE, UEI, NAICS or certification"/><button onClick={()=>void loadDirectory()}>Search</button></div><div className="network-grid">{companies.map(company=><article className="network-company-card" key={company.organization_id}><div className="network-company-heading"><CompanyIdentity name={company.organization_name} organizationId={company.organization_id}/><div><h3>{company.organization_name}{company.verified&&<small> Verified</small>}</h3><p>{company.tagline||company.description||"Company profile available for teaming discovery."}</p></div></div><div className="company-meta"><span>{[company.city,company.state].filter(Boolean).join(", ")||company.country}</span>{company.cage_code&&<span>CAGE {company.cage_code}</span>}</div><div className="chip-row">{[...company.capabilities,...company.certifications,...company.naics_codes].slice(0,8).map(tag=><span key={tag}>{tag}</span>)}</div><div className="card-actions">{company.connection_status==="accepted"?<button disabled><Check size={16}/> Connected</button>:company.connection_status==="pending"?<button className="secondary" onClick={()=>company.connection_id&&void manageConnection(company.connection_id,"cancel")}>Cancel request</button>:<button disabled={!company.accepting_partners||busy===`c-${company.organization_id}`} onClick={()=>void connect(company)}><UserPlus size={16}/> Connect</button>}{company.website&&<a href={company.website} target="_blank" rel="noreferrer">Website</a>}</div></article>)}</div></>}
 {tab==="invitations"&&<div className="network-list"><h2>Company connection requests</h2>{pending.length===0&&<p>No pending company connections.</p>}{pending.map(row=><article key={row.id}><div><strong><CompanyIdentity name={row.requester_name} organizationId={row.requester} compact/></strong><p>{row.message||"Wants to connect with your company."}</p></div><div><button onClick={()=>void respond(row.id,"accept","connection")}><Check/> Accept</button><button className="secondary" onClick={()=>void respond(row.id,"decline","connection")}><X/> Decline</button></div></article>)}<h2>Project Room invitations</h2>{roomPending.length===0&&<p>No pending Project Room invitations.</p>}{roomPending.map(row=><article key={row.id}><div><strong><CompanyIdentity name={row.owner_organization_name} compact/></strong><p>Invited you to {row.project_room_name}. {row.message}</p></div><div><button onClick={()=>void respond(row.id,"accept","room")}><Handshake/> Join room</button><button className="secondary" onClick={()=>void respond(row.id,"decline","room")}><X/> Decline</button></div></article>)}</div>}
 {tab==="partners"&&<div className="network-list"><h2>Trusted company connections</h2>{active.length===0&&<p>No active partners yet. Search the directory and send a connection request.</p>}{active.map(row=><article key={row.id}><div><strong className="company-relationship"><CompanyIdentity name={row.requester_name} organizationId={row.requester} compact/><span>↔</span><CompanyIdentity name={row.recipient_name} organizationId={row.recipient} compact/></strong><p>Connected company relationship. Invite this company from a Project Room.</p></div><div className="row-actions"><span className="status-pill">Connected</span><button className="secondary danger-button" disabled={busy===`manage-${row.id}`} onClick={()=>void manageConnection(row.id,"disconnect")}>Disconnect</button></div></article>)}</div>}
 </div>
}
