"use client";

import { useRouter } from "next/navigation";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {KeyRound,Laptop,RefreshCw,ShieldCheck,ShieldAlert,Smartphone,Trash2} from "lucide-react";
import {authFetch} from "@/lib/api";
import {registrationOptions,serializeCredential} from "@/lib/webauthn";

type SecurityOverview={
 email:string;account_status:string;organization_status?:string|null;
 mfa:{enabled:boolean;totp_enabled:boolean;passkey_enabled:boolean;methods:string[];recovery_codes_remaining:number;required_by_organization:boolean};
 organization_security:{require_mfa:boolean;require_mfa_for_financial_roles:boolean;require_mfa_for_exports:boolean;require_mfa_for_project_room_admin:boolean;session_max_days:number;can_manage:boolean};
 sessions:Array<{session_id:string;device_label:string;ip_address?:string|null;created_at:string;last_seen_at:string;expires_at:string;current:boolean;step_up_at?:string|null}>;
 passkeys:Array<{id:number;name:string;created_at:string;last_used_at?:string|null;device_type:string;backed_up:boolean}>;
 recent_activity:Array<{id:number;action:string;created_at:string;ip_address?:string|null}>;
};
type TotpSetup={secret:string;provisioning_uri:string;device_id:number};
type TotpConfirm={enabled:boolean;recovery_codes:string[];detail:string};
type PasskeyOptions={challenge_token:string;options:{challenge:string;user:{id:string;name:string;displayName:string};excludeCredentials?:Array<{id:string;type:PublicKeyCredentialType;transports?:AuthenticatorTransport[]}>;[key:string]:unknown}};

export default function SecurityPage(){
 const router=useRouter();
 const[data,setData]=useState<SecurityOverview|null>(null);const[message,setMessage]=useState("");const[busy,setBusy]=useState("");
 const[stepPassword,setStepPassword]=useState("");const[stepCode,setStepCode]=useState("");const[stepMethod,setStepMethod]=useState("totp");const[stepUnlocked,setStepUnlocked]=useState(false);
 const[setupPassword,setSetupPassword]=useState("");const[totpSetup,setTotpSetup]=useState<TotpSetup|null>(null);const[totpCode,setTotpCode]=useState("");const[recoveryCodes,setRecoveryCodes]=useState<string[]>([]);
 const load=useCallback(async()=>{setBusy("load");try{setData(await authFetch<SecurityOverview>("/auth/security/"));setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"Security center could not be loaded.")}finally{setBusy("")}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function stepUp(e:FormEvent){e.preventDefault();setBusy("step");setMessage("");try{await authFetch("/auth/security/step-up/",{method:"POST",body:JSON.stringify({password:stepPassword,method:stepMethod,code:stepCode})});setStepUnlocked(true);setStepPassword("");setStepCode("");setMessage("Sensitive security changes unlocked for 10 minutes.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Reauthentication failed")}finally{setBusy("")}}
 async function beginTotp(e:FormEvent){e.preventDefault();setBusy("totp-start");try{setTotpSetup(await authFetch<TotpSetup>("/auth/security/totp/setup/",{method:"POST",body:JSON.stringify({password:setupPassword})}));setSetupPassword("");setMessage("Add ForgeGov to your authenticator app, then enter the 6-digit code.")}catch(error){setMessage(error instanceof Error?error.message:"Authenticator setup failed")}finally{setBusy("")}}
 async function confirmTotp(e:FormEvent){e.preventDefault();setBusy("totp-confirm");try{const result=await authFetch<TotpConfirm>("/auth/security/totp/confirm/",{method:"POST",body:JSON.stringify({code:totpCode})});setRecoveryCodes(result.recovery_codes);setTotpSetup(null);setTotpCode("");setStepUnlocked(false);setMessage(result.detail);await load()}catch(error){setMessage(error instanceof Error?error.message:"Authenticator confirmation failed")}finally{setBusy("")}}
 async function disableTotp(){setBusy("totp-disable");try{await authFetch("/auth/security/totp/disable/",{method:"POST"});setStepUnlocked(false);setMessage("Authenticator app removed.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Could not remove authenticator")}finally{setBusy("")}}
 async function regenerateCodes(){setBusy("recovery");try{const result=await authFetch<{recovery_codes:string[];detail:string}>("/auth/security/recovery-codes/regenerate/",{method:"POST"});setRecoveryCodes(result.recovery_codes);setStepUnlocked(false);setMessage(result.detail);await load()}catch(error){setMessage(error instanceof Error?error.message:"Could not regenerate recovery codes")}finally{setBusy("")}}
 async function addPasskey(){setBusy("passkey");try{const row=await authFetch<PasskeyOptions>("/auth/security/passkeys/register/options/",{method:"POST"});const credential=await navigator.credentials.create({publicKey:registrationOptions(row.options)});if(!credential)throw new Error("Passkey creation was cancelled.");await authFetch("/auth/security/passkeys/register/verify/",{method:"POST",body:JSON.stringify({challenge_token:row.challenge_token,credential:serializeCredential(credential as PublicKeyCredential),name:"Passkey"})});setStepUnlocked(false);setMessage("Passkey added.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Passkey registration failed")}finally{setBusy("")}}
 async function removePasskey(id:number){setBusy(`passkey-${id}`);try{await authFetch(`/auth/security/passkeys/${id}/`,{method:"DELETE"});setStepUnlocked(false);setMessage("Passkey removed.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Passkey removal failed")}finally{setBusy("")}}
 async function revokeSession(id:string){setBusy(`session-${id}`);try{const result=await authFetch<{current:boolean}>(`/auth/security/sessions/${id}/revoke/`,{method:"POST"});if(result.current){router.replace("/sign-in");return}setMessage("Session revoked.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Could not revoke session")}finally{setBusy("")}}
 async function revokeOthers(){setBusy("sessions");try{await authFetch("/auth/security/sessions/revoke-others/",{method:"POST"});setStepUnlocked(false);setMessage("All other sessions revoked.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Could not revoke sessions")}finally{setBusy("")}}
 async function updatePolicy(patch:Record<string,unknown>){setBusy("policy");try{await authFetch("/auth/security/organization-policy/",{method:"PATCH",body:JSON.stringify(patch)});setStepUnlocked(false);setMessage("Company security policy updated.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Could not update company security policy")}finally{setBusy("")}}
 if(!data)return <main className="page-shell"><section className="data-panel table-state"><RefreshCw className={busy?"spin":""}/><strong>Loading Security Center…</strong><p>{message}</p></section></main>;
 return <main className="page-shell security-center"><header className="feature-hero"><div><span className="eyebrow">IDENTITY SECURITY</span><h1>Security Center</h1><p>Manage multi-factor authentication, passkeys, recovery codes, active sessions, and your company&apos;s security policy.</p></div><div className="security-score"><ShieldCheck/><div><span>Account protection</span><strong>{data.mfa.enabled?"MFA protected":"Password only"}</strong></div></div></header>{message&&<div className="system-banner">{message}</div>}
 <section className="security-grid">
  <article className="data-panel"><div className="panel-heading"><ShieldCheck/><div><h2>Multi-factor authentication</h2><p>Authenticator apps use time-based one-time codes. Recovery codes are single-use emergency access codes.</p></div></div>{data.mfa.totp_enabled?<div className="security-action-card good"><div><strong>Authenticator app enabled</strong><span>{data.mfa.recovery_codes_remaining} recovery codes remaining</span></div><div className="button-row"><button className="secondary-button" disabled={!stepUnlocked||busy==="recovery"} onClick={()=>void regenerateCodes()}>Regenerate recovery codes</button><button className="danger-button" disabled={!stepUnlocked||busy==="totp-disable"} onClick={()=>void disableTotp()}>Remove authenticator</button></div></div>:<form className="security-inline-form" onSubmit={beginTotp}><label><span>Current password</span><input type="password" value={setupPassword} onChange={e=>setSetupPassword(e.target.value)} required/></label><button className="primary-button" disabled={busy==="totp-start"}>Set up authenticator</button></form>}{totpSetup&&<div className="totp-setup"><strong>Authenticator setup</strong><p>Scan/import this provisioning URI in your authenticator app, or enter the secret manually.</p><code>{totpSetup.provisioning_uri}</code><div className="secret-box"><span>Manual secret</span><b>{totpSetup.secret}</b></div><form onSubmit={confirmTotp}><input value={totpCode} onChange={e=>setTotpCode(e.target.value)} placeholder="6-digit code" inputMode="numeric" required/><button className="primary-button">Confirm authenticator</button></form></div>}{recoveryCodes.length>0&&<div className="recovery-code-box"><ShieldAlert/><div><strong>Save these recovery codes now</strong><p>Each code works once. Store them somewhere separate from your password.</p><div className="recovery-code-grid">{recoveryCodes.map(code=><code key={code}>{code}</code>)}</div></div></div>}</article>
  <article className="data-panel"><div className="panel-heading"><KeyRound/><div><h2>Passkeys</h2><p>Passkeys use WebAuthn and can provide phishing-resistant verification through Touch ID, Face ID, Windows Hello, or a security key.</p></div></div><div className="passkey-list">{data.passkeys.map(row=><div key={row.id}><KeyRound/><div><strong>{row.name}</strong><span>Added {new Date(row.created_at).toLocaleDateString()}{row.last_used_at?` · Used ${new Date(row.last_used_at).toLocaleDateString()}`:""}</span></div><button className="icon-button danger-button" disabled={!stepUnlocked||busy===`passkey-${row.id}`} onClick={()=>void removePasskey(row.id)}><Trash2 size={15}/></button></div>)}</div><button className="primary-button" disabled={!stepUnlocked||busy==="passkey"} onClick={()=>void addPasskey()}><KeyRound size={16}/>Add passkey</button><small className="security-hint">Unlock security changes below before adding or removing a passkey.</small></article>
 </section>
 <section className="data-panel"><div className="panel-heading"><ShieldCheck/><div><h2>Unlock sensitive security changes</h2><p>ForgeGov requires recent authentication before changing MFA, passkeys, company security policy, or revoking all other sessions.</p></div></div><form className="step-up-form" onSubmit={stepUp}><label><span>Current password</span><input type="password" value={stepPassword} onChange={e=>setStepPassword(e.target.value)} required/></label>{data.mfa.totp_enabled&&<><label><span>MFA method</span><select value={stepMethod} onChange={e=>setStepMethod(e.target.value)}><option value="totp">Authenticator app</option><option value="recovery_code">Recovery code</option></select></label><label><span>Code</span><input value={stepCode} onChange={e=>setStepCode(e.target.value)} required/></label></>}<button className="secondary-button" disabled={busy==="step"}>{stepUnlocked?"Security changes unlocked":"Verify identity"}</button></form></section>
 <section className="security-grid"><article className="data-panel"><div className="panel-heading"><Laptop/><div><h2>Active sessions</h2><p>Revoke devices you no longer recognize or use.</p></div></div><div className="session-list">{data.sessions.map(row=><div key={row.session_id}><div className="session-icon">{row.device_label.includes("iPhone")||row.device_label.includes("Android")?<Smartphone/>:<Laptop/>}</div><div><strong>{row.device_label}{row.current?" · Current":""}</strong><span>{row.ip_address||"IP unavailable"} · Last active {new Date(row.last_seen_at).toLocaleString()}</span></div><button className="secondary-button" disabled={busy===`session-${row.session_id}`} onClick={()=>void revokeSession(row.session_id)}>Revoke</button></div>)}</div><button className="danger-button" disabled={!stepUnlocked||busy==="sessions"} onClick={()=>void revokeOthers()}>Sign out all other sessions</button></article>
  <article className="data-panel"><div className="panel-heading"><ShieldCheck/><div><h2>Company security policy</h2><p>Company-wide MFA can only be required after every active member has enrolled an MFA method.</p></div></div><div className="identity-security-list"><div><span>Required for company</span><strong>{data.organization_security.require_mfa?"Required":"Not required"}</strong></div><div><span>Session maximum</span><strong>{data.organization_security.session_max_days} days</strong></div></div>{data.organization_security.can_manage?<div className="button-row"><button className="secondary-button" disabled={!stepUnlocked||busy==="policy"} onClick={()=>void updatePolicy({require_mfa:!data.organization_security.require_mfa})}>{data.organization_security.require_mfa?"Stop requiring MFA":"Require MFA for company"}</button><button className="secondary-button" disabled={!stepUnlocked||busy==="policy"} onClick={()=>void updatePolicy({require_mfa_for_financial_roles:!data.organization_security.require_mfa_for_financial_roles})}>{data.organization_security.require_mfa_for_financial_roles?"Stop privileged-role MFA":"Require MFA for Owner/Admin/Pricing"}</button><button className="secondary-button" disabled={!stepUnlocked||busy==="policy"} onClick={()=>void updatePolicy({require_mfa_for_exports:!data.organization_security.require_mfa_for_exports})}>{data.organization_security.require_mfa_for_exports?"Stop export reauthentication":"Require recent auth for exports"}</button><button className="secondary-button" disabled={!stepUnlocked||busy==="policy"} onClick={()=>void updatePolicy({require_mfa_for_project_room_admin:!data.organization_security.require_mfa_for_project_room_admin})}>{data.organization_security.require_mfa_for_project_room_admin?"Stop room-admin reauthentication":"Require recent auth for room access changes"}</button></div>:<small>Only company owners and administrators can change this policy.</small>}</article></section>
 <section className="data-panel"><div className="panel-heading"><ShieldCheck/><div><h2>Recent security activity</h2><p>Security-sensitive activity recorded for your account.</p></div></div><div className="security-activity-list">{data.recent_activity.map(row=><div key={row.id}><strong>{row.action.replaceAll("security.","").replaceAll("_"," ")}</strong><span>{new Date(row.created_at).toLocaleString()} · {row.ip_address||"IP unavailable"}</span></div>)}</div></section>
 </main>
}
