"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {apiGet,apiPatch,apiPost} from "@/lib/api";
type Task={id:number;title:string;description:string;status:string;priority:string;visibility:string;due_date?:string};
type Comment={id:number;body:string;author_name:string;visibility:string;created_at:string};
type Note={id:number;title:string;body:string;visibility:string;author_name:string};
type FileItem={id:number;name:string;url:string;description:string;visibility:string;version:number};
type Activity={id:number;summary:string;actor_name:string;created_at:string};
const columns=["todo","in_progress","review","done"] as const;
export default function ProjectRoomDetail(){const params=useParams<{id:string}>();const id=params.id;const[tasks,setTasks]=useState<Task[]>([]);const[comments,setComments]=useState<Comment[]>([]);const[notes,setNotes]=useState<Note[]>([]);const[files,setFiles]=useState<FileItem[]>([]);const[activity,setActivity]=useState<Activity[]>([]);const[taskTitle,setTaskTitle]=useState("");const[comment,setComment]=useState("");const[noteTitle,setNoteTitle]=useState("");const[noteBody,setNoteBody]=useState("");const[fileName,setFileName]=useState("");const[fileUrl,setFileUrl]=useState("");const[message,setMessage]=useState("");
const load=useCallback(async()=>{try{const[t,c,n,f,a]=await Promise.all([apiGet<Task[]>(`/project-rooms/${id}/tasks/`),apiGet<Comment[]>(`/project-rooms/${id}/comments/`),apiGet<Note[]>(`/project-rooms/${id}/notes/`),apiGet<FileItem[]>(`/project-rooms/${id}/files/`),apiGet<Activity[]>(`/project-rooms/${id}/activity/`)]);setTasks(t);setComments(c);setNotes(n);setFiles(f);setActivity(a)}catch(e){setMessage(e instanceof Error?e.message:"Room could not be loaded")}},[id]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
const counts=useMemo(()=>Object.fromEntries(columns.map(s=>[s,tasks.filter(t=>t.status===s).length])),[tasks]);
async function addTask(e:FormEvent){e.preventDefault();await apiPost(`/project-rooms/${id}/tasks/`,{title:taskTitle,status:"todo",priority:"medium",visibility:"shared"});setTaskTitle("");await load()}
async function move(task:Task,status:string){await apiPatch(`/project-rooms/${id}/tasks/${task.id}/`,{status});await load()}
async function addComment(e:FormEvent){e.preventDefault();await apiPost(`/project-rooms/${id}/comments/`,{body:comment,visibility:"shared",mentions:[]});setComment("");await load()}
async function addNote(e:FormEvent){e.preventDefault();await apiPost(`/project-rooms/${id}/notes/`,{title:noteTitle,body:noteBody,visibility:"internal"});setNoteTitle("");setNoteBody("");await load()}
async function addFile(e:FormEvent){e.preventDefault();await apiPost(`/project-rooms/${id}/files/`,{name:fileName,url:fileUrl,visibility:"shared",version:1});setFileName("");setFileUrl("");await load()}
return <><header className="feature-hero"><div><span className="eyebrow">PROJECT ROOM</span><h1>Collaboration workspace</h1><p>Tasks, shared discussions, internal capture notes, controlled files, and a complete activity trail.</p></div></header>{message&&<p className="inline-message">{message}</p>}<section className="data-panel"><h2>Task board</h2><form className="advanced-filter-grid" onSubmit={addTask}><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="Add a task" required/><button className="primary-button">Add task</button></form><div className="kanban-grid">{columns.map(status=><div className="kanban-column" key={status}><h3>{status.replaceAll("_"," ")} <span>{counts[status]}</span></h3>{tasks.filter(t=>t.status===status).map(task=><article className="source-card" key={task.id}><strong>{task.title}</strong><small>{task.priority} · {task.visibility}</small><select value={task.status} onChange={e=>void move(task,e.target.value)}>{columns.map(c=><option key={c} value={c}>{c.replaceAll("_"," ")}</option>)}</select></article>)}</div>)}</div></section><div className="two-column-layout"><section className="data-panel"><h2>Discussion</h2><form onSubmit={addComment}><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Share an update or mention a teammate" required/><button className="primary-button">Post comment</button></form>{comments.map(c=><article className="activity-row" key={c.id}><strong>{c.author_name}</strong><p>{c.body}</p><small>{new Date(c.created_at).toLocaleString()}</small></article>)}</section><section className="data-panel"><h2>Internal notes</h2><form onSubmit={addNote}><input value={noteTitle} onChange={e=>setNoteTitle(e.target.value)} placeholder="Note title" required/><textarea value={noteBody} onChange={e=>setNoteBody(e.target.value)} placeholder="Capture strategy or internal note"/><button className="primary-button">Save internal note</button></form>{notes.map(n=><article className="source-card" key={n.id}><strong>{n.title}</strong><p>{n.body}</p><small>{n.visibility} · {n.author_name}</small></article>)}</section></div><div className="two-column-layout"><section className="data-panel"><h2>Controlled files</h2><form onSubmit={addFile}><input value={fileName} onChange={e=>setFileName(e.target.value)} placeholder="File name" required/><input value={fileUrl} onChange={e=>setFileUrl(e.target.value)} placeholder="Secure file URL" type="url" required/><button className="primary-button">Add file</button></form>{files.map(f=><article className="source-card" key={f.id}><a href={f.url} target="_blank" rel="noreferrer"><strong>{f.name}</strong></a><small>v{f.version} · {f.visibility}</small></article>)}</section><section className="data-panel"><h2>Activity</h2>{activity.map(a=><article className="activity-row" key={a.id}><strong>{a.actor_name}</strong><p>{a.summary}</p><small>{new Date(a.created_at).toLocaleString()}</small></article>)}</section></div></>;}
