"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, Circle, Plus, RefreshCw, Save, Trash2 } from "lucide-react";
import Link from "next/link";
import { apiDelete, apiGet, apiPatch, apiPost, normalizeList } from "@/lib/api";

type Opportunity = { id:number; source_id?:string; source?:string; title:string; agency?:string; solicitation_number?:string; response_deadline?:string; source_url?:string };
type Pipeline = { id:number; workspace_url?:string; stage:string; owner?:number|null; owner_name?:string; probability_of_win:number; estimated_value?:string; next_action?:string; follow_up_date?:string|null; priority?:string; assigned_team?:string; notes?:string; opportunity_detail:Opportunity };
type Member = {id:number;user:{id:number;email:string;first_name:string;last_name:string};role:string;job_title:string};
type Pursuit = { id:number; title:string; stage:string; probability_of_win:number; estimated_value?:string; due_date?:string; next_action?:string; incumbent?:string };
type Task = { id:number; title:string; description?:string; due_at?:string; completed:boolean; pipeline_item?:number };
type SavedSearch = { id:number; name:string; filters:Record<string,string>; alert_frequency:string; enabled:boolean };
const stages=["discovered","reviewing","qualified","bid_decision","capture","teaming","proposal","submitted","awarded","lost","no_bid","archived"];
const human=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const opportunityHref=(opportunity:Opportunity)=>{const sourceId=String(opportunity.source_id??"");if(opportunity.source==="grants.gov"||sourceId.startsWith("grants.gov:")){const id=sourceId.replace(/^grants\.gov:/,"");return id?`/opportunities/federal-grants/${encodeURIComponent(id)}`:"/opportunities/federal-grants"}return sourceId?`/opportunities/federal-contracts/${encodeURIComponent(sourceId)}`:"/opportunities/federal-contracts"};

export function PipelineWorkspace(){
 const [rows,setRows]=useState<Pipeline[]>([]); const [members,setMembers]=useState<Member[]>([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const [pipelineData,memberData]=await Promise.all([apiGet<Pipeline[]>("/pipeline/?page_size=250"),apiGet<Member[]>("/team/members/")]);setRows(normalizeList(pipelineData));setMembers(normalizeList(memberData));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load pipeline")}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function update(id:number,payload:Record<string,unknown>){try{await apiPatch(`/pipeline/${id}/`,payload);await load()}catch(e){setError(e instanceof Error?e.message:"Update failed")}}
 async function pursue(id:number){try{await apiPost(`/workflow/pipeline/${id}/create-pursuit/`,{});await load();setError("Pursuit created and linked.")}catch(e){setError(e instanceof Error?e.message:"Could not create pursuit")}}
 async function remove(id:number,title:string){if(!window.confirm(`Remove ${title} from the pipeline?`))return;try{await apiDelete(`/pipeline/${id}/`);await load();setError("")}catch(e){setError(e instanceof Error?e.message:"Could not remove pipeline item")}}
 const total=useMemo(()=>rows.reduce((s,r)=>s+Number(r.estimated_value??0),0),[rows]);
 return <><header className="module-header"><div><span className="eyebrow">Capture operations</span><h1>Pipeline</h1><p>Qualify opportunities, advance capture stages, and convert selected work into managed pursuits.</p></div><button className="secondary-button" onClick={load}><RefreshCw size={16}/> Refresh</button></header>
 <section className="workspace-summary"><div><span>Pipeline items</span><strong>{rows.length}</strong><small>Live database records</small></div><div><span>Estimated value</span><strong>{money.format(total)}</strong><small>Across valued opportunities</small></div><div><span>In capture</span><strong>{rows.filter(r=>["capture","teaming","proposal"].includes(r.stage)).length}</strong><small>Active capture work</small></div><div><span>Submitted</span><strong>{rows.filter(r=>r.stage==="submitted").length}</strong><small>Awaiting decision</small></div></section>
 {error&&<div className="system-banner warning">{error}</div>}
 <section className="data-panel">{loading?<div className="table-state"><RefreshCw className="spin"/><strong>Loading pipeline</strong></div>:!rows.length?<div className="table-state"><strong>No pipeline items yet</strong><p>Search federal opportunities and use Add to pipeline.</p></div>:<div className="pipeline-list">{rows.map(r=><article className="pipeline-row" key={r.id}><div><span className="eyebrow">{r.opportunity_detail.solicitation_number||((r.opportunity_detail.source==="grants.gov"||r.opportunity_detail.source_id?.startsWith("grants.gov:"))?"Federal grant":"Federal opportunity")}</span><Link className="pipeline-title-link" href={r.workspace_url||opportunityHref(r.opportunity_detail)}><h3>{r.opportunity_detail.title}</h3></Link><p>{r.opportunity_detail.agency||"Agency unavailable"}</p></div><label><span>Stage</span><select value={r.stage} onChange={e=>void update(r.id,{stage:e.target.value})}>{stages.map(s=><option key={s} value={s}>{human(s)}</option>)}</select></label><label><span>Owner</span><select value={r.owner??""} onChange={e=>void update(r.id,{owner:e.target.value?Number(e.target.value):null})}><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.user.id}>{[m.user.first_name,m.user.last_name].filter(Boolean).join(" ")||m.user.email}</option>)}</select></label><label><span>Priority</span><select value={r.priority??"medium"} onChange={e=>void update(r.id,{priority:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label><span>Team</span><input value={r.assigned_team??""} onBlur={e=>void update(r.id,{assigned_team:e.target.value})} onChange={e=>setRows(x=>x.map(a=>a.id===r.id?{...a,assigned_team:e.target.value}:a))}/></label><label><span>Follow-up</span><input type="date" value={r.follow_up_date??""} onChange={e=>void update(r.id,{follow_up_date:e.target.value||null})}/></label><label><span>Win probability</span><input type="number" min="0" max="100" value={r.probability_of_win} onChange={e=>void update(r.id,{probability_of_win:Number(e.target.value)})}/></label><label className="pipeline-next-action"><span>Next action</span><input value={r.next_action??""} onBlur={e=>void update(r.id,{next_action:e.target.value})} onChange={e=>setRows(x=>x.map(a=>a.id===r.id?{...a,next_action:e.target.value}:a))}/></label><div className="row-actions"><Link className="secondary-button" href={r.workspace_url||opportunityHref(r.opportunity_detail)}>Open workspace</Link><button className="primary-button" onClick={()=>void pursue(r.id)}>Create pursuit <ChevronRight size={15}/></button><button className="icon-button danger-button" title="Remove from pipeline" aria-label={`Remove ${r.opportunity_detail.title} from pipeline`} onClick={()=>void remove(r.id,r.opportunity_detail.title)}><Trash2 size={17}/></button></div></article>)}</div>}</section></>;
}

export function PursuitsWorkspace(){
 const [rows,setRows]=useState<Pursuit[]>([]);const [error,setError]=useState("");const[selected,setSelected]=useState<Pursuit|null>(null);const [dragging,setDragging]=useState<number|null>(null);const [dragStage,setDragStage]=useState("");const [now]=useState(()=>Date.now());
 const load=useCallback(async()=>{try{setRows(normalizeList(await apiGet<Pursuit[]>("/pursuits/?page_size=250")));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load pursuits")}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function patch(id:number,payload:Record<string,unknown>){try{const updated=await apiPatch<Pursuit>(`/pursuits/${id}/`,payload);setRows(current=>current.map(row=>row.id===id?updated:row));if(selected?.id===id)setSelected(updated)}catch(e){setError(e instanceof Error?e.message:"Update failed")}}
 async function movePursuit(id:number,stage:string){setRows(current=>current.map(row=>row.id===id?{...row,stage}:row));setDragging(null);setDragStage("");await patch(id,{stage})}
 const active=rows.filter(r=>!["awarded","lost","no_bid","archived"].includes(r.stage));
 const totalValue=active.reduce((sum,row)=>sum+Number(row.estimated_value??0),0);
 const weighted=active.reduce((sum,row)=>sum+(Number(row.estimated_value??0)*(Number(row.probability_of_win??0)/100)),0);
 const dueSoon=active.filter(row=>row.due_date&&new Date(row.due_date).getTime()-now<1000*60*60*24*14&&new Date(row.due_date).getTime()>now).length;
 return <><header className="module-header"><div><span className="eyebrow">Capture management</span><h1>Pursuits</h1><p>Manage bid decisions, capture posture, probability, value, deadlines, and execution actions in one workspace.</p></div><button className="secondary-button" onClick={load}><RefreshCw size={16}/> Refresh</button></header>
 <section className="workspace-summary"><div><span>Active pursuits</span><strong>{active.length}</strong><small>Excludes closed outcomes</small></div><div><span>Total value</span><strong>{money.format(totalValue)}</strong><small>Active estimated value</small></div><div><span>Weighted pipeline</span><strong>{money.format(weighted)}</strong><small>Value × win probability</small></div><div><span>Due within 14 days</span><strong>{dueSoon}</strong><small>Immediate capture attention</small></div></section>
 {error&&<div className="system-banner warning">{error}</div>}<section className="data-panel"><div className="kanban-help">Drag cards between stages or use the stage selector. Changes save immediately.</div><div className="kanban-board">{["triage","qualify","bid_decision","capture","proposal","submitted","awarded"].map(stage=><section className={`kanban-column ${dragStage===stage?"drag-over":""}`} key={stage} onDragOver={e=>{e.preventDefault();setDragStage(stage)}} onDragLeave={()=>setDragStage(current=>current===stage?"":current)} onDrop={e=>{e.preventDefault();const id=Number(e.dataTransfer.getData("text/pursuit-id")||dragging);if(id)void movePursuit(id,stage)}}><header><span>{human(stage)}</span><b>{rows.filter(r=>r.stage===stage).length}</b></header>{rows.filter(r=>r.stage===stage).map(r=><article className={`kanban-card pursuit-card ${dragging===r.id?"dragging":""}`} key={r.id} draggable onDragStart={e=>{setDragging(r.id);e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/pursuit-id",String(r.id))}} onDragEnd={()=>{setDragging(null);setDragStage("")}} onClick={()=>setSelected(r)}><strong>{r.title}</strong><p>{r.next_action||"No next action set"}</p><div className="pursuit-card-metrics"><span>{money.format(Number(r.estimated_value??0))}</span><span>{r.probability_of_win}% Pwin</span></div>{r.due_date?<small>Due {new Date(r.due_date).toLocaleDateString()}</small>:null}<label onClick={e=>e.stopPropagation()}><span>Move to</span><select value={r.stage} onChange={e=>void movePursuit(r.id,e.target.value)}>{["triage","qualify","bid_decision","capture","proposal","submitted","awarded","lost","no_bid","archived"].map(s=><option key={s} value={s}>{human(s)}</option>)}</select></label></article>)}</section>)}</div></section>
 {selected&&<div className="document-viewer-backdrop"><div className="record-modal pursuit-detail-modal"><header><div><span className="eyebrow">Capture plan</span><h2>{selected.title}</h2></div><button type="button" className="icon-button" onClick={()=>setSelected(null)}>×</button></header><div className="record-form"><label><span>Stage</span><select value={selected.stage} onChange={e=>void patch(selected.id,{stage:e.target.value})}>{["triage","qualify","bid_decision","capture","proposal","submitted","awarded","lost","no_bid","archived"].map(s=><option key={s} value={s}>{human(s)}</option>)}</select></label><label><span>Win probability</span><input type="number" min="0" max="100" value={selected.probability_of_win} onChange={e=>setSelected({...selected,probability_of_win:Number(e.target.value)})} onBlur={()=>void patch(selected.id,{probability_of_win:selected.probability_of_win})}/></label><label><span>Estimated value</span><input type="number" value={selected.estimated_value??""} onChange={e=>setSelected({...selected,estimated_value:e.target.value})} onBlur={()=>void patch(selected.id,{estimated_value:selected.estimated_value||null})}/></label><label><span>Due date</span><input type="datetime-local" value={selected.due_date?.slice(0,16)??""} onChange={e=>{setSelected({...selected,due_date:e.target.value});void patch(selected.id,{due_date:e.target.value||null})}}/></label><label><span>Incumbent</span><input value={selected.incumbent??""} onChange={e=>setSelected({...selected,incumbent:e.target.value})} onBlur={()=>void patch(selected.id,{incumbent:selected.incumbent})}/></label><label><span>Next action</span><textarea value={selected.next_action??""} onChange={e=>setSelected({...selected,next_action:e.target.value})} onBlur={()=>void patch(selected.id,{next_action:selected.next_action})}/></label></div><footer><span className="capture-score">Weighted value: {money.format(Number(selected.estimated_value??0)*(selected.probability_of_win/100))}</span><button className="primary-button" onClick={()=>setSelected(null)}>Done</button></footer></div></div>}
 </>;
}

export function TasksWorkspace(){
 const [rows,setRows]=useState<Task[]>([]);const [title,setTitle]=useState("");const [due,setDue]=useState("");const [error,setError]=useState("");
 const load=useCallback(async()=>{try{setRows(normalizeList(await apiGet<Task[]>("/tasks/?page_size=250")));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load tasks")}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function create(e:FormEvent){e.preventDefault();try{await apiPost("/workflow/tasks/",{title,due_at:due||null});setTitle("");setDue("");await load()}catch(e){setError(e instanceof Error?e.message:"Could not create task")}}
 async function toggle(t:Task){await apiPatch(`/tasks/${t.id}/`,{completed:!t.completed});await load()}
 async function remove(id:number){await apiDelete(`/tasks/${id}/`);await load()}
 return <><header className="module-header"><div><span className="eyebrow">Execution management</span><h1>Tasks</h1><p>Create, complete, and track capture work with due dates and pipeline relationships.</p></div></header><section className="data-panel"><form className="quick-create-form" onSubmit={create}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Add a task…" required/><input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/><button className="primary-button"><Plus size={16}/> Add task</button></form>{error&&<div className="form-error">{error}</div>}<div className="task-list">{rows.map(t=><article className={`task-row ${t.completed?"complete":""}`} key={t.id}><button className="icon-button" onClick={()=>void toggle(t)}>{t.completed?<CheckCircle2/>:<Circle/>}</button><div><strong>{t.title}</strong><span>{t.due_at?new Date(t.due_at).toLocaleString():"No due date"}</span></div><button className="icon-button" onClick={()=>void remove(t.id)}><Trash2 size={17}/></button></article>)}</div></section></>;
}

export function SavedSearchesWorkspace(){
 const [rows,setRows]=useState<SavedSearch[]>([]);const [error,setError]=useState("");
 const load=useCallback(async()=>{try{setRows(normalizeList(await apiGet<SavedSearch[]>("/saved-searches/?page_size=250")));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load searches")}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function remove(id:number){await apiDelete(`/saved-searches/${id}/`);await load()}
 return <><header className="module-header"><div><span className="eyebrow">Opportunity monitoring</span><h1>Saved Searches</h1><p>Reuse live SAM.gov filters and maintain searches that feed future alerts.</p></div><button className="secondary-button" onClick={load}><RefreshCw size={16}/> Refresh</button></header>{error&&<div className="system-banner warning">{error}</div>}<section className="data-panel"><div className="saved-search-grid">{rows.map(r=>{const {source,...searchFilters}=r.filters;const q=new URLSearchParams(searchFilters).toString();const route=source==="grants.gov"?"/opportunities/federal-grants":"/opportunities/federal-contracts";return <article className="saved-search-card" key={r.id}><div><Save size={18}/><span>{r.alert_frequency}</span></div><h3>{r.name}</h3><p>{Object.entries(r.filters).filter(([,v])=>v).map(([k,v])=>`${human(k)}: ${v}`).join(" · ")||"No filters"}</p><footer><a className="primary-button" href={`${route}?${q}`}>Run search</a><button className="icon-button" onClick={()=>void remove(r.id)}><Trash2 size={17}/></button></footer></article>})}</div></section></>;
}
