"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Bell, Bot, Building2, CalendarClock, Database, ExternalLink, Eye, Landmark, Mail, MessageSquare, Network, Phone, RefreshCw, Search, Target, Trash2, Users, X } from "lucide-react";
import Link from "next/link";
import { apiDelete, apiGet, apiPatch, apiPost, normalizeList } from "@/lib/api";

type Row = Record<string, unknown>;

function deferredLoad(load: () => void | Promise<void>) {
  const timer = window.setTimeout(() => void load(), 0);
  return () => window.clearTimeout(timer);
}

function useInitialLoad(load: () => void | Promise<void>) {
  const initialLoad = useRef(load);
  useEffect(() => deferredLoad(() => initialLoad.current()), []);
}

function money(value: unknown) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(Number(value ?? 0));
}

function text(value: unknown, fallback = "—") {
  if (value === null || value === undefined || value === "") return fallback;
  return String(value);
}

function firstText(...values: unknown[]) {
  for (const value of values) {
    if (value !== null && value !== undefined && value !== "") return String(value);
  }
  return "—";
}

export function ForecastWorkspace() {
  const [query,setQuery]=useState(""); const [rows,setRows]=useState<Row[]>([]); const [status,setStatus]=useState("Loading official forecast sources…"); const [selected,setSelected]=useState<Row|null>(null);
  const load=useCallback(async()=>{setStatus("Refreshing Acquisition.gov forecast sources…");try{const data=await apiGet<{results:Row[];reachable:boolean}>(`/intelligence/forecasts/sources/?q=${encodeURIComponent(query)}`);setRows(data.results??[]);setStatus(`${data.results?.length??0} official agency forecast sources loaded${data.reachable?"":" from the fallback directory"}.`)}catch(error){setStatus(error instanceof Error?error.message:"Forecast source request failed")}},[query]);
  useInitialLoad(load);
  const eventLabel=(row:Row,index:number)=>{const value=firstText(row.status,row.event_type,row.update_type).toLowerCase();if(value.includes("cancel"))return "Cancelled";if(value.includes("delay"))return "Delayed";if(value.includes("award"))return "Awarded";if(value.includes("release")||value.includes("solicit"))return "Solicitation released";if(value.includes("update"))return "Updated forecast";return "Active";};
  const active=rows.filter((r,i)=>!eventLabel(r,i).includes("Cancelled")).length;
  return <><header className="feature-hero"><div><span className="eyebrow">Forward-looking acquisition intelligence</span><h1>Federal Procurement Forecasts</h1><p>A live intelligence feed for upcoming agency requirements, forecast changes, and official source activity—without losing your ForgeGov context.</p></div><button className="secondary-button" onClick={()=>void load()}><RefreshCw size={16}/> Refresh</button></header>
  <section className="release-four-summary"><div><span>Sources loaded</span><strong>{rows.length}</strong></div><div><span>Active forecasts</span><strong>{active}</strong></div><div><span>Tracked agencies</span><strong>{new Set(rows.map(r=>text(r.agency))).size}</strong></div><div><span>Workspace</span><strong>Live feed</strong></div></section>
  <section className="data-panel"><form className="quick-create-form" onSubmit={e=>{e.preventDefault();void load()}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Department of Defense, VA, DHS…"/><button className="primary-button"><Search size={16}/> Search forecasts</button></form><p className="inline-message">{status}</p></section>
  <section className="forecast-feed">{rows.map((row,index)=>{const event=eventLabel(row,index);return <article className="data-panel" key={`${text(row.agency)}-${index}`}><div className="forecast-date"><b>{String(index+1).padStart(2,"0")}</b><small>feed</small></div><div><span className="status-badge">{event}</span><div className="forecast-card-heading"><h3 title={text(row.agency)}>{text(row.agency)}</h3><span>Agency procurement forecast</span></div><p>{firstText(row.description,row.summary,"Recurring procurement forecast published through the federal acquisition forecast directory.")}</p><div className="forecast-event-row"><span className="forecast-event-tag">Official source</span><span className="forecast-event-tag">Agency forecast</span>{row.updated_at?<span className="forecast-event-tag">Updated {text(row.updated_at)}</span>:null}</div><small>Official recurring procurement forecast source.</small></div><button className="primary-button" onClick={()=>setSelected({...row,event})}>Review in ForgeGov <Eye size={15}/></button></article>})}</section>
  {selected&&<div className="document-viewer-backdrop"><div className="document-viewer"><header><div><Landmark/><strong>{text(selected.agency)}</strong></div><div><a className="secondary-button" href={text(selected.forecast_url)} target="_blank" rel="noreferrer">Official source <ExternalLink size={15}/></a><button className="icon-button" onClick={()=>setSelected(null)}>×</button></div></header><div className="document-viewer-empty"><div><Landmark size={44}/><h2>{text(selected.agency)} procurement forecast</h2><div className="intelligence-drawer-grid"><div><span>Activity</span><strong>{text(selected.event)}</strong></div><div><span>Source</span><strong>Acquisition.gov directory</strong></div><div><span>Agency</span><strong>{text(selected.agency)}</strong></div><div><span>ForgeGov status</span><strong>Reviewed in workspace</strong></div></div><p>{firstText(selected.description,selected.summary,"This agency publishes recurring acquisition forecasts. ForgeGov preserves the agency context and provides the official source as a fallback when secure embedding is blocked.")}</p><a className="primary-button" href={text(selected.forecast_url)} target="_blank" rel="noreferrer">Continue to official source</a></div></div></div></div>}</>;
}

export function StateLocalWorkspace() {
  const [query, setQuery] = useState("");
  const [state, setState] = useState("");
  const [rows, setRows] = useState<Row[]>([]);
  const [message, setMessage] = useState("Loading official state procurement portals…");
  const load = useCallback(async () => {
    const params = new URLSearchParams(); if (query) params.set("q", query); if (state) params.set("state", state);
    try { const data = await apiGet<{ results: Row[] }>(`/intelligence/state-local/sources/?${params}`); setRows(data.results ?? []); setMessage(`${data.results?.length ?? 0} official procurement sources loaded.`); }
    catch (error) { setMessage(error instanceof Error ? error.message : "State/local source request failed"); }
  }, [query, state]);
  useInitialLoad(load);
  return <>
    <header className="feature-hero"><div><span className="eyebrow">State and local market access</span><h1>State & Local Procurement Sources</h1><p>Open verified public procurement portals while ForgeGov’s source-specific adapters are expanded.</p></div></header>
    <section className="data-panel"><form className="advanced-filter-grid" onSubmit={(e) => {e.preventDefault();void load();}}><label><span>Keyword</span><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="California, construction…"/></label><label><span>State code</span><input value={state} onChange={(e)=>setState(e.target.value.toUpperCase())} maxLength={2} placeholder="TX"/></label><button className="primary-button"><Search size={16}/> Find sources</button></form><p className="inline-message">{message}</p></section>
    <section className="source-card-grid">{rows.map((row, index)=><article className="source-card" key={`${text(row.state)}-${index}`}><Building2/><div><span>{text(row.state)}</span><h3>{text(row.jurisdiction)}</h3><p>{text(row.coverage)}</p></div><a className="primary-button" href={text(row.portal)} target="_blank" rel="noreferrer">Open portal <ExternalLink size={15}/></a></article>)}</section>
  </>;
}

type VehicleResult = { results: Row[]; page_metadata?: { hasNext?: boolean; total?: number }; persisted?: { created?: number; updated?: number } };
export function ContractVehicleWorkspace() {
  const [query, setQuery] = useState(""); const [agency, setAgency] = useState(""); const [recipient, setRecipient] = useState(""); const [page, setPage] = useState(1); const [data, setData] = useState<VehicleResult>({results:[]}); const [message,setMessage]=useState("Loading federal contract vehicles…"); const [selected,setSelected]=useState<Row|null>(null);
  const search = useCallback(async (requestedPage = 1) => {
    setMessage("Searching USAspending IDV records…"); const params=new URLSearchParams({page:String(requestedPage),limit:"50",persist:"true"}); if(query)params.set("q",query);if(agency)params.set("agency",agency);if(recipient)params.set("recipient",recipient);
    try{const result=await apiGet<VehicleResult>(`/live/usaspending/vehicles/?${params}`);setData(result);setPage(requestedPage);setMessage(`${result.results?.length??0} contract vehicles loaded.`);}catch(error){setMessage(error instanceof Error?error.message:"Vehicle search failed");}
  },[agency,query,recipient]);
  useInitialLoad(() => search(1));
  const potential=useMemo(()=>data.results.reduce((sum,row)=>sum+Number(row["Potential Award Amount"]??row["Award Amount"]??0),0),[data.results]);
  return <>
    <header className="feature-hero"><div><span className="eyebrow">IDIQ, BPA and contract vehicle intelligence</span><h1>Federal Contract Vehicles</h1><p>Search live USAspending IDV records, identify vehicle holders, and persist results for competitor analysis.</p></div></header>
    <section className="insight-strip"><div><span>Loaded</span><strong>{data.results.length}</strong></div><div><span>Potential value</span><strong>{money(potential)}</strong></div><div><span>Page</span><strong>{page}</strong></div><div><span>Source</span><strong>USAspending</strong></div></section>
    <section className="data-panel"><form className="advanced-filter-grid" onSubmit={(e)=>{e.preventDefault();void search(1);}}><label><span>Keyword</span><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="logistics, IT, maintenance"/></label><label><span>Awarding agency</span><input value={agency} onChange={(e)=>setAgency(e.target.value)} placeholder="Department of Defense"/></label><label><span>Vehicle holder</span><input value={recipient} onChange={(e)=>setRecipient(e.target.value)} placeholder="Company name"/></label><button className="primary-button"><Search size={16}/> Search vehicles</button></form><p className="inline-message">{message}</p></section>
    <section className="data-panel"><div className="opportunity-results-grid vehicle-results-grid">{data.results.map((row,index)=><article className="opportunity-result-card" key={`${text(row.generated_unique_award_id)}-${index}`}><div className="opportunity-result-main"><div className="result-source-row"><span className="source-chip"><Network size={14}/>{text(row["Award Type"])}</span><span>{text(row["Award ID"])}</span></div><h3>{text(row.Description,"Contract vehicle details unavailable")}</h3><div className="result-facts"><Link className="entity-link" href={`/intelligence/agency/${encodeURIComponent(text(row["Awarding Agency"]))}`}>{text(row["Awarding Agency"])} <Eye size={13}/></Link><span>{money(row["Potential Award Amount"]??row["Award Amount"])}</span></div><Link className="entity-link" href={`/participants/vendors/profile?name=${encodeURIComponent(text(row["Recipient Name"],""))}`}>{text(row["Recipient Name"],"Unknown holder")} <Eye size={14}/></Link></div><div className="opportunity-result-actions vehicle-card-actions"><button className="primary-button" onClick={()=>setSelected(row)}>Vehicle intelligence <Eye size={14}/></button><Link className="secondary-button" href={`/participants/vendors/profile?name=${encodeURIComponent(text(row["Recipient Name"],""))}`}>Holder profile</Link></div></article>)}</div><div className="pagination-bar"><button className="secondary-button" disabled={page<=1} onClick={()=>void search(page-1)}>Previous</button><span>Page {page}</span><button className="secondary-button" disabled={!data.page_metadata?.hasNext} onClick={()=>void search(page+1)}>Next</button></div></section>
    {selected&&<div className="document-viewer-backdrop"><div className="document-viewer"><header><div><Network/><strong>{text(selected["Award ID"],"Contract vehicle")}</strong></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></header><div className="document-viewer-empty"><div><Network size={44}/><h2>{text(selected.Description,"Federal contract vehicle")}</h2><div className="intelligence-drawer-grid"><div><span>Vehicle holder</span><strong>{text(selected["Recipient Name"])}</strong></div><div><span>Awarding agency</span><Link className="entity-link" href={`/intelligence/agency/${encodeURIComponent(text(selected["Awarding Agency"]))}`}><strong>{text(selected["Awarding Agency"])}</strong><Eye size={13}/></Link></div><div><span>Potential value</span><strong>{money(selected["Potential Award Amount"]??selected["Award Amount"])}</strong></div><div><span>Award type</span><strong>{text(selected["Award Type"])}</strong></div><div><span>Start date</span><strong>{text(selected["Start Date"])}</strong></div><div><span>End date</span><strong>{text(selected["End Date"])}</strong></div></div><div className="vehicle-card-actions"><Link className="primary-button" href={`/participants/vendors/profile?name=${encodeURIComponent(text(selected["Recipient Name"],""))}`}>Open holder profile</Link>{selected.generated_unique_award_id?<a className="secondary-button" href={`https://www.usaspending.gov/award/${text(selected.generated_unique_award_id)}/`} target="_blank" rel="noreferrer">Official record <ExternalLink size={14}/></a>:null}</div></div></div></div></div>}
  </>;
}

export function SubcontractWorkspace() {
  const [query,setQuery]=useState("");const[state,setState]=useState("");const[idv,setIdv]=useState("");const[subnet,setSubnet]=useState<Row[]>([]);const[subawards,setSubawards]=useState<Row[]>([]);const[subnetPage,setSubnetPage]=useState(0);const[subnetHasNext,setSubnetHasNext]=useState(false);const[subnetTotal,setSubnetTotal]=useState<number|null>(null);const[busySubnetId,setBusySubnetId]=useState("");const[message,setMessage]=useState("Loading subcontract intelligence…");const[sourceStatus,setSourceStatus]=useState<"loading"|"live"|"indexed"|"cached"|"unavailable">("loading");const[sourceName,setSourceName]=useState("SBA SUBNet");const[selectedSubnet,setSelectedSubnet]=useState<Row|null>(null);const[subnetQuestion,setSubnetQuestion]=useState("");const[subnetAnswer,setSubnetAnswer]=useState("");const[subnetAiBusy,setSubnetAiBusy]=useState(false);
  const load=useCallback(async(requestedPage=0)=>{setMessage("Checking SBA SUBNet and SAM subaward reporting…");const [subnetResult,subawardResult]=await Promise.allSettled([apiGet<{results:Row[];has_next?:boolean;page?:number;status?:"live"|"indexed"|"cached"|"unavailable";warning?:string;source_name?:string}>(`/live/sba/subnet/?q=${encodeURIComponent(query)}&state=${encodeURIComponent(state)}&page=${requestedPage}&page_size=20`),apiGet<{results:Row[]}>(`/live/sam/subawards/?referenced_idv=${encodeURIComponent(idv)}&limit=50`)]);const notes:string[]=[];if(subnetResult.status==="fulfilled"){const result=subnetResult.value;setSubnet(result.results??[]);setSubnetPage(result.page??requestedPage);setSubnetHasNext(Boolean(result.has_next));setSubnetTotal(typeof (result as {total_records?:unknown}).total_records==="number"?Number((result as {total_records?:number}).total_records):null);setSourceStatus(result.status??"live");setSourceName(result.source_name??"SBA SUBNet");if(result.status==="indexed")notes.push(`${result.results?.length??0} official SBA opportunity pages loaded through ForgeGov live web search while direct SUBNet access reconnects.`);else if(result.status==="cached")notes.push(`${result.results?.length??0} verified SUBNet opportunities loaded from ForgeGov's last successful SBA snapshot. Live refresh will continue automatically.`);else if(result.status==="unavailable")notes.push("Live SBA access is reconnecting. ForgeGov will retry automatically while SAM subaward intelligence remains available.");else notes.push(`${result.results?.length??0} current opportunities loaded from ${result.source_name??"SBA SUBNet"}.`)}else{setSourceStatus("unavailable");setSourceName("SBA SUBNet");notes.push("Live SBA access is reconnecting. ForgeGov will retry automatically while SAM subaward intelligence remains available.")}if(subawardResult.status==="fulfilled"){setSubawards(subawardResult.value.results??[]);notes.push(`${subawardResult.value.results?.length??0} SAM subawards loaded.`)}else notes.push("SAM subaward reporting could not be refreshed.");setMessage(notes.join(" "));},[idv,query,state]);
  async function addSubnetToPipeline(row:Row){const sourceId=text(row.source_id,"");if(!sourceId)return;setBusySubnetId(sourceId);try{await apiPost("/workflow/opportunity-to-pipeline/",{source_id:sourceId,stage:"reviewing"});setMessage(`Added “${text(row.title,"SUBNet opportunity")}” to the pipeline.`)}catch(error){setMessage(error instanceof Error?error.message:"Could not add SUBNet opportunity to pipeline")}finally{setBusySubnetId("")}}
  async function askSubnet(){if(!selectedSubnet||subnetQuestion.trim().length<2)return;setSubnetAiBusy(true);setSubnetAnswer("");try{const prompt=`Act as a senior capture manager. Analyze only the SBA SUBNet listing facts below. Clearly separate listing facts from inference, identify risks, questions for the prime, teaming gaps, and next actions. Listing: ${JSON.stringify(selectedSubnet)}\n\nUser question: ${subnetQuestion}`;const result=await apiPost<{answer?:string}>("/ai/chat/",{message:prompt,history:[]});setSubnetAnswer(result.answer||"ForgeAI did not return an answer.")}catch(error){setSubnetAnswer(error instanceof Error?error.message:"ForgeAI could not analyze this SUBNet opportunity.")}finally{setSubnetAiBusy(false)}}
  useInitialLoad(()=>load(0));
  useEffect(()=>{if(sourceStatus==="live"||sourceStatus==="loading")return;const timer=window.setInterval(()=>void load(subnetPage),60000);return()=>window.clearInterval(timer)},[load,sourceStatus,subnetPage]);
  return <><header className="feature-hero"><div><span className="eyebrow">Prime and subcontract intelligence</span><h1>Subcontracting</h1><p>Current SBA SUBNet postings and reported SAM.gov subaward performance in one workspace.</p></div><div className={`source-health-pill ${sourceStatus}`}><span/>{sourceStatus==="loading"?"Checking SBA source":sourceStatus==="live"?`${sourceName} live`:sourceStatus==="indexed"?"Official SBA web index":sourceStatus==="cached"?"Verified cached results":"SBA reconnecting"}</div></header>
  <section className="data-panel"><form className="advanced-filter-grid" onSubmit={e=>{e.preventDefault();void load(0)}}><label><span>SUBNet keyword</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="mowing, HVAC, logistics"/></label><label><span>State</span><input value={state} onChange={e=>setState(e.target.value)} placeholder="Texas"/></label><label><span>Referenced IDV PIID</span><input value={idv} onChange={e=>setIdv(e.target.value)} placeholder="W52P1J18DA075"/></label><button className="primary-button"><RefreshCw size={16}/>Refresh intelligence</button></form><p className="inline-message">{message}</p></section>
  <div className="split-intelligence"><section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">CURRENT OPPORTUNITIES</span><h2>SBA SUBNet</h2></div><small>{subnet.length} on this page</small></div><div className="intelligence-list subnet-opportunity-list">{subnet.length?subnet.map((row,index)=><article className="interactive-intelligence-row" key={`${firstText(row.source_id,row.title)}-${index}`}><Target/><div><button className="entity-link entity-button" onClick={()=>setSelectedSubnet(row)}><h3>{text(row.title)}</h3><Eye size={14}/></button><p>{text(row.description,"")}</p><small>{text(row.place_of_performance)} · NAICS {text(row.naics)} · Closes {text(row.closing_date)}</small></div><div className="row-actions"><button className="secondary-button" onClick={()=>setSelectedSubnet(row)}>Review details <Eye size={15}/></button><button className="primary-button" disabled={busySubnetId===text(row.source_id,"")} onClick={()=>void addSubnetToPipeline(row)}><Target size={15}/>{busySubnetId===text(row.source_id,"")?"Adding…":"Add to pipeline"}</button>{row.source_url?<a className="icon-button" href={String(row.source_url)} target="_blank" rel="noreferrer" title="Open official SBA record"><ExternalLink size={17}/></a>:null}</div></article>):<div className="table-state compact-state"><Target/><strong>{sourceStatus==="unavailable"?"Live SBA access is reconnecting":"No current opportunities matched"}</strong><p>{sourceStatus==="unavailable"?"ForgeGov will retry automatically. SAM subaward intelligence remains active while the official SBA source reconnects.":"Try a broader keyword or clear the state filter."}</p></div>}</div><div className="pagination-bar"><button className="secondary-button" disabled={subnetPage<=0} onClick={()=>void load(subnetPage-1)}>Previous</button><span>Page {subnetPage+1} · showing {subnet.length} of 20{subnetTotal!==null?` · ${subnetTotal} matched`:""}</span><button className="secondary-button" disabled={!subnetHasNext} onClick={()=>void load(subnetPage+1)}>Next</button></div></section>
  <section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">REPORTED PERFORMANCE</span><h2>SAM Subawards</h2></div><small>{subawards.length} results</small></div><div className="intelligence-list">{subawards.map((row,index)=><article key={`${text(row.piid)}-${index}`}><Database/><div><Link className="entity-link" href={`/participants/vendors/profile?name=${encodeURIComponent(text(row.subcontractor,""))}`}><h3>{text(row.subcontractor)||"Reported subcontractor"}</h3><Eye size={14}/></Link><p>{text(row.description)}</p><small>{text(row.prime_contractor)} · {money(row.amount)} · PIID {text(row.piid)}</small></div></article>)}</div></section></div>
  {selectedSubnet&&<div className="document-viewer-backdrop" role="dialog" aria-modal="true"><div className="record-modal subnet-detail-modal"><header><div><span className="eyebrow">SBA SUBNET OPPORTUNITY</span><h2>{text(selectedSubnet.title)}</h2></div><button className="icon-button" onClick={()=>setSelectedSubnet(null)}><X/></button></header><div className="subnet-detail-body"><p className="subnet-description">{text(selectedSubnet.description,"No description was included in the SBA listing.")}</p><div className="intelligence-drawer-grid"><div><span>Prime contractor</span>{text(selectedSubnet.prime_contractor)!=="—"?<Link className="entity-link" href={`/participants/vendors/profile?name=${encodeURIComponent(text(selectedSubnet.prime_contractor,""))}`}><strong>{text(selectedSubnet.prime_contractor)}</strong><Eye size={13}/></Link>:<strong>Not provided</strong>}</div><div><span>NAICS</span><strong>{text(selectedSubnet.naics)}</strong></div><div><span>Place of performance</span><strong>{text(selectedSubnet.place_of_performance)}</strong></div><div><span>Closing date</span><strong>{text(selectedSubnet.closing_date)}</strong></div><div><span>Performance start</span><strong>{firstText(selectedSubnet.performance_start_date,selectedSubnet.performance_start)}</strong></div><div><span>Contact</span><strong>{firstText(selectedSubnet.contact,selectedSubnet.point_of_contact)}</strong></div></div><section className="subnet-ai-panel"><div className="panel-heading"><Bot/><div><h3>ForgeAI subcontract analyst</h3><p>Ask about bid fit, risks, questions for the prime, teaming needs, or next actions. Answers use this listing unless another source is explicitly identified.</p></div></div><textarea value={subnetQuestion} onChange={e=>setSubnetQuestion(e.target.value)} placeholder="Should we pursue this opportunity? What should we verify first?"/><button className="primary-button" disabled={subnetAiBusy||subnetQuestion.trim().length<2} onClick={()=>void askSubnet()}>{subnetAiBusy?"Analyzing…":"Ask ForgeAI"}</button>{subnetAnswer&&<div className="ai-readable-answer">{subnetAnswer}</div>}</section></div><footer><span>Source: {sourceName}</span>{selectedSubnet.source_url?<a className="primary-button" href={String(selectedSubnet.source_url)} target="_blank" rel="noreferrer">Open official SBA record <ExternalLink size={15}/></a>:null}</footer></div></div>}
  </>;
}

type PartnerRow = {
  id: number | string;
  name: string;
  uei?: string;
  cage_code?: string;
  city?: string;
  state?: string;
  website?: string;
  award_count?: number;
  obligated_amount?: number | string;
  naics_codes?: string[];
  socioeconomic_statuses?: string[];
};

type TeamingRequestRow = {
  id: number;
  company_name: string;
  role: string;
  status: string;
  capabilities?: string;
  point_of_contact?: string;
  due_date?: string | null;
  notes?: string;
  pursuit?: number | null;
  created_at?: string;
  updated_at?: string;
};

type TeamingActivityRow = {
  id: number;
  activity_type: string;
  subject: string;
  details?: string;
  occurred_at: string;
  follow_up_at?: string | null;
  completed: boolean;
  teaming_request?: number;
  created_at?: string;
  updated_at?: string;
};

export function TeamingWorkspace(){
  const[query,setQuery]=useState("");const[naics,setNaics]=useState("");const[state,setState]=useState("");const[status,setStatus]=useState("");const[partners,setPartners]=useState<PartnerRow[]>([]);const[requests,setRequests]=useState<TeamingRequestRow[]>([]);const[message,setMessage]=useState("Search stored vendor and award intelligence for teaming candidates.");
  const[selected,setSelected]=useState<TeamingRequestRow|null>(null);const[activities,setActivities]=useState<TeamingActivityRow[]>([]);const[activityType,setActivityType]=useState("note");const[subject,setSubject]=useState("");const[details,setDetails]=useState("");const[followUp,setFollowUp]=useState("");
  const loadRequests=useCallback(async()=>{const data=await apiGet<TeamingRequestRow[]|{results:TeamingRequestRow[]}>("/teaming-requests/?page_size=100");setRequests(normalizeList<TeamingRequestRow>(data));},[]);
  useInitialLoad(loadRequests);
  async function searchPartners(){const params=new URLSearchParams();if(query)params.set("q",query);if(naics)params.set("naics",naics);if(state)params.set("state",state);if(status)params.set("status",status);setMessage("Analyzing vendors and award history…");try{const data=await apiGet<{results:PartnerRow[]}>(`/intelligence/partners/?${params}`);setPartners(data.results??[]);setMessage(`${data.results?.length??0} potential teaming partners loaded.`);}catch(error){setMessage(error instanceof Error?error.message:"Partner discovery failed");}}
  async function createLead(partner:PartnerRow){try{await apiPost("/teaming-requests/",{company_name:partner.name,role:"subcontractor",status:"draft",capabilities:[...(partner.naics_codes??[]),...(partner.socioeconomic_statuses??[])].join(", ")});setMessage(`${partner.name} added as a draft teaming lead.`);await loadRequests();}catch(error){setMessage(error instanceof Error?error.message:"Teaming lead could not be created");}}
  async function removeLead(request:TeamingRequestRow){if(!window.confirm(`Delete teaming lead for ${request.company_name}?`))return;try{await apiDelete(`/teaming-requests/${request.id}/`);if(selected?.id===request.id)setSelected(null);await loadRequests();setMessage(`${request.company_name} removed from the teaming workspace.`)}catch(error){setMessage(error instanceof Error?error.message:"Teaming lead could not be deleted")}}
  async function updateLead(id:number,payload:Record<string,unknown>){try{await apiPatch(`/teaming-requests/${id}/`,payload);await loadRequests();if(selected?.id===id)setSelected({...selected,...payload} as TeamingRequestRow)}catch(error){setMessage(error instanceof Error?error.message:"Teaming lead could not be updated")}}
  async function openActivity(request:TeamingRequestRow){setSelected(request);try{setActivities(await apiGet<TeamingActivityRow[]>(`/workflow/teaming/${request.id}/activities/`))}catch(error){setMessage(error instanceof Error?error.message:"Activity history could not be loaded")}}
  async function addActivity(){if(!selected||!subject.trim())return;try{await apiPost(`/workflow/teaming/${selected.id}/activities/`,{activity_type:activityType,subject,details,follow_up_at:followUp||null});setSubject("");setDetails("");setFollowUp("");await openActivity(selected);setMessage("Teaming activity saved.")}catch(error){setMessage(error instanceof Error?error.message:"Activity could not be saved")}}
  async function toggleActivity(row:TeamingActivityRow){await apiPatch(`/workflow/teaming-activities/${row.id}/`,{completed:!row.completed});if(selected)await openActivity(selected)}
  return <>
    <header className="feature-hero"><div><span className="eyebrow">Partner intelligence and outreach pipeline</span><h1>Teaming Partner Discovery</h1><p>Find candidates, review profiles, record outreach, and manage follow-ups without leaving ForgeGov.</p></div></header>
    <section className="data-panel"><form className="advanced-filter-grid" onSubmit={(e)=>{e.preventDefault();void searchPartners();}}><label><span>Company / UEI / CAGE</span><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Company name"/></label><label><span>NAICS</span><input value={naics} onChange={(e)=>setNaics(e.target.value)} placeholder="811310"/></label><label><span>State</span><input value={state} onChange={(e)=>setState(e.target.value.toUpperCase())} maxLength={2} placeholder="TX"/></label><label><span>Socioeconomic status</span><input value={status} onChange={(e)=>setStatus(e.target.value)} placeholder="SDVOSB, HUBZone…"/></label><button className="primary-button"><Search size={16}/> Find partners</button></form><p className="inline-message">{message}</p></section>
    <div className="split-intelligence"><section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">DISCOVERY</span><h2>Potential partners</h2></div><small>{partners.length} matches</small></div><div className="intelligence-list">{partners.map((partner)=><article key={partner.id}><Users/><div><span>{firstText(partner.uei,partner.cage_code)}</span><Link className="entity-link" href={`/participants/vendors/profile?id=${partner.id}`}><h3>{partner.name}</h3><Eye size={14}/></Link><p>{text(partner.city,"")}{partner.city&&partner.state?", ":""}{text(partner.state,"")} · {Number(partner.award_count??0).toLocaleString()} awards · {money(partner.obligated_amount)}</p><small>{[...(partner.socioeconomic_statuses??[]),...(partner.naics_codes??[])].slice(0,8).join(" · ")||"Profile indicators unavailable"}</small></div><div className="row-actions"><Link className="secondary-button" href={`/participants/vendors/profile?id=${partner.id}`}>View profile</Link>{partner.website?<a className="icon-button" title="Company website" href={partner.website} target="_blank" rel="noreferrer"><ExternalLink size={16}/></a>:null}<button className="primary-button" onClick={()=>void createLead(partner)}>Add lead</button></div></article>)}</div></section><section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">WORKSPACE</span><h2>Teaming leads</h2></div><small>{requests.length} records</small></div><div className="intelligence-list">{requests.map((request)=><article key={request.id}><Target/><div><span>{request.role}</span><Link className="entity-link" href={`/participants/vendors/profile?name=${encodeURIComponent(request.company_name)}`}><h3>{request.company_name}</h3><Eye size={14}/></Link><p>{request.capabilities||"No capability notes yet."}</p><small>{request.due_date?`Follow up ${new Date(request.due_date).toLocaleString()}`:"No follow-up date set"}</small></div><div className="row-actions"><select aria-label={`Status for ${request.company_name}`} value={request.status} onChange={(e)=>void updateLead(request.id,{status:e.target.value})}><option value="draft">Draft</option><option value="open">Open</option><option value="responded">Responded</option><option value="accepted">Accepted</option><option value="declined">Declined</option><option value="closed">Archived</option></select><button className="secondary-button" onClick={()=>void openActivity(request)}><MessageSquare size={15}/> Activity</button><a className="icon-button" title="Draft outreach email" href={`mailto:?subject=${encodeURIComponent(`Teaming opportunity with ForgeGov user`)}&body=${encodeURIComponent(`Hello,\n\nWe are interested in discussing a potential teaming opportunity with ${request.company_name}.`)}`}><Mail size={16}/></a><button className="icon-button danger-button" title="Delete teaming lead" onClick={()=>void removeLead(request)}><Trash2 size={16}/></button></div></article>)}</div></section></div>
    {selected&&<div className="document-viewer-backdrop"><div className="record-modal teaming-activity-modal"><header><div><span className="eyebrow">Partner CRM</span><h2>{selected.company_name}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}><X size={20}/></button></header><div className="teaming-contact-grid"><label><span>Point of contact</span><input value={selected.point_of_contact??""} onChange={e=>setSelected({...selected,point_of_contact:e.target.value})} onBlur={()=>void updateLead(selected.id,{point_of_contact:selected.point_of_contact})}/></label><label><span>Next follow-up</span><input type="datetime-local" value={selected.due_date?.slice(0,16)??""} onChange={e=>{setSelected({...selected,due_date:e.target.value});void updateLead(selected.id,{due_date:e.target.value||null})}}/></label></div><section className="activity-composer"><select value={activityType} onChange={e=>setActivityType(e.target.value)}><option value="note">Note</option><option value="email">Email</option><option value="call">Call</option><option value="meeting">Meeting</option><option value="follow_up">Follow-up</option></select><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/><textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="Outcome, commitments, and next steps…"/><label><span>Follow-up date</span><input type="datetime-local" value={followUp} onChange={e=>setFollowUp(e.target.value)}/></label><button className="primary-button" onClick={()=>void addActivity()}>Save activity</button></section><div className="activity-list">{activities.map(row=><article key={row.id} className={row.completed?"complete":""}>{row.activity_type==="call"?<Phone/>:row.activity_type==="follow_up"?<CalendarClock/>:<MessageSquare/>}<div><strong>{row.subject}</strong><p>{row.details||"No additional details."}</p><small>{new Date(row.occurred_at).toLocaleString()}{row.follow_up_at?` · Follow up ${new Date(row.follow_up_at).toLocaleString()}`:""}</small></div><button className="secondary-button" onClick={()=>void toggleActivity(row)}>{row.completed?"Reopen":"Complete"}</button></article>)}</div></div></div>}
  </>;
}

export function ProfileWorkspace({kind}:{kind:"agency"|"vendor"}){
  const[query,setQuery]=useState("");const[rows,setRows]=useState<Row[]>([]);const[message,setMessage]=useState(`Search ${kind} intelligence.`);
  const load=useCallback(async()=>{try{const data=await apiGet<{results:Row[]}>(`/intelligence/${kind==="agency"?"agencies":"vendors"}/?q=${encodeURIComponent(query)}`);setRows(data.results??[]);setMessage(`${data.results?.length??0} profiles loaded from stored award intelligence.`);}catch(error){setMessage(error instanceof Error?error.message:"Profile search failed");}},[kind,query]);
  return <>
    <header className="feature-hero"><div><span className="eyebrow">{kind==="agency"?"Buyer intelligence":"Competitor intelligence"}</span><h1>{kind==="agency"?"Federal Agency Profiles":"Vendor & Competitor Profiles"}</h1><p>{kind==="agency"?"Analyze agency spending, active opportunities, leading vendors, and category concentration.":"Analyze award history, agency relationships, category strengths, and recent wins."}</p></div></header>
    <section className="data-panel"><form className="quick-create-form" onSubmit={(e)=>{e.preventDefault();void load();}}><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={kind==="agency"?"Department of the Navy":"Company name, UEI or CAGE"}/><button className="primary-button"><Search size={16}/> Search profiles</button></form><p className="inline-message">{message}</p></section>
    <section className="profile-grid">{rows.map((row,index)=><article className="profile-card" key={`${text(row.id)}-${index}`}><header>{kind==="agency"?<Building2/>:<Users/>}<div><span>{kind==="agency"?text(row.agency_code):firstText(row.uei, row.cage_code)}</span><h3>{kind==="vendor"?<Link className="entity-link" href={`/participants/vendors/profile?id=${text(row.id)}`}>{text(row.name)} <Eye size={14}/></Link>:<Link className="entity-link" href={`/intelligence/agency/${encodeURIComponent(text(row.name))}`}>{text(row.name)} <Eye size={14}/></Link>}</h3></div></header><div className="profile-metrics"><div><span>Awards</span><strong>{Number(row.award_count??0).toLocaleString()}</strong></div><div><span>Obligated</span><strong>{money(row.obligated_amount)}</strong></div>{kind==="agency"?<div><span>Active opportunities</span><strong>{Number(row.active_opportunities??0).toLocaleString()}</strong></div>:null}</div><h4>{kind==="agency"?"Top vendors":"Top agencies"}</h4><ul>{((kind==="agency"?row.top_vendors:row.top_agencies) as Row[]|undefined)?.map((item,i)=><li key={i}><span>{text(item.recipient_name??item.awarding_agency)}</span><b>{money(item.obligated)}</b></li>)}</ul></article>)}</section>
  </>;
}

export function MarketAnalyticsWorkspace({categoryType}:{categoryType:"naics"|"psc"}){
  const[rows,setRows]=useState<Row[]>([]);const[message,setMessage]=useState("Loading stored market intelligence…");
  const load=useCallback(async()=>{try{const data=await apiGet<{results:Row[]}>(`/intelligence/categories/?type=${categoryType}`);setRows(data.results??[]);setMessage(`${data.results?.length??0} ${categoryType.toUpperCase()} markets analyzed.`);}catch(error){setMessage(error instanceof Error?error.message:"Market analytics failed");}},[categoryType]);
  useInitialLoad(load);
  return <>
    <header className="feature-hero"><div><span className="eyebrow">Category intelligence</span><h1>{categoryType.toUpperCase()} Market Analytics</h1><p>Compare obligated dollars, award volume, vendor concentration, agency demand, and active opportunity counts.</p></div><button className="secondary-button" onClick={()=>void load()}><RefreshCw size={16}/> Refresh</button></header><p className="inline-message">{message}</p>
    <section className="data-panel"><div className="market-table"><div className="market-row market-head"><b>Code</b><b>Obligated</b><b>Awards</b><b>Vendors</b><b>Agencies</b><b>Opportunities</b></div>{rows.map((row,index)=><div className="market-row" key={`${text(row.code)}-${index}`}><strong>{text(row.code)}</strong><span>{money(row.obligated)}</span><span>{Number(row.award_count??0).toLocaleString()}</span><span>{Number(row.vendor_count??0).toLocaleString()}</span><span>{Number(row.agency_count??0).toLocaleString()}</span><span>{Number(row.opportunity_count??0).toLocaleString()}</span></div>)}</div></section>
  </>;
}

type AlertRow={id:number;title:string;summary?:string;source_id?:string;source_url?:string;created_at:string;read:boolean;dismissed:boolean;alert_type:string};
export function AlertsWorkspace(){
  const[rows,setRows]=useState<AlertRow[]>([]);const[message,setMessage]=useState("Loading opportunity alerts…");
  const load=useCallback(async()=>{try{const data=await apiGet<AlertRow[]|{results:AlertRow[]}>("/alerts/?dismissed=false&page_size=250");const alerts=normalizeList<AlertRow>(data);setRows(alerts);setMessage(`${alerts.filter((row)=>!row.read).length} unread alerts.`);}catch(error){setMessage(error instanceof Error?error.message:"Alerts could not be loaded");}},[]);
  const internalHref=(row:AlertRow)=>{const sourceId=String(row.source_id??"");if(sourceId.startsWith("grants.gov:")){const id=sourceId.replace(/^grants\.gov:/,"");return id?`/opportunities/federal-grants/${encodeURIComponent(id)}`:"/opportunities/federal-grants"}return sourceId?`/opportunities/federal-contracts/${encodeURIComponent(sourceId)}`:""};
  useInitialLoad(load);
  async function evaluate(){setMessage("Evaluating saved searches against live SAM.gov and Grants.gov data…");try{const result=await apiPost<{alerts_created:number;saved_searches_evaluated:number}>("/workflow/saved-searches/evaluate/",{});setMessage(`${result.saved_searches_evaluated} saved searches evaluated; ${result.alerts_created} new alerts created.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Alert evaluation failed");}}
  async function patch(id:number,payload:Partial<AlertRow>){await apiPatch(`/alerts/${id}/`,payload);await load();}
  return <>
    <header className="feature-hero"><div><span className="eyebrow">Automated opportunity monitoring</span><h1>Alerts</h1><p>Run saved searches against live SAM.gov data and review new matches in one inbox.</p></div><button className="primary-button" onClick={()=>void evaluate()}><RefreshCw size={16}/> Evaluate now</button></header><p className="inline-message">{message}</p>
    <section className="data-panel"><div className="intelligence-list">{rows.map(row=><article className={row.read?"alert-read":""} key={row.id}><Bell/><div><span>{row.alert_type.replaceAll("_"," ")}</span><h3>{row.title}</h3><p>{row.summary||"Matched a saved search."}</p><small>{new Date(row.created_at).toLocaleString()}</small></div><div className="alert-actions">{internalHref(row)?<Link className="secondary-button" href={internalHref(row)}>Open workspace</Link>:null}{row.source_url?<a className="icon-button" href={row.source_url} target="_blank" rel="noreferrer" aria-label="Open official source"><ExternalLink size={17}/></a>:null}<button className="secondary-button" onClick={()=>void patch(row.id,{read:!row.read})}>{row.read?"Unread":"Read"}</button><button className="secondary-button" onClick={()=>void patch(row.id,{dismissed:true})}>Dismiss</button></div></article>)}</div></section>
  </>;
}
