"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {AlertTriangle,CheckCircle2,GitCompare,LoaderCircle,MessageSquare,RefreshCw,ShieldCheck,Sparkles} from "lucide-react";
import {apiGet,apiPatch,apiPost} from "@/lib/api";
import {MicrosoftActions} from "@/components/microsoft-actions";
import {ProposalExecution} from "@/components/proposal-execution";

type Score={criterion:string;score:number;explanation:string;confidence:number};
type Run={id:number;review_type:string;status:string;summary:string;scorecard:Score[];provider:string;model:string;error:string;created_at:string;completed_at:string|null};
type Evidence={id:number;source_label:string;locator:string;quotation:string};
type Comment={id:number;body:string;author:string;resolution_event:boolean;created_at:string};
type Finding={id:number;severity:string;title:string;detail:string;recommendation:string;confidence:number;status:string;section:string;resolution_response:string;evidence:Evidence[];comments:Comment[]};
type Revision={id:number;revision:number;created_at:string;change_summary:string};
type Section={id:number;title:string;volume:string;status:string;revision_count:number;revisions:Revision[]};
type Payload={runs:Run[];findings:Finding[];sections:Section[];review_types:{value:string;label:string}[];permissions:{can_approve:boolean};warning:string;review_run_id?:number;created?:boolean};

export function ProposalReviewCenter({noticeId}:{noticeId:string}){
 const[data,setData]=useState<Payload|null>(null);const[message,setMessage]=useState("");const[busy,setBusy]=useState("");const[reviewType,setReviewType]=useState("compliance");const[comment,setComment]=useState<Record<number,string>>({});const[resolution,setResolution]=useState<Record<number,string>>({});const[sectionId,setSectionId]=useState<number|null>(null);const[older,setOlder]=useState<number|null>(null);const[newer,setNewer]=useState<number|null>(null);const[diff,setDiff]=useState<string[]>([]);
 const base=`/ai/opportunities/${encodeURIComponent(noticeId)}`;
 const load=useCallback(async()=>{try{setData(await apiGet<Payload>(`${base}/proposal-review-center/`));setMessage("")}catch(e){setMessage(e instanceof Error?e.message:"Proposal Review Center could not be loaded")}},[base]);
 useEffect(()=>{let active=true;apiGet<Payload>(`${base}/proposal-review-center/`).then(result=>{if(active)setData(result)}).catch(e=>{if(active)setMessage(e instanceof Error?e.message:"Proposal Review Center could not be loaded")});return()=>{active=false}},[base]);
 const selected=useMemo(()=>data?.sections.find(row=>row.id===sectionId),[data,sectionId]);
 async function startReview(){setBusy("review");try{const result=await apiPost<Payload>(`${base}/proposal-review-center/`,{review_type:reviewType});setData(result);setMessage(result.created?"Review queued. Refresh to see the completed scorecard and findings.":"An identical review is already queued or running.")}catch(e){setMessage(e instanceof Error?e.message:"Review could not be started")}finally{setBusy("")}}
 async function addComment(id:number){if(!comment[id]?.trim())return;setBusy(`comment-${id}`);try{await apiPost(`${base}/proposal-findings/${id}/comments/`,{body:comment[id]});setComment({...comment,[id]:""});await load()}catch(e){setMessage(e instanceof Error?e.message:"Comment could not be added")}finally{setBusy("")}}
 async function resolveFinding(id:number,status:"resolved"|"accepted"){if(!resolution[id]?.trim())return;setBusy(`finding-${id}`);try{await apiPatch(`${base}/proposal-findings/${id}/`,{status,resolution_response:resolution[id]});setResolution({...resolution,[id]:""});await load()}catch(e){setMessage(e instanceof Error?e.message:"Finding could not be resolved")}finally{setBusy("")}}
 async function compare(){if(!selected||!older||!newer)return;setBusy("compare");try{const result=await apiGet<{diff:string[]}>(`${base}/proposal-sections/${selected.id}/compare/?older=${older}&newer=${newer}`);setDiff(result.diff??[])}catch(e){setMessage(e instanceof Error?e.message:"Revisions could not be compared")}finally{setBusy("")}}
 if(!data)return <section className="data-panel proposal-review-loading">{message?<><AlertTriangle/><strong>Review Center unavailable</strong><p>{message}</p><button className="secondary-button" onClick={()=>void load()}>Retry</button></>:<><LoaderCircle className="spin"/><strong>Loading Proposal Review Center</strong></>}</section>;
 const latest=data.runs[0];const open=data.findings.filter(row=>row.status==="open");
 return <section className="proposal-review-center">
  <header className="proposal-review-hero"><div><span className="eyebrow">PROPOSAL INTELLIGENCE + REVIEW AUTOMATION</span><h2>Proposal Review Center</h2><p>Run evidence-grounded compliance and evaluator reviews, resolve findings, and preserve every decision.</p></div><div className="button-row"><MicrosoftActions title="ForgeGov proposal review" summary={latest?.summary||"Proposal review coordination"}/><button className="secondary-button" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button></div></header>
  {message&&<div className="system-banner">{message}</div>}
  <section className="data-panel proposal-review-launch"><div><ShieldCheck/><div><strong>Start a controlled review</strong><p>The review uses the current solicitation evidence and stored proposal revisions. Duplicate runs against the same baseline are blocked.</p></div></div><select aria-label="Review type" value={reviewType} onChange={e=>setReviewType(e.target.value)}>{data.review_types.map(row=><option key={row.value} value={row.value}>{row.label}</option>)}</select><button className="primary-button" disabled={busy==="review"} onClick={()=>void startReview()}>{busy==="review"?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>}Run review</button></section>
  <div className="proposal-review-kpis"><article><span>Review runs</span><strong>{data.runs.length}</strong><small>Preserved history</small></article><article><span>Open findings</span><strong>{open.length}</strong><small>{open.filter(row=>row.severity==="critical").length} critical</small></article><article><span>Latest status</span><strong>{latest?.status.replaceAll("_"," ")||"Not run"}</strong><small>{latest?.review_type.replaceAll("_"," ")||"Start a review"}</small></article><article><span>Average score</span><strong>{latest?.scorecard.length?Math.round(latest.scorecard.reduce((sum,row)=>sum+Number(row.score||0),0)/latest.scorecard.length):"—"}</strong><small>Advisory, evidence-dependent</small></article></div>
  {latest&&<section className="data-panel proposal-scorecard"><div className="panel-title-row"><div><span className="eyebrow">LATEST REVIEW</span><h3>{latest.review_type.replaceAll("_"," ")}</h3><p>{latest.summary||latest.error||"Review is queued or running."}</p></div><span className={`review-run-status ${latest.status}`}>{latest.status}</span></div><div className="proposal-score-grid">{latest.scorecard.map(row=><article key={row.criterion}><span>{row.criterion.replaceAll("_"," ")}</span><strong>{row.score}/100</strong><p>{row.explanation}</p><small>{row.confidence}% confidence</small></article>)}</div></section>}
  <section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">FINDINGS</span><h3>Reviewer findings and resolution</h3></div><small>{open.length} open</small></div><div className="proposal-review-findings">{data.findings.map(row=><article key={row.id} className={`finding-${row.severity}`}><header><span>{row.severity}</span><strong>{row.title}</strong><small>{row.confidence}% confidence · {row.status}</small></header><p>{row.detail}</p>{row.section&&<small>Section: {row.section}</small>}{row.recommendation&&<div className="finding-recommendation"><b>Recommended correction</b><p>{row.recommendation}</p></div>}{row.evidence.map(item=><blockquote key={item.id}><b>{item.source_label}{item.locator?` · ${item.locator}`:""}</b><p>{item.quotation||"Human validation required; no source quotation supplied."}</p></blockquote>)}<div className="finding-comments">{row.comments.map(item=><p key={item.id}><b>{item.author||"Former user"}</b> {item.body}<small>{new Date(item.created_at).toLocaleString()}</small></p>)}</div>{row.status==="open"&&<><div className="finding-comment-form"><input aria-label={`Comment on ${row.title}`} value={comment[row.id]??""} onChange={e=>setComment({...comment,[row.id]:e.target.value})} placeholder="Add reviewer comment"/><button className="secondary-button" onClick={()=>void addComment(row.id)}><MessageSquare size={14}/>Comment</button></div><div className="finding-resolution-form"><textarea aria-label={`Resolution for ${row.title}`} value={resolution[row.id]??""} onChange={e=>setResolution({...resolution,[row.id]:e.target.value})} placeholder="Describe the correction or accepted-risk justification"/><button className="primary-button" onClick={()=>void resolveFinding(row.id,"resolved")}><CheckCircle2 size={14}/>Resolve</button>{data.permissions.can_approve&&<button className="secondary-button" onClick={()=>void resolveFinding(row.id,"accepted")}>Accept risk</button>}</div></>}</article>)}{!data.findings.length&&<p>No review findings have been recorded.</p>}</div></section>
  <section className="data-panel proposal-revision-compare"><div className="panel-title-row"><div><span className="eyebrow">REVISION CONTROL</span><h3>Compare proposal revisions</h3></div><GitCompare/></div><div className="revision-compare-controls"><select aria-label="Proposal section" value={sectionId??""} onChange={e=>{setSectionId(Number(e.target.value)||null);setOlder(null);setNewer(null);setDiff([])}}><option value="">Select section</option>{data.sections.map(row=><option key={row.id} value={row.id}>{row.volume} · {row.title}</option>)}</select><select aria-label="Older revision" value={older??""} onChange={e=>setOlder(Number(e.target.value)||null)}><option value="">Older revision</option>{selected?.revisions.map(row=><option key={row.id} value={row.id}>Revision {row.revision}</option>)}</select><select aria-label="Newer revision" value={newer??""} onChange={e=>setNewer(Number(e.target.value)||null)}><option value="">Newer revision</option>{selected?.revisions.map(row=><option key={row.id} value={row.id}>Revision {row.revision}</option>)}</select><button className="secondary-button" disabled={!older||!newer||busy==="compare"} onClick={()=>void compare()}>Compare</button></div>{diff.length?<pre className="proposal-diff">{diff.join("\n")}</pre>:<p>Select two revisions from the same section to inspect exact additions and removals.</p>}</section>
  <ProposalExecution noticeId={noticeId}/><p className="proposal-warning">{data.warning}</p>
 </section>
}
