"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Award, BellRing, Bot, Building2, Database, FileSearch, FolderKanban, Handshake, Search, ShieldCheck, Sparkles, Target, Users } from "lucide-react";
import { authFetch } from "@/lib/api";

type RegistrationConfig={mode:string;public_registration:boolean};

export function PublicLanding(){
  const [registration,setRegistration]=useState<RegistrationConfig>({mode:"private_beta",public_registration:false});
  useEffect(()=>{authFetch<RegistrationConfig>("/auth/registration-config/").then(setRegistration).catch(()=>{});},[]);
  return <main className="public-landing">
    <nav className="landing-nav"><Link href="/" className="landing-brand"><span className="forge-logo"><span>F</span>G</span><span><b>FORGE</b>GOV<small>GovCon Intelligence</small></span></Link><div><a href="#platform">Platform</a><a href="#workflow">Workflow</a><Link href="/sign-in">Sign in</Link><Link className="landing-nav-cta" href="/register">{registration.public_registration?"Start test access":"Request access"}</Link></div></nav>
    <section className="landing-hero"><div className="landing-hero-copy"><span className="landing-eyebrow"><ShieldCheck size={15}/> Government contracting intelligence + capture</span><h1>Find the work. Understand the market. Run the capture.</h1><p>ForgeGov brings live opportunity discovery, award intelligence, teaming, Project Rooms, pricing, proposal execution, alerts, and ForgeAI into one secure operating workspace.</p><div className="landing-cta-row"><Link className="landing-primary" href="/register">{registration.public_registration?"Create a test account":"Request private-beta access"}<ArrowRight size={17}/></Link><Link className="landing-secondary" href="/sign-in">Sign in</Link></div><div className="landing-trust"><span><Database/>Live federal data</span><span><ShieldCheck/>Tenant-secure workspaces</span><span><Sparkles/>AI-assisted capture</span></div></div><div className="landing-hero-panel"><div className="landing-screen-head"><span><i/> ForgeGov command center</span><small>Live workspace</small></div><div className="landing-screen-grid"><div><Search/><b>Opportunity discovery</b><small>SAM.gov, Grants.gov, forecasts, vehicles, SUBNet</small></div><div><Award/><b>Award intelligence</b><small>Incumbents, recipients, agencies, obligations</small></div><div><Target/><b>Capture pipeline</b><small>Qualify, assign, decide, and advance pursuits</small></div><div><FolderKanban/><b>Project Rooms</b><small>Secure internal and partner-company collaboration</small></div></div></div></section>
    <section id="platform" className="landing-section"><div className="landing-section-head"><span>ONE OPERATING PICTURE</span><h2>Built for the full government-contracting workflow.</h2><p>Move from public-market intelligence to a controlled pursuit workspace without losing the context your team needs.</p></div><div className="landing-feature-grid">{[[FileSearch,"Live opportunity intelligence","Search federal contracts, grants, forecasts, vehicles, and subcontracting sources."],[Building2,"Agency & vendor intelligence","Understand buyers, incumbents, competitors, partners, and historical awards."],[Handshake,"Teaming & network","Find partners, connect companies, and collaborate through controlled Project Rooms."],[BellRing,"Saved searches & alerts","Track matching opportunities, activity, deadlines, and source changes."],[Bot,"ForgeAI capture copilot","Summarize solicitations, ask document questions, build capture briefs, and surface risks."],[Users,"Enterprise controls","Role-based permissions, MFA policies, audit history, partner expiration, and platform governance."]].map(([Icon,title,text])=>{const C=Icon as typeof FileSearch;return <article key={String(title)}><C/><h3>{String(title)}</h3><p>{String(text)}</p></article>})}</div></section>
    <section id="workflow" className="landing-workflow"><div><span>DISCOVER</span><b>Search live government data</b></div><ArrowRight/><div><span>QUALIFY</span><b>Build the capture picture</b></div><ArrowRight/><div><span>COLLABORATE</span><b>Run secure Project Rooms</b></div><ArrowRight/><div><span>EXECUTE</span><b>Price, propose, and submit</b></div></section>
    <section className="landing-beta"><div><span>{registration.public_registration?"TEST REGISTRATION OPEN":"PRIVATE BETA"}</span><h2>{registration.public_registration?"ForgeGov test access is open.":"ForgeGov is onboarding private-beta companies."}</h2><p>{registration.public_registration?"Create an account, verify your email, and start testing the complete ForgeGov workflow.":"Request access to test ForgeGov with your company and help shape the platform before wider release."}</p></div><Link href="/register">{registration.public_registration?"Create account":"Request access"}<ArrowRight size={17}/></Link></section>
    <footer className="landing-footer"><span>© 2026 ForgeGov</span><div><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/sign-in">Sign in</Link></div></footer>
  </main>;
}
