"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, BadgeDollarSign, CheckCircle2, Circle, ExternalLink, FileText, History, ListChecks, LoaderCircle, Mail, NotebookPen, Save, Sparkles, Target, TriangleAlert, Users, X } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { apiGet, apiPatch, apiPost } from "@/lib/api";

type GrantOption={code?:string;label?:string};
type GrantContact={name?:string;email?:string;phone?:string;description?:string};
type DocumentRow={name:string;url:string;description?:string;preview_available?:boolean};
type Detail={opportunity:Record<string,unknown>;description:string;documents:DocumentRow[];source_url:string;contacts?:GrantContact[];eligibilities?:GrantOption[];funding_instruments?:GrantOption[];funding_categories?:GrantOption[];alns?:GrantOption[];award_ceiling?:unknown;award_floor?:unknown;cost_sharing?:unknown};
type ComplianceItem={id:string;label:string;complete:boolean;source?:string};
type AiSource={label:string;type:string;title:string;url?:string};
type Workspace={id:number;notes:string;capture_summary:string;risks:string[];compliance_items:ComplianceItem[];decision:string;updated_at:string};

function value(row:Record<string,unknown>,key:string){const item=row[key];return item===null||item===undefined||item===""?"—":String(item)}
function previewable(document:DocumentRow){return document.preview_available||/\.(pdf|txt|html?)(\?|$)/i.test(document.url)}
function optionText(item:GrantOption){return [item.code,item.label].filter(Boolean).join(" — ")||"—"}
function StructuredAnswer({content}:{content:string}){const blocks=content.split(/\n{2,}/).map(v=>v.trim()).filter(Boolean);return <div className="structured-ai-answer">{blocks.map((block,index)=>{const lines=block.split("\n").map(v=>v.trim()).filter(Boolean);const first=lines[0]??"";const heading=/^#{1,6}\s/.test(first)||/^\*\*.+\*\*:?$/.test(first);const title=first.replace(/^#{1,6}\s*/,"").replace(/^\*\*(.+)\*\*:?$/,"$1").replace(/:$/,"");const body=heading?lines.slice(1):lines;return <section className="ai-insight-card" key={index}>{heading&&<h3>{title}</h3>}{body.map((line,i)=>/^[-•*]\s+/.test(line)?<div className="ai-bullet" key={i}><span/><p>{line.replace(/^[-•*]\s+/,"")}</p></div>:<p key={i}>{line}</p>)}</section>})}</div>}

export default function FederalGrantDetailPage(){
 const params=useParams<{opportunityId:string}>();const opportunityId=decodeURIComponent(params.opportunityId);const sourceId=`grants.gov:${opportunityId}`;
 const[data,setData]=useState<Detail|null>(null);const[message,setMessage]=useState("Loading Grants.gov opportunity details…");const[adding,setAdding]=useState(false);const[viewer,setViewer]=useState<DocumentRow|null>(null);
 const[activeTab,setActiveTab]=useState<"overview"|"compliance"|"notes"|"timeline">("overview");const[workspace,setWorkspace]=useState<Workspace|null>(null);const[workspaceMessage,setWorkspaceMessage]=useState("");const[saving,setSaving]=useState(false);
 const[question,setQuestion]=useState("");const[answer,setAnswer]=useState("");const[aiSources,setAiSources]=useState<AiSource[]>([]);const[asking,setAsking]=useState(false);
 const loadWorkspace=useCallback(async()=>{try{setWorkspace(await apiGet<Workspace>(`/workflow/opportunity-workspaces/${encodeURIComponent(sourceId)}/`));setWorkspaceMessage("")}catch{setWorkspace(null)}},[sourceId]);
 const load=useCallback(async()=>{try{const result=await apiGet<Detail>(`/live/grants/opportunities/${encodeURIComponent(opportunityId)}/`);setData(result);setMessage(`${result.documents?.length??0} grant documents and ${result.contacts?.length??0} agency contacts loaded.`);void loadWorkspace()}catch(error){setMessage(error instanceof Error?error.message:"Grant details could not be loaded")}},[opportunityId,loadWorkspace]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function addToPipeline(){setAdding(true);try{await apiPost("/workflow/opportunity-to-pipeline/",{source_id:sourceId,stage:"reviewing"});setMessage("Grant added to the capture pipeline.");await loadWorkspace()}catch(error){setMessage(error instanceof Error?error.message:"Grant could not be added")}finally{setAdding(false)}}
 async function saveWorkspace(next:Partial<Workspace>={}){if(!workspace)return;setSaving(true);try{const result=await apiPatch<Workspace>(`/workflow/opportunity-workspaces/${encodeURIComponent(sourceId)}/`,{notes:next.notes??workspace.notes,capture_summary:next.capture_summary??workspace.capture_summary,risks:next.risks??workspace.risks,compliance_items:next.compliance_items??workspace.compliance_items,decision:next.decision??workspace.decision});setWorkspace(result);setWorkspaceMessage("Grant workspace saved.")}catch(error){setWorkspaceMessage(error instanceof Error?error.message:"Workspace could not be saved")}finally{setSaving(false)}}
 function starterChecklist():ComplianceItem[]{if(!data)return[];const o=data.opportunity;return[{id:"eligibility",label:"Confirm applicant eligibility and organization type",complete:false,source:"Grants.gov eligibility"},{id:"deadline",label:`Confirm application deadline: ${value(o,"closeDate")}`,complete:false,source:"Grants.gov"},{id:"registration",label:"Verify SAM.gov registration, UEI, and Grants.gov workspace access",complete:false,source:"Application readiness"},{id:"funding",label:"Validate award range, cost sharing, and allowable costs",complete:false,source:"Funding profile"},{id:"narrative",label:"Extract required narratives, forms, attachments, and page limits",complete:false,source:"Grant documents"},{id:"evaluation",label:"Identify merit-review criteria and scoring priorities",complete:false,source:"Grant documents"}]}
 async function ask(event?:FormEvent,preset?:string){event?.preventDefault();const prompt=preset??question;if(!prompt.trim()||!data)return;setQuestion(prompt);setAsking(true);setAnswer("");setAiSources([]);const o=data.opportunity;const context=`Grant: ${value(o,"title")}\nOpportunity number: ${value(o,"number")}\nAgency: ${value(o,"agencyName")}\nPosted: ${value(o,"openDate")}\nDeadline: ${value(o,"closeDate")}\nAward ceiling: ${String(data.award_ceiling??"Not provided")}\nAward floor: ${String(data.award_floor??"Not provided")}\nEligibility: ${(data.eligibilities??[]).map(optionText).join("; ")}\nALNs: ${(data.alns??[]).map(optionText).join("; ")}\nDescription: ${data.description.slice(0,14000)}\nDocuments: ${data.documents.map(d=>d.name).join(", ")}`;try{const result=await apiPost<{answer:string;sources?:AiSource[]}>("/ai/chat/",{message:`Use this federal grant context and available live web research. Separate verified facts, analysis, risks, and recommended next actions. Do not invent missing requirements.\n\n${context}\n\nQuestion: ${prompt}`,history:[]});setAnswer(result.answer);setAiSources(result.sources??[])}catch(error){setAnswer(error instanceof Error?error.message:"ForgeGov AI could not answer")}finally{setAsking(false)}}
 const opportunity=useMemo(()=>data?.opportunity??{},[data]);const timeline=useMemo(()=>data?[{label:"Posted",date:value(opportunity,"openDate")},{label:"Application deadline",date:value(opportunity,"closeDate")}].filter(row=>row.date!=="—"):[],[data,opportunity]);const completed=workspace?.compliance_items.filter(item=>item.complete).length??0;const total=workspace?.compliance_items.length??0;
 return <><header className="feature-hero opportunity-detail-hero grant-detail-hero"><div><Link className="detail-back" href="/opportunities/federal-grants"><ArrowLeft size={16}/> Back to grants</Link><span className="eyebrow">GRANTS.GOV APPLICATION WORKSPACE</span><h1>{value(opportunity,"title")}</h1><p><Link className="entity-link hero-entity-link" href={`/intelligence/agency/${encodeURIComponent(value(opportunity,"agencyName"))}`}>{value(opportunity,"agencyName")} ↗</Link></p></div><div className="detail-actions">{data?.source_url&&<a className="secondary-button" href={data.source_url} target="_blank" rel="noreferrer">Official grant <ExternalLink size={16}/></a>}<button className="primary-button" onClick={()=>void addToPipeline()} disabled={adding}><Target size={16}/>{adding?"Adding…":"Add to pipeline"}</button></div></header><p className="inline-message">{message}</p>
 {!data?<div className="table-state"><LoaderCircle className="spin"/><strong>Loading grant workspace</strong></div>:<><section className="insight-strip detail-facts"><div><span>Opportunity number</span><strong>{value(opportunity,"number")}</strong></div><div><span>Status</span><strong>{value(opportunity,"oppStatus")}</strong></div><div><span>Award ceiling</span><strong>{String(data.award_ceiling??"—")}</strong></div><div><span>Deadline</span><strong>{value(opportunity,"closeDate")}</strong></div></section>
 <nav className="workspace-tabs"><button className={activeTab==="overview"?"active":""} onClick={()=>setActiveTab("overview")}><FileText size={16}/> Overview</button><button className={activeTab==="compliance"?"active":""} onClick={()=>setActiveTab("compliance")}><ListChecks size={16}/> Compliance {total?`${completed}/${total}`:""}</button><button className={activeTab==="notes"?"active":""} onClick={()=>setActiveTab("notes")}><NotebookPen size={16}/> Capture notes</button><button className={activeTab==="timeline"?"active":""} onClick={()=>setActiveTab("timeline")}><History size={16}/> Timeline</button></nav>{workspaceMessage&&<p className="inline-message">{workspaceMessage}</p>}
 {activeTab==="overview"&&<><div className="split-intelligence"><section className="data-panel opportunity-description"><div className="panel-title-row"><div><span className="eyebrow">PROGRAM SYNOPSIS</span><h2>Grant description</h2></div></div><div className="rich-description">{data.description||"No public synopsis was returned."}</div></section><section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">APPLICATION PACKAGE</span><h2>Documents</h2></div><small>{data.documents.length} files</small></div><div className="document-list">{data.documents.length?data.documents.map((document,index)=><button key={`${document.url}-${index}`} onClick={()=>setViewer(document)}><FileText/><span><strong>{document.name}</strong><small>{document.description||"Review grant document"}</small></span><ExternalLink size={16}/></button>):<div className="table-state"><FileText/><strong>No separate public attachments returned</strong><p>Use the official grant page for the complete application package.</p></div>}</div></section></div>
 <section className="grant-intelligence-grid"><article><BadgeDollarSign/><div><span>Funding profile</span><strong>{String(data.award_floor??"—")} to {String(data.award_ceiling??"—")}</strong><p>Cost sharing: {String(data.cost_sharing??"Not stated")}</p></div></article><article><Users/><div><span>Eligibility</span><strong>{data.eligibilities?.length??0} applicant categories</strong><p>{(data.eligibilities??[]).slice(0,4).map(optionText).join("; ")||"Not provided"}</p></div></article><article><ListChecks/><div><span>Assistance listings</span><strong>{(data.alns??[]).map(item=>item.code).filter(Boolean).join(", ")||"—"}</strong><p>{(data.funding_instruments??[]).map(optionText).join("; ")||"Funding instrument not provided"}</p></div></article><article><Mail/><div><span>Agency contacts</span><strong>{data.contacts?.length??0} contacts</strong><p>{data.contacts?.map(c=>[c.name,c.email].filter(Boolean).join(" · ")).join("; ")||"Not provided"}</p></div></article></section>
 <section className="data-panel context-ai"><div className="panel-title-row"><div><span className="eyebrow">CONTEXTUAL AI</span><h2>Analyze this grant</h2></div><Sparkles/></div><div className="ai-preset-row"><button onClick={()=>void ask(undefined,"Create an executive summary covering purpose, funding, eligibility, deadline, and major unknowns.")}>Executive summary</button><button onClick={()=>void ask(undefined,"Extract eligibility rules, required registrations, forms, narratives, attachments, and deadlines into a compliance plan.")}>Application requirements</button><button onClick={()=>void ask(undefined,"Identify eligibility, cost-sharing, schedule, evaluation, staffing, and delivery risks. Separate facts from assumptions.")}>Find risks</button><button onClick={()=>void ask(undefined,"Recommend a grant application strategy, partner profile, win themes, and next actions based on the available evidence.")}>Application strategy</button></div><form onSubmit={ask}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about eligibility, requirements, funding, evaluation, partners, or application strategy…"/><button className="primary-button" disabled={asking||!question.trim()}>{asking?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>} {asking?"Analyzing…":"Ask AI"}</button></form>{answer&&<div className="context-ai-answer"><div className="ai-answer-header"><Sparkles size={18}/><div><strong>ForgeGov grant findings</strong><small>Facts, analysis, risks, and next actions</small></div></div><StructuredAnswer content={answer}/>{aiSources.length?<details className="ai-source-list contextual-source-list compact-source-disclosure"><summary>Sources ({aiSources.length})</summary><div className="compact-source-items">{aiSources.slice(0,12).map(source=>source.url?<a key={`${source.label}-${source.url}`} href={source.url} target="_blank" rel="noreferrer"><b>{source.label}</b>{source.title}<ExternalLink size={12}/></a>:<div key={`${source.label}-${source.title}`}><b>{source.label}</b>{source.title}</div>)}</div></details>:null}</div>}</section></>}
 {activeTab==="compliance"&&<section className="data-panel workspace-section-card"><div className="workspace-section-header"><div><span className="workspace-step">02</span><div><span className="eyebrow">APPLICATION READINESS</span><h2>Grant compliance checklist</h2><p>Track eligibility, registrations, forms, narratives, attachments, and submission requirements.</p></div></div><div className="workspace-progress"><strong>{completed}/{total}</strong><span>complete</span><div><i style={{width:`${total?Math.round(completed/total*100):0}%`}}/></div></div></div>{!workspace?<div className="table-state"><TriangleAlert/><strong>Add this grant to activate its workspace.</strong><p>Use Add to pipeline, then the compliance and capture records will persist.</p></div>:<><div className="workspace-toolbar">{!total?<button className="secondary-button" onClick={()=>{const next={...workspace,compliance_items:starterChecklist()};setWorkspace(next);void saveWorkspace(next)}}>Build starter checklist</button>:<span>{total-completed} requirements remaining</span>}<button className="primary-button" disabled={saving} onClick={()=>void saveWorkspace()}><Save size={16}/>{saving?"Saving…":"Save checklist"}</button></div><div className="compliance-list modern-compliance-list">{workspace.compliance_items.map((item,index)=><article className={item.complete?"complete":""} key={item.id||index}><button className="check-toggle" onClick={()=>setWorkspace({...workspace,compliance_items:workspace.compliance_items.map((row,i)=>i===index?{...row,complete:!row.complete}:row)})}>{item.complete?<CheckCircle2/>:<Circle/>}</button><div><strong>{item.label}</strong><small>{item.source||"Workspace item"}</small></div><button className="icon-button danger-button" onClick={()=>setWorkspace({...workspace,compliance_items:workspace.compliance_items.filter((_,i)=>i!==index)})}><X size={16}/></button></article>)}</div></>}</section>}
 {activeTab==="notes"&&<section className="workspace-capture-shell">{workspace?<><div className="capture-command-bar"><div><span className="workspace-step">03</span><div><span className="eyebrow">APPLICATION STRATEGY</span><h2>Build the grant win plan</h2><p>Organize the decision, narrative strategy, partners, assumptions, and risks.</p></div></div><label className="decision-control"><span>Application decision</span><select value={workspace.decision} onChange={e=>setWorkspace({...workspace,decision:e.target.value})}><option value="undecided">Undecided</option><option value="bid">Apply</option><option value="no_bid">Do not apply</option><option value="hold">Hold</option></select></label></div><div className="capture-card-grid"><label className="capture-editor primary-editor"><span><b>Application strategy</b><small>Program fit, outcomes, win themes, evidence, and partner approach</small></span><textarea value={workspace.capture_summary} onChange={e=>setWorkspace({...workspace,capture_summary:e.target.value})}/></label><label className="capture-editor"><span><b>Working notes</b><small>Questions, registrations, budget, partners, and narrative ideas</small></span><textarea value={workspace.notes} onChange={e=>setWorkspace({...workspace,notes:e.target.value})}/></label><label className="capture-editor risk-editor"><span><b>Risk register</b><small>Enter one eligibility, schedule, cost-share, compliance, or delivery risk per line</small></span><textarea value={workspace.risks.join("\n")} onChange={e=>setWorkspace({...workspace,risks:e.target.value.split("\n").map(v=>v.trim()).filter(Boolean)})}/></label></div><div className="workspace-save-bar"><span>Last saved {new Date(workspace.updated_at).toLocaleString()}</span><button className="primary-button" disabled={saving} onClick={()=>void saveWorkspace()}><Save size={16}/>{saving?"Saving…":"Save grant workspace"}</button></div></>:<div className="table-state"><NotebookPen/><strong>Workspace is not active yet.</strong><p>Add this grant to the pipeline to persist application notes.</p></div>}</section>}
 {activeTab==="timeline"&&<section className="data-panel workspace-section-card"><div className="workspace-section-header"><div><span className="workspace-step">04</span><div><span className="eyebrow">APPLICATION TIMELINE</span><h2>Grant milestones</h2><p>Key program dates and ForgeGov workspace activity.</p></div></div></div><div className="timeline-list modern-timeline">{timeline.map((row,index)=><article key={`${row.label}-${index}`}><span><i/></span><div><small>{index===0?"OPEN":"DEADLINE"}</small><strong>{row.label}</strong><p>{row.date}</p></div></article>)}{workspace&&<article><span><i/></span><div><small>FORGEGOV</small><strong>Workspace last updated</strong><p>{new Date(workspace.updated_at).toLocaleString()}</p></div></article>}</div></section>}</>}
 {viewer&&<div className="document-viewer-backdrop" role="dialog" aria-modal="true"><div className="document-viewer"><header><strong>{viewer.name}</strong><div><a className="secondary-button" href={viewer.url} target="_blank" rel="noreferrer">Open original <ExternalLink size={15}/></a><button className="icon-button" onClick={()=>setViewer(null)}><X/></button></div></header>{previewable(viewer)?<iframe title={viewer.name} src={viewer.url}/>:<div className="document-viewer-empty"><div><FileText size={42}/><h2>Browser preview is unavailable for this file type.</h2><p>Open the official Grants.gov file when required.</p><a className="primary-button" href={viewer.url} target="_blank" rel="noreferrer">Open original file</a></div></div>}</div></div>}
 </>;
}
