"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Bot, Building2, CalendarClock, CheckCircle2, ExternalLink, FileSearch, Landmark, Mail, MapPin, Phone, RefreshCw, Target, Users } from "lucide-react";
import { apiGet, apiPost } from "@/lib/api";
import { MicrosoftActions } from "@/components/microsoft-actions";

type AwardRow={id?:number;award_id?:string;award_number?:string;awarding_agency?:string;naics_code?:string;psc_code?:string;obligated_amount?:string|number;potential_amount?:string|number;start_date?:string;end_date?:string;match_reason?:string;classification?:string};
type Workspace={
  opportunity:{source_id:string;source:string;title:string;description:string;prime_contractor:string;solicitation_number:string;naics:string;psc:string;closing_date?:string|null;performance_start?:string;place_of_performance:string;source_url:string;active:boolean;notice_type:string;source_metadata:{source_name:string;observed_at?:string;classification:string}};
  contact:{name:string;email:string;phone:string;raw:string};
  prime:{name:string;vendor:null|{id:number;name:string;uei?:string;cage_code?:string;website?:string;city?:string;state?:string;naics_codes?:string[];socioeconomic_statuses?:string[]};award_summary:{award_count:number;obligated_amount:string|number;potential_amount:string|number;top_agencies:Array<{awarding_agency:string;awards:number;obligated:string|number}>;classification:string};recent_awards:AwardRow[]};
  parent_contract_candidates:AwardRow[];
  pipeline:{active:boolean;id?:number|null;stage:string;owner:string;next_action:string;probability_of_win:number};
  capture_links:{company_profile:string;pipeline:string;project_rooms:string};
  warnings:string[];
};
type Tab="overview"|"prime"|"capture"|"collaboration";

const money=(value:unknown)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(value??0));
const date=(value?:string|null)=>value?new Date(value).toLocaleString():"Not provided";

export default function SubcontractOpportunityPage(){
  const params=useParams<{sourceId:string}>();
  const sourceId=decodeURIComponent(params.sourceId);
  const [data,setData]=useState<Workspace|null>(null);
  const [message,setMessage]=useState("Loading subcontract opportunity intelligence…");
  const [activeTab,setActiveTab]=useState<Tab>("overview");
  const [adding,setAdding]=useState(false);
  const [question,setQuestion]=useState("Should we pursue this subcontract opportunity? What should we verify with the prime first?");
  const [answer,setAnswer]=useState("");
  const [aiBusy,setAiBusy]=useState(false);

  const load=useCallback(async()=>{try{const row=await apiGet<Workspace>(`/live/sba/subnet/${encodeURIComponent(sourceId)}/`);setData(row);setMessage("Subcontract opportunity workspace loaded from ForgeGov indexed SBA and award intelligence.")}catch(error){setMessage(error instanceof Error?error.message:"Subcontract opportunity could not be loaded")}},[sourceId]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);

  async function addToPipeline(){if(!data)return;setAdding(true);try{await apiPost("/workflow/opportunity-to-pipeline/",{source_id:data.opportunity.source_id,stage:"reviewing"});setMessage("Subcontract opportunity added to the capture pipeline.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Opportunity could not be added to the pipeline")}finally{setAdding(false)}}
  async function askAI(){if(!data||question.trim().length<2)return;setAiBusy(true);setAnswer("");try{const evidence={opportunity:data.opportunity,contact:data.contact,prime_award_summary:data.prime.award_summary,parent_contract_candidates:data.parent_contract_candidates.slice(0,5)};const row=await apiPost<{answer?:string}>("/ai/chat/",{message:`Act as a senior government-contracting subcontract capture manager. Use only the public/listing evidence below unless you explicitly label inference. Identify pursuit fit, questions for the prime, teaming/capability gaps, risks, and next actions.\n\nPUBLIC EVIDENCE:\n${JSON.stringify(evidence)}\n\nQUESTION:\n${question}`,history:[]});setAnswer(row.answer??"ForgeAI did not return an answer.")}catch(error){setAnswer(error instanceof Error?error.message:"ForgeAI could not analyze this opportunity")}finally{setAiBusy(false)}}

  const opportunity=data?.opportunity;
  const prime=data?.prime;
  const relatedAgencies=useMemo(()=>prime?.award_summary.top_agencies??[],[prime]);

  if(!data)return <main className="page-stack"><header className="feature-hero"><div><Link className="detail-back" href="/opportunities/subcontracting"><ArrowLeft size={16}/>Back to Subcontracting</Link><span className="eyebrow">SBA SUBNET WORKSPACE</span><h1>Subcontract opportunity</h1><p>{message}</p></div><RefreshCw className="spin"/></header></main>;

  return <main className="page-stack subcontract-workspace-page" data-qa="subcontract-workspace">
    <header className="feature-hero opportunity-detail-hero subcontract-detail-hero" data-qa="subcontract-detail-hero"><div><Link className="detail-back" href="/opportunities/subcontracting"><ArrowLeft size={16}/>Back to Subcontracting</Link><span className="eyebrow">{opportunity?.source_metadata.source_name||"SBA SUBNet"} · SUBCONTRACT OPPORTUNITY</span><h1>{opportunity?.title}</h1><p>{opportunity?.prime_contractor||"Prime contractor not provided"}</p></div><div className="detail-actions compact-action-group" data-qa="subcontract-detail-actions" data-qa-no-x-overflow="true"><MicrosoftActions title={opportunity?.title??"Subcontract opportunity"} summary={opportunity?.description} sourceUrl={opportunity?.source_url} deadline={opportunity?.closing_date??""} agency={opportunity?.prime_contractor} solicitationNumber={opportunity?.solicitation_number}/>{opportunity?.source_url&&<a className="secondary-button" href={opportunity.source_url} target="_blank" rel="noreferrer">Official source <ExternalLink size={15}/></a>}<button className="primary-button" disabled={adding||data.pipeline.active} onClick={()=>void addToPipeline()}><Target size={15}/>{data.pipeline.active?"In pipeline":adding?"Adding…":"Add to pipeline"}</button></div></header>
    <p className="inline-message">{message}</p>

    <section className="subcontract-command-grid" data-qa="subcontract-command-grid" data-qa-no-x-overflow="true">
      <article><span>Prime contractor</span><strong>{opportunity?.prime_contractor||"Unknown"}</strong><small>{prime?.vendor?.uei?`UEI ${prime.vendor.uei}`:"ForgeGov vendor profile matching available when public records support it."}</small></article>
      <article><span>Closing date</span><strong>{date(opportunity?.closing_date)}</strong><small>{opportunity?.active?"Listing currently indexed as active":"Listing is not currently active"}</small></article>
      <article><span>NAICS</span><strong>{opportunity?.naics||"Not provided"}</strong><small>{opportunity?.place_of_performance||"Place of performance not provided"}</small></article>
      <article><span>Prime award history</span><strong>{prime?.award_summary.award_count??0}</strong><small>{money(prime?.award_summary.obligated_amount)} historical obligations in stored public awards</small></article>
      <article><span>Capture status</span><strong>{data.pipeline.active?data.pipeline.stage.replaceAll("_"," "):"Not added"}</strong><small>{data.pipeline.active?`${data.pipeline.probability_of_win}% Pwin · ${data.pipeline.owner||"Unassigned"}`:"Add to pipeline to activate capture management."}</small></article>
    </section>

    <div className="opportunity-tab-shell subcontract-tab-shell" data-qa="subcontract-detail-tabs" data-qa-no-x-overflow="true"><div className="opportunity-tab-rail" role="tablist">{([['overview','Overview'],['prime','Prime & parent contract'],['capture','Capture intelligence'],['collaboration','Collaboration']] as const).map(([key,label])=><button key={key} className={activeTab===key?"active":""} onClick={()=>setActiveTab(key)}>{label}</button>)}</div></div>

    {activeTab==="overview"&&<div className="subcontract-detail-grid" data-qa="subcontract-detail-grid" data-qa-no-x-overflow="true"><section className="data-panel opportunity-description"><div className="panel-title-row"><div><span className="eyebrow">SCOPE</span><h2>Subcontract requirement</h2></div></div><div className="rich-description">{opportunity?.description||"The source listing did not provide a description."}</div></section><section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">OPPORTUNITY FACTS</span><h2>Key details</h2></div></div><div className="subcontract-fact-list"><div><CalendarClock/><span><b>Performance start</b>{opportunity?.performance_start||"Not provided"}</span></div><div><MapPin/><span><b>Place of performance</b>{opportunity?.place_of_performance||"Not provided"}</span></div><div><Building2/><span><b>Prime contractor</b>{opportunity?.prime_contractor||"Not provided"}</span></div><div><Target/><span><b>Reference</b>{opportunity?.solicitation_number||opportunity?.source_id}</span></div></div></section><section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">CONTACT</span><h2>Prime point of contact</h2></div></div><div className="subcontract-contact-card"><Users/><div><strong>{data.contact.name||"Contact name not parsed"}</strong>{data.contact.email?<a href={`mailto:${data.contact.email}`}><Mail size={14}/>{data.contact.email}</a>:null}{data.contact.phone?<a href={`tel:${data.contact.phone}`}><Phone size={14}/>{data.contact.phone}</a>:null}<small>{data.contact.raw||"No contact information was included in the source listing."}</small></div></div></section><section className="data-panel source-provenance-panel"><div className="panel-title-row"><div><span className="eyebrow">PROVENANCE</span><h2>Source confidence</h2></div></div><div className="source-evidence-item"><CheckCircle2/><div><strong>Official subcontract listing</strong><p>ForgeGov preserves the SBA source URL and separates source facts from historical award inferences.</p><small>Observed {date(String(opportunity?.source_metadata.observed_at||""))}</small></div></div>{data.warnings.map((warning,index)=><p className="panel-note" key={index}>{warning}</p>)}</section></div>}

    {activeTab==="prime"&&<div className="subcontract-detail-grid" data-qa="subcontract-detail-grid" data-qa-no-x-overflow="true"><section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">PRIME INTELLIGENCE</span><h2>{prime?.name||"Prime contractor"}</h2></div>{data.capture_links.company_profile&&<Link className="secondary-button" href={data.capture_links.company_profile}>Open company profile</Link>}</div><div className="profile-metrics"><div><span>Stored awards</span><strong>{prime?.award_summary.award_count??0}</strong></div><div><span>Obligated</span><strong>{money(prime?.award_summary.obligated_amount)}</strong></div><div><span>Potential value</span><strong>{money(prime?.award_summary.potential_amount)}</strong></div></div><div className="subcontract-agency-list">{relatedAgencies.map((row,index)=><div key={index}><Landmark/><span><strong>{row.awarding_agency}</strong><small>{row.awards} awards · {money(row.obligated)}</small></span></div>)}</div></section><section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">PARENT CONTRACT RESEARCH</span><h2>Possible contract relationships</h2></div><small>{data.parent_contract_candidates.length} signals</small></div><div className="intelligence-list">{data.parent_contract_candidates.length?data.parent_contract_candidates.map((row,index)=><article key={`${row.award_id??row.award_number}-${index}`}><FileSearch/><div><span>{row.classification?.replaceAll("_"," ")}</span><strong>{row.award_number||row.award_id||"Historical award"}</strong><p>{row.awarding_agency||"Agency unavailable"} · {money(row.obligated_amount)} obligated</p><small>{row.match_reason}</small></div></article>):<div className="table-state compact-state"><FileSearch/><strong>No reliable parent-contract candidate yet</strong><p>ForgeGov will not manufacture a parent-contract relationship without evidence.</p></div>}</div></section><section className="data-panel subcontract-award-history"><div className="panel-title-row"><div><span className="eyebrow">PUBLIC AWARDS</span><h2>Recent prime award history</h2></div></div><div className="intelligence-list">{prime?.recent_awards.map((row,index)=><article key={`${row.award_id}-${index}`}><Building2/><div><span>{row.awarding_agency}</span><strong>{row.award_number||row.award_id}</strong><p>{money(row.obligated_amount)} obligated · NAICS {row.naics_code||"—"}</p><small>{row.start_date?new Date(row.start_date).toLocaleDateString():""}{row.end_date?` → ${new Date(row.end_date).toLocaleDateString()}`:""}</small></div></article>)}</div></section></div>}

    {activeTab==="capture"&&<div className="subcontract-detail-grid" data-qa="subcontract-detail-grid" data-qa-no-x-overflow="true"><section className="data-panel"><div className="panel-title-row"><div><span className="eyebrow">CAPTURE WORKFLOW</span><h2>Pursuit status</h2></div></div>{data.pipeline.active?<div className="subcontract-capture-state"><Target/><div><strong>{data.pipeline.stage.replaceAll("_"," ")}</strong><p>{data.pipeline.next_action||"No next action recorded yet."}</p><small>{data.pipeline.owner||"Unassigned"} · {data.pipeline.probability_of_win}% probability</small></div><Link className="primary-button" href={data.capture_links.pipeline}>Open pipeline</Link></div>:<div className="table-state"><Target/><strong>Activate capture management</strong><p>Add this listing to Pipeline to assign ownership, follow-ups, decision gates, proposal work, and Project Rooms.</p><button className="primary-button" onClick={()=>void addToPipeline()}>Add to pipeline</button></div>}</section><section className="data-panel subcontract-ai-panel"><div className="panel-heading"><Bot/><div><h2>ForgeAI subcontract analyst</h2><p>Analyze the listing together with public prime and parent-contract evidence while keeping inference clearly labeled.</p></div></div><textarea rows={5} value={question} onChange={e=>setQuestion(e.target.value)}/><button className="primary-button" disabled={aiBusy||question.trim().length<2} onClick={()=>void askAI()}>{aiBusy?"Analyzing…":"Analyze pursuit"}</button>{answer&&<div className="ai-readable-answer">{answer}</div>}</section></div>}

    {activeTab==="collaboration"&&<div className="subcontract-detail-grid" data-qa="subcontract-detail-grid" data-qa-no-x-overflow="true"><section className="data-panel"><div className="panel-heading"><Users/><div><h2>Work with your team</h2><p>Move subcontract opportunities through the same ForgeGov collaboration workflows used for prime pursuits.</p></div></div><div className="settings-link-list"><Link href="/project-rooms"><Users/><div><strong>Project Rooms</strong><span>Create a secure internal or cross-company collaboration room after adding the opportunity to Pipeline.</span></div><ExternalLink/></Link><Link href="/network"><Building2/><div><strong>ForgeGov Network</strong><span>Find partners to close capability or past-performance gaps.</span></div><ExternalLink/></Link></div></section><section className="data-panel"><div className="panel-heading"><Mail/><div><h2>Microsoft 365</h2><p>Email the opportunity with Outlook, create a deadline/review event, or share it to the configured Teams channel.</p></div></div><MicrosoftActions title={opportunity?.title??"Subcontract opportunity"} summary={opportunity?.description} sourceUrl={opportunity?.source_url} deadline={opportunity?.closing_date??""} agency={opportunity?.prime_contractor} solicitationNumber={opportunity?.solicitation_number}/></section></div>}
  </main>;
}
