# Generated by Django 5.2.17 on 2026-08-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformauditevent',
            new_name='platform_ad_created_e2eecc_idx',
            old_name='platform_ad_created_4cd240_idx',
        ),
        migrations.RenameIndex(
            model_name='platformauditevent',
            new_name='platform_ad_action_ba9c55_idx',
            old_name='platform_ad_action_9c6aa1_idx',
        ),
        migrations.RenameIndex(
            model_name='platformauditevent',
            new_name='platform_ad_target__44e646_idx',
            old_name='platform_ad_target__17d341_idx',
        ),
    ]
