"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Mail, RefreshCw, ShieldCheck, UserPlus, Users } from "lucide-react";
import { apiDelete, apiGet, apiPatch, apiPost, authFetch } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";

type Profile={organization_name:string;uei:string;cage_code:string;tagline:string;description:string;website:string;city:string;state:string;country:string;naics_codes:string[];psc_codes:string[];capabilities:string[];certifications:string[];contract_vehicles:string[];service_areas:string[];contact_email:string;is_public:boolean;accepting_partners:boolean};
type Member={id:number;role:string;job_title:string;department:string;active:boolean;user:{id:number;email:string;first_name:string;last_name:string}};
type Invite={id:number;email:string;role:string;job_title:string;department:string;status:string;expires_at:string;resend_count:number;last_sent_at?:string;invite_url?:string;email_delivered?:boolean};
type Partner={id:number;requester:number;requester_name:string;recipient:number;recipient_name:string;status:string};
type IntegrationStatus={email?:{configured:boolean;backend:string;from_email:string}};
type JoinRequest={id:number;organization_name:string;user_email:string;email_domain:string;requested_role:string;status:string;created_at:string};
const split=(value:string)=>value.split(",").map(v=>v.trim()).filter(Boolean);
const roles=["admin","capture","bd","proposal","viewer"];

export default function CompanyHubPage(){
 const {session}=useAuth(); const admin=["owner","admin"].includes(session?.role||"");
 const [profile,setProfile]=useState<Profile|null>(null); const [members,setMembers]=useState<Member[]>([]); const [invites,setInvites]=useState<Invite[]>([]); const [partners,setPartners]=useState<Partner[]>([]); const [joinRequests,setJoinRequests]=useState<JoinRequest[]>([]); const [emailStatus,setEmailStatus]=useState<IntegrationStatus["email"]>();
 const [email,setEmail]=useState(""); const [role,setRole]=useState("viewer"); const [jobTitle,setJobTitle]=useState(""); const [department,setDepartment]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState("");
 const load=useCallback(async()=>{try{const [p,m,i,c,j,status]=await Promise.all([apiGet<Profile>("/network/profile/"),admin?authFetch<Member[]>("/team/members/"):Promise.resolve([]),admin?authFetch<Invite[]>("/team/invitations/"):Promise.resolve([]),apiGet<Partner[]>("/network/connections/?status=accepted"),admin?apiGet<JoinRequest[]>("/company/join-requests/"):Promise.resolve([]),apiGet<IntegrationStatus>("/integrations/status/")]);setProfile(p);setMembers(m);setInvites(i);setPartners(c);setJoinRequests(j);setEmailStatus(status.email);setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"Company Hub could not be loaded")}},[admin]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const activeMembers=useMemo(()=>members.filter(m=>m.active!==false),[members]);
 async function saveProfile(e:FormEvent){e.preventDefault();if(!profile)return;setBusy("profile");try{await apiPatch("/network/profile/",{...profile,name:profile.organization_name});setMessage("Company profile saved.")}catch(error){setMessage(error instanceof Error?error.message:"Profile save failed")}finally{setBusy("")}}
 async function invite(e:FormEvent){e.preventDefault();setBusy("invite");try{const result=await authFetch<Invite>("/team/invitations/",{method:"POST",body:JSON.stringify({email,role,job_title:jobTitle,department})});setMessage(result.email_delivered===false?"Invitation created in ForgeGov, but email delivery failed. Copy the invitation link or resend after email is configured.":"Invitation sent by email and added to the invitation manager.");setEmail("");setJobTitle("");setDepartment("");await load()}catch(error){setMessage(error instanceof Error?error.message:"Invitation failed")}finally{setBusy("")}}
 async function invitationAction(id:number,action:"resend"|"cancel"){setBusy(`invite-${id}`);try{await authFetch(`/team/invitations/${id}/action/`,{method:"POST",body:JSON.stringify({action})});setMessage(action==="resend"?"Invitation resent.":"Invitation cancelled.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Invitation update failed")}finally{setBusy("")}}
 async function updateMember(member:Member,patch:Partial<Member>){setBusy(`member-${member.id}`);try{await authFetch(`/team/members/${member.id}/`,{method:"PATCH",body:JSON.stringify(patch)});await load()}catch(error){setMessage(error instanceof Error?error.message:"Member update failed")}finally{setBusy("")}}
 async function removeMember(member:Member){if(!window.confirm(`Remove ${member.user.email} from this company workspace?`))return;setBusy(`member-${member.id}`);try{await apiDelete(`/team/members/${member.id}/`);await load()}catch(error){setMessage(error instanceof Error?error.message:"Member removal failed")}finally{setBusy("")}}
 async function respondJoinRequest(id:number,action:"approve"|"decline"){setBusy(`join-${id}`);try{await apiPost(`/company/join-requests/${id}/respond/`,{action});setMessage(action==="approve"?"Join request approved. The user can now switch into this workspace.":"Join request declined.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Join request update failed")}finally{setBusy("")}}
 return <div className="page-stack company-hub-page"><header className="module-header"><div><span className="eyebrow">COMPANY HUB</span><h1>{session?.organization.name}</h1><p>Manage company information, employees, invitations, roles, capabilities, and partner relationships from one place.</p></div><button className="secondary-button" onClick={()=>void load()}><RefreshCw size={16}/> Refresh</button></header>
 <section className="workspace-summary"><div><span>Active employees</span><strong>{activeMembers.length}</strong><small>Company-controlled memberships</small></div><div><span>Pending invitations</span><strong>{invites.filter(i=>i.status==="pending").length}</strong><small>Email-bound and expiring</small></div><div><span>Connected partners</span><strong>{partners.filter(p=>p.status==="accepted").length}</strong><small>Eligible for Project Room invites</small></div><div><span>Directory profile</span><strong>{profile?.is_public?"Public":"Private"}</strong><small>{profile?.accepting_partners?"Accepting partners":"Not accepting partners"}</small></div></section>
 {message&&<div className="system-banner warning">{message}</div>}{emailStatus&&!emailStatus.configured&&<div className="system-banner warning email-setup-banner"><strong>Email delivery is not configured.</strong><span>Invitations remain available in ForgeGov. To deliver external email, verify forge-gov.com with a transactional provider and add the SMTP values below to the production environment.</span><details><summary>Recommended Resend SMTP values</summary><code>EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend<br/>EMAIL_HOST=smtp.resend.com<br/>EMAIL_PORT=587<br/>EMAIL_HOST_USER=resend<br/>EMAIL_HOST_PASSWORD=&lt;API_KEY&gt;<br/>EMAIL_USE_TLS=true<br/>DEFAULT_FROM_EMAIL=ForgeGov &lt;notifications@forge-gov.com&gt;</code></details></div>}
 {profile&&<section className="data-panel"><div className="panel-heading"><Building2/><div><h2>Company profile and capabilities</h2><p>This information feeds Network discovery, partner matching, and ForgeAI context.</p></div></div><form className="company-hub-form" onSubmit={saveProfile}><div className="form-grid"><label>Company name<input value={profile.organization_name||""} onChange={e=>setProfile({...profile,organization_name:e.target.value})}/></label><label>UEI<input value={profile.uei||""} onChange={e=>setProfile({...profile,uei:e.target.value})}/></label><label>CAGE code<input value={profile.cage_code||""} onChange={e=>setProfile({...profile,cage_code:e.target.value})}/></label><label>Tagline<input value={profile.tagline||""} onChange={e=>setProfile({...profile,tagline:e.target.value})}/></label><label>Website<input value={profile.website||""} onChange={e=>setProfile({...profile,website:e.target.value})}/></label><label>Contact email<input type="email" value={profile.contact_email||""} onChange={e=>setProfile({...profile,contact_email:e.target.value})}/></label><label>Location<input value={[profile.city,profile.state].filter(Boolean).join(", ")} onChange={e=>{const [city,...rest]=e.target.value.split(",");setProfile({...profile,city:city.trim(),state:rest.join(",").trim()})}} placeholder="Texarkana, TX"/></label></div><label>Company description<textarea value={profile.description||""} onChange={e=>setProfile({...profile,description:e.target.value})}/></label><div className="form-grid"><label>Capabilities<input value={profile.capabilities.join(", ")} onChange={e=>setProfile({...profile,capabilities:split(e.target.value)})}/></label><label>NAICS codes<input value={profile.naics_codes.join(", ")} onChange={e=>setProfile({...profile,naics_codes:split(e.target.value)})}/></label><label>PSC codes<input value={profile.psc_codes.join(", ")} onChange={e=>setProfile({...profile,psc_codes:split(e.target.value)})}/></label><label>Certifications<input value={profile.certifications.join(", ")} onChange={e=>setProfile({...profile,certifications:split(e.target.value)})}/></label></div><div className="check-row"><label><input type="checkbox" checked={profile.is_public} onChange={e=>setProfile({...profile,is_public:e.target.checked})}/> Visible in Network</label><label><input type="checkbox" checked={profile.accepting_partners} onChange={e=>setProfile({...profile,accepting_partners:e.target.checked})}/> Accepting partners</label></div><button className="primary-button" disabled={busy==="profile"}>Save company profile</button></form></section>}
 <section className="company-hub-grid"><article className="data-panel"><div className="panel-heading"><Users/><div><h2>Team members</h2><p>The company controls membership and permissions; people keep their own login identity.</p></div></div>{!admin?<p>Only owners and administrators can manage membership.</p>:<div className="company-member-list">{members.map(member=><div className="company-member-row" key={member.id}><div><strong>{[member.user.first_name,member.user.last_name].filter(Boolean).join(" ")||member.user.email}</strong><small>{member.user.email}</small></div><input aria-label="Job title" value={member.job_title||""} onChange={e=>setMembers(rows=>rows.map(r=>r.id===member.id?{...r,job_title:e.target.value}:r))} onBlur={()=>void updateMember(member,{job_title:member.job_title})} placeholder="Job title"/><input aria-label="Department" value={member.department||""} onChange={e=>setMembers(rows=>rows.map(r=>r.id===member.id?{...r,department:e.target.value}:r))} onBlur={()=>void updateMember(member,{department:member.department})} placeholder="Department"/><select value={member.role} disabled={member.role==="owner"} onChange={e=>void updateMember(member,{role:e.target.value})}>{member.role==="owner"&&<option value="owner">Owner</option>}{roles.map(r=><option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select><button className="secondary-button" disabled={member.role==="owner"||busy===`member-${member.id}`} onClick={()=>void updateMember(member,{active:!member.active})}>{member.active===false?"Reactivate":"Suspend"}</button><button className="secondary-button danger-button" disabled={member.role==="owner"} onClick={()=>void removeMember(member)}>Remove</button></div>)}</div>}</article>
 <article className="data-panel"><div className="panel-heading"><UserPlus/><div><h2>Invite an employee</h2><p>Employees join this company only through a single-use email invitation.</p></div></div>{admin&&<form className="invite-company-form" onSubmit={invite}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Job title<input value={jobTitle} onChange={e=>setJobTitle(e.target.value)} placeholder="Capture Manager"/></label><label>Department<input value={department} onChange={e=>setDepartment(e.target.value)} placeholder="Business Development"/></label><label>System role<select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option value={r} key={r}>{r.replaceAll("_"," ")}</option>)}</select></label><button className="primary-button" disabled={busy==="invite"}><Mail size={16}/> Send invitation</button></form>}</article></section>
 {admin&&<section className="data-panel"><div className="panel-heading"><ShieldCheck/><div><h2>Domain join requests</h2><p>Matching a verified company domain suggests the correct workspace, but owners and administrators approve access.</p></div></div>{joinRequests.length?<div className="invitation-manager">{joinRequests.map(row=><article key={row.id}><div><strong>{row.user_email}</strong><small>Verified domain: {row.email_domain}</small></div><span className={`status-pill status-${row.status}`}>{row.status}</span>{row.status==="pending"&&<div className="row-actions"><button className="primary-button" disabled={busy===`join-${row.id}`} onClick={()=>void respondJoinRequest(row.id,"approve")}>Approve</button><button className="secondary-button" disabled={busy===`join-${row.id}`} onClick={()=>void respondJoinRequest(row.id,"decline")}>Decline</button></div>}</article>)}</div>:<div className="table-state compact-state"><strong>No pending domain requests</strong><p>Employees can request access when their email domain matches the verified company website.</p></div>}</section>}
 <section className="data-panel"><div className="panel-heading"><ShieldCheck/><div><h2>Invitation manager</h2><p>Track delivery, expiration, acceptance, cancellation, and resends.</p></div></div><div className="invitation-manager">{invites.map(invite=><article key={invite.id}><div><strong>{invite.email}</strong><small>{invite.job_title||invite.role} {invite.department?`· ${invite.department}`:""}</small></div><span className={`status-pill status-${invite.status}`}>{invite.status}</span><small>Expires {new Date(invite.expires_at).toLocaleString()}</small><small>Resent {invite.resend_count||0} times</small>{invite.status==="pending"&&<div className="row-actions"><button className="secondary-button" onClick={()=>void invitationAction(invite.id,"resend")}>Resend</button><button className="secondary-button danger-button" onClick={()=>void invitationAction(invite.id,"cancel")}>Cancel</button></div>}</article>)}</div></section></div>;
}
