type DescriptorJson={id:string;type:PublicKeyCredentialType;transports?:AuthenticatorTransport[]};
type RegistrationJson={challenge:string;user:{id:string;name:string;displayName:string};excludeCredentials?:DescriptorJson[];[key:string]:unknown};
type AuthenticationJson={challenge:string;allowCredentials?:DescriptorJson[];[key:string]:unknown};

function fromBase64url(value:string):ArrayBuffer{const padding="=".repeat((4-(value.length%4))%4);const base64=(value+padding).replace(/-/g,"+").replace(/_/g,"/");const raw=atob(base64);const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i+=1)bytes[i]=raw.charCodeAt(i);return bytes.buffer}
function toBase64url(value:ArrayBuffer):string{const bytes=new Uint8Array(value);let raw="";for(const byte of bytes)raw+=String.fromCharCode(byte);return btoa(raw).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
export function registrationOptions(options:RegistrationJson):PublicKeyCredentialCreationOptions{return{...options,challenge:fromBase64url(options.challenge),user:{...options.user,id:fromBase64url(options.user.id)},excludeCredentials:(options.excludeCredentials??[]).map(row=>({...row,id:fromBase64url(row.id)}))} as PublicKeyCredentialCreationOptions}
export function authenticationOptions(options:AuthenticationJson):PublicKeyCredentialRequestOptions{return{...options,challenge:fromBase64url(options.challenge),allowCredentials:(options.allowCredentials??[]).map(row=>({...row,id:fromBase64url(row.id)}))} as PublicKeyCredentialRequestOptions}
export function serializeCredential(credential:PublicKeyCredential):Record<string,unknown>{const response=credential.response;const common={id:credential.id,rawId:toBase64url(credential.rawId),type:credential.type,authenticatorAttachment:credential.authenticatorAttachment,clientExtensionResults:credential.getClientExtensionResults()};if(response instanceof AuthenticatorAttestationResponse){return{...common,response:{clientDataJSON:toBase64url(response.clientDataJSON),attestationObject:toBase64url(response.attestationObject),transports:typeof response.getTransports==="function"?response.getTransports():[]}}}const assertion=response as AuthenticatorAssertionResponse;return{...common,response:{clientDataJSON:toBase64url(assertion.clientDataJSON),authenticatorData:toBase64url(assertion.authenticatorData),signature:toBase64url(assertion.signature),userHandle:assertion.userHandle?toBase64url(assertion.userHandle):null}}}
