# Generated by Django 5.2.16 on 2026-07-20 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('uei', models.CharField(blank=True, max_length=32)),
                ('cage_code', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='sam.gov', max_length=40)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('solicitation_number', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('subagency', models.CharField(blank=True, max_length=255)),
                ('notice_type', models.CharField(choices=[('solicitation', 'Solicitation'), ('sources_sought', 'Sources Sought'), ('presolicitation', 'Presolicitation'), ('award', 'Award Notice'), ('special', 'Special Notice'), ('other', 'Other')], default='other', max_length=40)),
                ('naics_code', models.CharField(blank=True, max_length=12)),
                ('set_aside', models.CharField(blank=True, max_length=255)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('place_of_performance', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('source_modified_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['response_deadline', '-posted_date'],
                'indexes': [models.Index(fields=['source', 'source_id'], name='core_opport_source_29e9c8_idx'), models.Index(fields=['solicitation_number'], name='core_opport_solicit_44432f_idx'), models.Index(fields=['naics_code'], name='core_opport_naics_c_3626da_idx'), models.Index(fields=['response_deadline'], name='core_opport_respons_ea8351_idx')],
            },
        ),
        migrations.CreateModel(
            name='PipelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('discovered', 'Discovered'), ('reviewing', 'Reviewing'), ('qualified', 'Qualified'), ('bid_decision', 'Bid / No-Bid'), ('capture', 'Capture Planning'), ('teaming', 'Teaming'), ('proposal', 'Proposal Development'), ('submitted', 'Submitted'), ('awarded', 'Awarded'), ('lost', 'Lost'), ('no_bid', 'No-Bid'), ('archived', 'Archived')], default='discovered', max_length=30)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('probability_of_win', models.PositiveSmallIntegerField(default=0)),
                ('next_action', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_items', to='core.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_items', to='core.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pipeline_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'opportunity')},
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('filters', models.JSONField(default=dict)),
                ('alert_frequency', models.CharField(default='daily', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='core.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forgegov_saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_forgegov_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.organization')),
                ('pipeline_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.pipelineitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('capture', 'Capture Manager'), ('bd', 'Business Development'), ('proposal', 'Proposal Writer'), ('viewer', 'Read Only')], default='viewer', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
