# Generated by Django 5.2.16 on 2026-07-20 12:25

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pipelineitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='notice_type_raw',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='office',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='organization_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='psc_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='resource_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='set_aside_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='notice_type',
            field=models.CharField(choices=[('solicitation', 'Solicitation'), ('combined', 'Combined Synopsis / Solicitation'), ('sources_sought', 'Sources Sought'), ('presolicitation', 'Presolicitation'), ('award', 'Award Notice'), ('special', 'Special Notice'), ('justification', 'Justification'), ('surplus', 'Sale of Surplus Property'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='pipelineitem',
            name='probability_of_win',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['psc_code'], name='core_opport_psc_cod_8bc82a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['active', 'posted_date'], name='core_opport_active_b52455_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_membership'),
        ),
        migrations.AddConstraint(
            model_name='pipelineitem',
            constraint=models.UniqueConstraint(fields=('organization', 'opportunity'), name='unique_pipeline_opportunity_per_org'),
        ),
        migrations.AddIndex(
            model_name='datasyncrun',
            index=models.Index(fields=['source', 'status', '-started_at'], name='core_datasy_source_15c206_idx'),
        ),
    ]
