# Generated by Django 5.2.16 on 2026-07-21 08:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datasyncrun_alter_membership_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('agency_code', models.CharField(blank=True, max_length=32)),
                ('agency_type', models.CharField(default='federal', max_length=40)),
                ('parent_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('opportunity_count', models.PositiveIntegerField(default=0)),
                ('award_count', models.PositiveIntegerField(default=0)),
                ('obligated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='usaspending.gov', max_length=80)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('award_number', models.CharField(blank=True, db_index=True, max_length=160)),
                ('award_type', models.CharField(choices=[('contract', 'Federal Contract'), ('idv', 'Federal IDV'), ('vehicle', 'Federal Contract Vehicle'), ('grant', 'Federal Grant'), ('state_local', 'State and Local Contract'), ('state_local_idv', 'State and Local IDV'), ('state_local_vehicle', 'State and Local Vehicle')], default='contract', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_uei', models.CharField(blank=True, max_length=32)),
                ('awarding_agency', models.CharField(blank=True, max_length=255)),
                ('funding_agency', models.CharField(blank=True, max_length=255)),
                ('obligated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('potential_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('naics_code', models.CharField(blank=True, max_length=12)),
                ('psc_code', models.CharField(blank=True, max_length=12)),
                ('place_of_performance', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-obligated_amount', '-updated_at'],
                'indexes': [models.Index(fields=['award_type', 'awarding_agency'], name='core_award_award_t_23291d_idx'), models.Index(fields=['recipient_name'], name='core_award_recipie_2a35f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('category_type', models.CharField(choices=[('naics', 'NAICS'), ('psc', 'PSC'), ('nigp', 'NIGP'), ('unspsc', 'UNSPSC')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('parent_code', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['category_type', 'code'],
                'constraints': [models.UniqueConstraint(fields=('category_type', 'code'), name='unique_category_type_code')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('contact_type', models.CharField(choices=[('government', 'Government'), ('vendor', 'Vendor'), ('partner', 'Partner'), ('internal', 'Internal')], default='government', max_length=30)),
                ('agency_name', models.CharField(blank=True, max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.organization')),
                ('relationship_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='groups', to='core.contact')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_groups', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('participant_type', models.CharField(choices=[('state', 'State'), ('jurisdiction', 'Jurisdiction'), ('other', 'Other')], default='other', max_length=40)),
                ('state_code', models.CharField(blank=True, max_length=4)),
                ('website', models.URLField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'participant_type'), name='unique_participant_type_name')],
            },
        ),
        migrations.CreateModel(
            name='Pursuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('stage', models.CharField(choices=[('triage', 'Triage'), ('qualify', 'Qualify'), ('bid_decision', 'Bid / No-Bid'), ('capture', 'Capture'), ('proposal', 'Proposal'), ('submitted', 'Submitted'), ('awarded', 'Awarded'), ('lost', 'Lost'), ('no_bid', 'No-Bid')], default='triage', max_length=30)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('probability_of_win', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=500)),
                ('incumbent', models.CharField(blank=True, max_length=255)),
                ('prime_or_sub', models.CharField(default='prime', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pursuits', to='core.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pursuits', to='core.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pursuits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('file_type', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(default='user', max_length=40)),
                ('source_url', models.URLField(blank=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_records', to='core.opportunity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_records', to='core.organization')),
                ('pursuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_records', to='core.pursuit')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(default='subcontractor', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('responded', 'Responded'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('closed', 'Closed')], default='draft', max_length=30)),
                ('capabilities', models.TextField(blank=True)),
                ('point_of_contact', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaming_requests', to='core.organization')),
                ('pursuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaming_requests', to='core.pursuit')),
            ],
            options={
                'ordering': ['status', 'due_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('uei', models.CharField(blank=True, db_index=True, max_length=32)),
                ('cage_code', models.CharField(blank=True, db_index=True, max_length=16)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('socioeconomic_statuses', models.JSONField(blank=True, default=list)),
                ('naics_codes', models.JSONField(blank=True, default=list)),
                ('claimed', models.BooleanField(default=False)),
                ('award_count', models.PositiveIntegerField(default=0)),
                ('obligated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_vendor_name_91f195_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pursuit',
            index=models.Index(fields=['organization', 'stage'], name='core_pursui_organiz_404806_idx'),
        ),
        migrations.AddIndex(
            model_name='pursuit',
            index=models.Index(fields=['due_date'], name='core_pursui_due_dat_2be277_idx'),
        ),
    ]
