from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[("core","0010_opportunity_document_intelligence"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="ProjectRoomTask",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("title",models.CharField(max_length=500)),("description",models.TextField(blank=True)),("status",models.CharField(choices=[("todo","To Do"),("in_progress","In Progress"),("review","Review"),("done","Done")],default="todo",max_length=20)),("priority",models.CharField(default="medium",max_length=20)),("visibility",models.CharField(choices=[("internal","Owner Company Only"),("shared","All Project Room Participants")],default="shared",max_length=20)),("due_date",models.DateField(blank=True,null=True)),("sort_order",models.PositiveIntegerField(default=0)),("assigned_to",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="project_room_tasks",to=settings.AUTH_USER_MODEL)),("created_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="created_project_room_tasks",to=settings.AUTH_USER_MODEL)),("project_room",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="collaboration_tasks",to="core.projectroom"))],options={"ordering":["status","sort_order","due_date","id"]}),
        migrations.CreateModel(name="ProjectRoomComment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("body",models.TextField()),("visibility",models.CharField(choices=[("internal","Owner Company Only"),("shared","All Project Room Participants")],default="shared",max_length=20)),("mentions",models.JSONField(blank=True,default=list)),("author",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="project_room_comments",to=settings.AUTH_USER_MODEL)),("project_room",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="comments",to="core.projectroom")),("task",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name="comments",to="core.projectroomtask"))],options={"ordering":["created_at"]}),
        migrations.CreateModel(name="ProjectRoomNote",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("title",models.CharField(max_length=255)),("body",models.TextField(blank=True)),("visibility",models.CharField(choices=[("internal","Owner Company Only"),("shared","All Project Room Participants")],default="internal",max_length=20)),("author",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="project_room_notes",to=settings.AUTH_USER_MODEL)),("project_room",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="notes",to="core.projectroom"))],options={"ordering":["-updated_at"]}),
        migrations.CreateModel(name="ProjectRoomFile",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("name",models.CharField(max_length=500)),("url",models.URLField(max_length=2000)),("description",models.TextField(blank=True)),("visibility",models.CharField(choices=[("internal","Owner Company Only"),("shared","All Project Room Participants"),("pricing","Pricing Authorized Participants")],default="shared",max_length=20)),("version",models.PositiveIntegerField(default=1)),("project_room",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="collaboration_files",to="core.projectroom")),("uploaded_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="project_room_files",to=settings.AUTH_USER_MODEL))],options={"ordering":["-updated_at"]}),
        migrations.CreateModel(name="ProjectRoomActivity",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("action",models.CharField(max_length=120)),("object_type",models.CharField(blank=True,max_length=80)),("object_id",models.CharField(blank=True,max_length=80)),("summary",models.CharField(max_length=500)),("visibility",models.CharField(choices=[("internal","Owner Company Only"),("shared","All Project Room Participants")],default="shared",max_length=20)),("metadata",models.JSONField(blank=True,default=dict)),("actor",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="project_room_activity",to=settings.AUTH_USER_MODEL)),("project_room",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="activity",to="core.projectroom"))],options={"ordering":["-created_at"]}),
        migrations.CreateModel(name="CollaborationNotification",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("title",models.CharField(max_length=255)),("message",models.TextField(blank=True)),("kind",models.CharField(default="project_room",max_length=60)),("read",models.BooleanField(default=False)),("link",models.CharField(blank=True,max_length=500)),("organization",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="collaboration_notifications",to="core.organization")),("project_room",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name="notifications",to="core.projectroom")),("user",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name="forgegov_collaboration_notifications",to=settings.AUTH_USER_MODEL))],options={"ordering":["-created_at"]}),
        migrations.AddConstraint(model_name="projectroomfile",constraint=models.UniqueConstraint(fields=("project_room","name","version"),name="unique_project_room_file_version")),
        migrations.AddIndex(model_name="projectroomtask",index=models.Index(fields=["project_room","status","visibility"],name="core_prtask_room_stat_vis_idx")),
        migrations.AddIndex(model_name="projectroomcomment",index=models.Index(fields=["project_room","visibility","created_at"],name="core_prcomment_room_vis_idx")),
        migrations.AddIndex(model_name="projectroomnote",index=models.Index(fields=["project_room","visibility","-updated_at"],name="core_prnote_room_vis_idx")),
        migrations.AddIndex(model_name="projectroomfile",index=models.Index(fields=["project_room","visibility","-updated_at"],name="core_prfile_room_vis_idx")),
        migrations.AddIndex(model_name="projectroomactivity",index=models.Index(fields=["project_room","visibility","-created_at"],name="core_practivity_room_vis_idx")),
        migrations.AddIndex(model_name="collaborationnotification",index=models.Index(fields=["organization","user","read","-created_at"],name="core_collabnotif_org_user_idx")),
    ]
