from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [("core", "0011_project_room_collaboration"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="OrganizationProfile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("tagline", models.CharField(blank=True, max_length=240)), ("description", models.TextField(blank=True)), ("website", models.URLField(blank=True)), ("city", models.CharField(blank=True, max_length=120)), ("state", models.CharField(blank=True, max_length=80)), ("country", models.CharField(blank=True, default="United States", max_length=80)), ("naics_codes", models.JSONField(blank=True, default=list)), ("psc_codes", models.JSONField(blank=True, default=list)), ("capabilities", models.JSONField(blank=True, default=list)), ("certifications", models.JSONField(blank=True, default=list)), ("contract_vehicles", models.JSONField(blank=True, default=list)), ("service_areas", models.JSONField(blank=True, default=list)), ("contact_email", models.EmailField(blank=True, max_length=254)), ("is_public", models.BooleanField(default=True)), ("accepting_partners", models.BooleanField(default=True)), ("verified", models.BooleanField(default=False)), ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="network_profile", to="core.organization"))], options={"ordering": ["organization__name"]}),
        migrations.CreateModel(name="NetworkConnection", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("declined", "Declined"), ("blocked", "Blocked")], default="pending", max_length=20)), ("message", models.TextField(blank=True)), ("responded_at", models.DateTimeField(blank=True, null=True)), ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="network_requests_received", to="core.organization")), ("requester", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="network_requests_sent", to="core.organization")), ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="network_connections_requested", to=settings.AUTH_USER_MODEL)), ("responded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="network_connections_responded", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-updated_at"]}),
        migrations.CreateModel(name="ProjectRoomInvitation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("declined", "Declined"), ("cancelled", "Cancelled")], default="pending", max_length=20)), ("access_level", models.CharField(choices=[("partner", "Teaming Partner"), ("subcontractor", "Subcontractor"), ("consultant", "Consultant"), ("viewer", "Viewer")], default="partner", max_length=20)), ("can_upload", models.BooleanField(default=True)), ("can_comment", models.BooleanField(default=True)), ("can_view_pricing", models.BooleanField(default=False)), ("message", models.TextField(blank=True)), ("responded_at", models.DateTimeField(blank=True, null=True)), ("invited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="project_room_invitations_sent", to=settings.AUTH_USER_MODEL)), ("invited_organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_room_invitations", to="core.organization")), ("project_room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="partner_invitations", to="core.projectroom")), ("responded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="project_room_invitations_responded", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.AddConstraint(model_name="networkconnection", constraint=models.UniqueConstraint(fields=("requester", "recipient"), name="unique_directional_network_connection")),
        migrations.AddConstraint(model_name="networkconnection", constraint=models.CheckConstraint(condition=~models.Q(("requester", models.F("recipient"))), name="network_connection_distinct_orgs")),
        migrations.AddIndex(model_name="networkconnection", index=models.Index(fields=["recipient", "status", "-created_at"], name="core_netconn_rec_stat_idx")),
        migrations.AddIndex(model_name="networkconnection", index=models.Index(fields=["requester", "status", "-created_at"], name="core_netconn_req_stat_idx")),
        migrations.AddConstraint(model_name="projectroominvitation", constraint=models.UniqueConstraint(condition=models.Q(("status", "pending")), fields=("project_room", "invited_organization"), name="unique_pending_project_room_invite")),
        migrations.AddIndex(model_name="projectroominvitation", index=models.Index(fields=["invited_organization", "status", "-created_at"], name="core_prinvite_org_stat_idx")),
    ]
