from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_pursuit_decision_intelligence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fringe_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("overhead_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("ga_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("material_handling_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("subcontract_handling_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("payroll_burden_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("default_profit_percent", models.DecimalField(decimal_places=3, default=12, max_digits=7)),
                ("minimum_margin_percent", models.DecimalField(decimal_places=3, default=8, max_digits=7)),
                ("annual_escalation_percent", models.DecimalField(decimal_places=3, default=3, max_digits=7)),
                ("payment_lag_days", models.PositiveIntegerField(default=30)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="pricing_profile", to="core.organization")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_pricing_profiles", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Target Pricing", max_length=255)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "Ready for Review"), ("approved", "Approved"), ("locked", "Locked")], default="draft", max_length=20)),
                ("fringe_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("overhead_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("ga_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("material_handling_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("subcontract_handling_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("payroll_burden_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("target_profit_percent", models.DecimalField(decimal_places=3, default=12, max_digits=7)),
                ("minimum_margin_percent", models.DecimalField(decimal_places=3, default=8, max_digits=7)),
                ("annual_escalation_percent", models.DecimalField(decimal_places=3, default=3, max_digits=7)),
                ("pursuit_cost", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_pricing_plans", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_pricing_plans", to=settings.AUTH_USER_MODEL)),
                ("opportunity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pricing_plans", to="core.opportunity")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pricing_plans", to="core.organization")),
            ],
            options={"ordering": ["-revision", "-updated_at"]},
        ),
        migrations.CreateModel(
            name="PricingClin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clin", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("option_year", models.PositiveSmallIntegerField(default=0)),
                ("quantity", models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ("unit", models.CharField(default="LOT", max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="clins", to="core.pricingplan")),
            ],
            options={"ordering": ["option_year", "sort_order", "clin"]},
        ),
        migrations.CreateModel(
            name="PricingCostItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(choices=[("labor", "Labor"), ("material", "Materials"), ("travel", "Travel"), ("equipment", "Equipment"), ("subcontract", "Subcontractor"), ("bond", "Bond"), ("insurance", "Insurance"), ("other", "Other Direct Cost")], max_length=30)),
                ("name", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ("labor_hours", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("labor_rate", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("option_year", models.PositiveSmallIntegerField(default=0)),
                ("escalation_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("source", models.CharField(blank=True, max_length=500)),
                ("source_kind", models.CharField(default="user", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("clin", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cost_items", to="core.pricingclin")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cost_items", to="core.pricingplan")),
            ],
            options={"ordering": ["option_year", "category", "sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="PricingScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scenario_type", models.CharField(choices=[("competitive", "Competitive"), ("target", "Target"), ("protective", "Protective")], max_length=20)),
                ("profit_percent", models.DecimalField(decimal_places=3, default=12, max_digits=7)),
                ("cost_adjustment_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("price_adjustment_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("notes", models.TextField(blank=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scenarios", to="core.pricingplan")),
            ],
            options={"ordering": ["scenario_type"]},
        ),
        migrations.AddConstraint(model_name="pricingplan", constraint=models.UniqueConstraint(fields=("organization", "opportunity", "revision"), name="uniq_priceplan_org_opp_rev")),
        migrations.AddIndex(model_name="pricingplan", index=models.Index(fields=["organization", "opportunity", "status"], name="priceplan_org_opp_stat")),
        migrations.AddConstraint(model_name="pricingclin", constraint=models.UniqueConstraint(fields=("plan", "clin", "option_year"), name="uniq_priceclin_plan_clin_yr")),
        migrations.AddIndex(model_name="pricingcostitem", index=models.Index(fields=["plan", "category", "option_year"], name="priceitem_plan_cat_yr")),
        migrations.AddConstraint(model_name="pricingscenario", constraint=models.UniqueConstraint(fields=("plan", "scenario_type"), name="uniq_pricescn_plan_type")),
    ]
