# Generated by Django 5.2.17 on 2026-08-12 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_portfolio_revenue_profit_intelligence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='business_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('capture', 'Capture Manager'), ('bd', 'Business Development'), ('proposal', 'Proposal Manager'), ('pricing', 'Pricing Manager'), ('contributor', 'Contributor'), ('viewer', 'Read Only')], default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('capture', 'Capture Manager'), ('bd', 'Business Development'), ('proposal', 'Proposal Manager'), ('pricing', 'Pricing Manager'), ('contributor', 'Contributor'), ('viewer', 'Read Only')], default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationjoinrequest',
            name='requested_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('capture', 'Capture Manager'), ('bd', 'Business Development'), ('proposal', 'Proposal Manager'), ('pricing', 'Pricing Manager'), ('contributor', 'Contributor'), ('viewer', 'Read Only')], default='viewer', max_length=20),
        ),
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifecycle_status', models.CharField(choices=[('pending_email_verification', 'Pending Email Verification'), ('email_verified', 'Email Verified'), ('onboarding', 'Onboarding'), ('pending_organization', 'Pending Organization Approval'), ('active', 'Active')], default='pending_email_verification', max_length=40)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('locked', 'Locked'), ('disabled', 'Disabled'), ('deletion_pending', 'Deletion Pending')], default='active', max_length=30)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_version', models.CharField(blank=True, max_length=40)),
                ('privacy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_version', models.CharField(blank=True, max_length=40)),
                ('registration_email_domain', models.CharField(blank=True, max_length=255)),
                ('last_password_change_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('pending_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_identity_profiles', to='core.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forgegov_security', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='AccountActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], max_length=30)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgegov_account_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', '-created_at'], name='accttoken_user_purp_idx'), models.Index(fields=['purpose', 'expires_at'], name='accttoken_purp_exp_idx')],
            },
        ),
    ]
